/**
 * lib/data/programs.ts
 * Server-only module. Reads programs-manifest.json (generated by scripts/build-valid-urls.js)
 * and provides typed lookups used by dynamic route pages and the sitemap.
 *
 * If the manifest is missing, run: npm run build:urls
 */

import { readFileSync } from 'fs'
import { join } from 'path'
import { UNIVERSITIES, getUniversityById, specSlug as toSlug, specName as toName } from '@/lib/data'

export interface ProgramRow {
  university_slug: string
  /** Lowercase program code: mba | mca | bba | bca | bcom | mcom | ba | ma | msc | bsc */
  program: string
  /** URL-safe spec slug, e.g. "human-resource-management". Empty string when row is the general program. */
  spec_slug: string
  /** Clean display name, e.g. "Human Resource Management". From the Excel `specialisation` column. */
  spec_name: string
}

let _rows: ProgramRow[] | null = null

function loadManifest(): ProgramRow[] {
  if (_rows !== null) return _rows
  try {
    const p = join(process.cwd(), 'lib', 'data', 'programs-manifest.json')
    _rows = JSON.parse(readFileSync(p, 'utf8')) as ProgramRow[]
  } catch {
    console.warn(
      '[lib/data/programs.ts] programs-manifest.json not found. Run: npm run build:urls'
    )
    _rows = []
  }
  return _rows
}

// Spec slug aliases: different names for the same specialization
// e.g. "financial-management" and "finance" are the same spec.
// Extensions in the "New from 2026-08-22 slug drift audit" block group
// slug variants that mean the same thing across universities (audit lives at
// audits/slug-drift-2026-08-22.md).
const SPEC_ALIASES: Record<string, string[]> = {
  'finance': ['financial-management', 'finance-management', 'finance-and-accounting'],
  'marketing': ['marketing-management', 'sales-and-marketing'],
  'human-resource-management': ['hr-management', 'hrm', 'hr', 'human-resource', 'human-resources', 'human-resources-management'],
  'operations-management': ['operations', 'production-and-operations-management', 'production-management', 'production-operations', 'production-operations-management'],
  'business-analytics': ['analytics', 'business-analytics-and-ai', 'data-analytics'],
  'digital-marketing': ['digital-marketing-management', 'digital-mktg'],
  'international-business': ['international-business-management', 'intl-business', 'ib'],
  'healthcare-management': ['hospital-management', 'hospital-administration', 'hospital-healthcare-management', 'hospital-and-healthcare-management', 'healthcare', 'hospital-and-health-care-management', 'hospital-health-care-management'],
  'information-technology': ['it-management', 'information-technology-management', 'it', 'it-systems', 'it-systems-management'],
  'supply-chain-management': ['logistics-and-supply-chain-management', 'logistics-supply-chain-management', 'logistics-scm', 'logistics-supply-chain', 'supply-chain-logistics', 'operations-and-supply-chain-management', 'operations-supply-chain-management'],
  'entrepreneurship': ['entrepreneurship-and-leadership-management', 'entrepreneur', 'entrepreneurship-management'],
  // data-science-ai is the single-dash form middleware's --  collapse rule
  // (line 410) produces from data-science--ai. Without it in this group the
  // collapsed URL resolved to nothing and section 2f 404'd it, so the chain
  // /universities/{uni}/mba/data-science--ai went 308 -> 404 for 18 universities.
  'data-science': ['data-science-and-analytics', 'data-science-analytics', 'data-science--ai', 'data-science-ai'],
  'general-management': ['general'],
  'cyber-security': ['cybersecurity', 'cyber-security-and-forensics', 'cyber-security-forensics'],
  'artificial-intelligence-and-machine-learning': ['ai-ml', 'ai-and-ml', 'artificial-intelligence-machine-learning', 'artificial-intelligence'],
  'blockchain-technology': ['blockchain', 'blockchain-technologies'],
  'cloud-computing': ['cloud-computing-and-internet-of-things', 'cloud-technology'],
  'full-stack-development': ['full-stack-web-development', 'full-stack-development-and-devops', 'full-stack'],
  'project-management': ['project-management-and-leadership'],
  'retail-management': ['retail', 'retail-ops'],
  'banking-and-insurance': ['banking-insurance', 'banking-finance', 'banking-and-financial-services', 'bfsi-banking-financial-services-and-insurance'],
  // New from 2026-08-22 slug drift audit. Each group ties slugs with the
  // same semantic. Do not merge distinct concepts here.
  'accounting-and-finance': ['accounting-finance'],
  'fintech': ['fintech-management'],
  'travel-and-tourism-management': ['travel-tourism-management', 'travel-tourism'],
  'cloud-technology-and-information-security': ['cloud-technology-information-security'],
  'data-science-and-artificial-intelligence': ['data-science-artificial-intelligence'],
  'computer-science-and-it': ['computer-science-it'],
  'agri-business-management': ['agri-business', 'agribusiness', 'agribusiness-management'],
  'artificial-intelligence-and-data-science': ['artificial-intelligence-data-science', 'ai-data-science', 'ai-and-data-science'],
  'finance-and-accounting-management': ['finance-accounting'],
  'hospitality-management': ['hospitality'],
  'marketing-and-sales-management': ['marketing-sales-management', 'marketing-sales'],
  'data-science-and-business-analytics': ['data-science-business-analytics'],
  'aviation-management': ['aviation'],
  'oil-and-gas-management': ['oil-gas-management'],
  'infrastructure-management': ['infrastructure'],
  'cloud-computing-and-cyber-security': ['cloud-computing-cyber-security'],
  'international-finance-and-accounting': ['international-finance-accounting'],
  'general-commerce-and-management': ['general-commerce'],
}

// Build reverse map: alias -> canonical
const _aliasToCanonical: Record<string, string> = {}
for (const [canonical, aliases] of Object.entries(SPEC_ALIASES)) {
  for (const alias of aliases) {
    _aliasToCanonical[alias] = canonical
  }
}

// MBA site-wide canonical overrides. Sprint 4 (2026-06-12, next.config.js
// lines 483-497) established these short-form slugs as the canonical for
// MBA via wildcard 301 redirects. Some universities still carry the long
// form in data.ts programDetails. Without this override, resolveSpec would
// return the long form for those unis and the route's own 301 would
// redirect the canonical short-form URL back to the long form, which
// next.config.js then redirects again to the short form: infinite loop.
// The override forces resolveSpec to report the short-form slug for MBA
// even when data.ts has the long form, matching next.config.js and
// keeping the response as a single 200 render.
const MBA_CANONICAL_OVERRIDES: Record<string, string> = {
  'human-resource-management': 'hr-management',
  'information-technology': 'it-management',
  'operations-management': 'operations',
  'retail-management': 'retail',
  'marketing-management': 'marketing',
  'financial-management': 'finance',
  'international-business-management': 'international-business',
  'entrepreneurship-management': 'entrepreneurship',
  'digital-marketing-management': 'digital-marketing',
  'hospital-healthcare-management': 'healthcare-management',
  'data-science-analytics': 'data-science',
  'logistics-supply-chain-management': 'supply-chain-management',
  // 2026-08-30: next.config.js line 619 redirects /universities/:uni/mba/
  // human-resource to hr-management sitewide, but resolveSpec canonicalised
  // Symbiosis the other way, to its data.ts slug human-resource. Once the edge
  // started serving that canonicalisation as a 308 the two rules pointed at
  // each other and the URL looped. next.config is the sitewide authority for
  // the MBA HR slug, so the resolver agrees with it here.
  'human-resource': 'hr-management',
}

/**
 * Look up a single row by (university_slug, program[, spec_slug]).
 * Falls back to alias matching if exact slug not found.
 * Returns null if no matching row exists.
 */
export function getProgram(
  slug: string,
  program: string,
  specSlug?: string
): ProgramRow | null {
  const prog = program.toLowerCase()
  const rows = loadManifest()
  if (specSlug) {
    // 1. Exact match
    const exact = rows.find(
      r => r.university_slug === slug && r.program === prog && r.spec_slug === specSlug
    )
    if (exact) return exact

    // 2. Try alias: specSlug might be an alias for a canonical slug
    const canonical = _aliasToCanonical[specSlug]
    if (canonical) {
      const aliasMatch = rows.find(
        r => r.university_slug === slug && r.program === prog && r.spec_slug === canonical
      )
      if (aliasMatch) return aliasMatch
    }

    // 3. Try reverse: specSlug might be a canonical, check if any alias exists in manifest
    const aliases = SPEC_ALIASES[specSlug]
    if (aliases) {
      for (const alias of aliases) {
        const rev = rows.find(
          r => r.university_slug === slug && r.program === prog && r.spec_slug === alias
        )
        if (rev) return rev
      }
    }

    return null
  }
  return rows.find(r => r.university_slug === slug && r.program === prog) ?? null
}

/**
 * All rows for a given university (all programs + specs).
 */
export function getUniversityPrograms(slug: string): ProgramRow[] {
  return loadManifest().filter(r => r.university_slug === slug)
}

/**
 * All specialisation rows for a (university, program) pair.
 * Excludes general-program rows (empty spec_slug).
 */
export function getAllSpecsForProgram(slug: string, program: string): ProgramRow[] {
  const prog = program.toLowerCase()
  return loadManifest().filter(
    r => r.university_slug === slug && r.program === prog && r.spec_slug !== ''
  )
}

/**
 * Clean display name for a specialisation, sourced from Excel.
 * Returns null when the (uni, program, specSlug) triple is not in the manifest.
 */
export function getSpecDisplayName(
  slug: string,
  program: string,
  specSlug: string
): string | null {
  const row = getProgram(slug, program.toLowerCase(), specSlug)
  if (!row) return null
  if (row.spec_name) return row.spec_name
  // Empty spec_name means the Excel source had no display name for this slug.
  // Return null so resolveSpecName can fall through to the lib/data.ts lookup,
  // which carries the correct display name (e.g. "Computer Applications – Data Science").
  return null
}

/**
 * Resolve a spec for a (university, program, specSlug) triple by checking
 * the manifest first, then falling back to lib/data.ts programDetails.
 *
 * Why both: the program-listing page (UniProgramBody → SpecializationGrid)
 * generates href slugs from `lib/data.ts` programDetails specs via specSlug().
 * The manifest is built from a separate Excel sheet that has drifted out of
 * sync. When a user clicks a listing link, we should always render content,
 * even if the manifest is missing that spec — otherwise the page 404s.
 *
 * Returns the canonical display name when found, null otherwise.
 */
export function resolveSpecName(
  uniId: string,
  programLabel: string,
  programSlug: string,
  specSlug: string
): string | null {
  return resolveSpec(uniId, programLabel, programSlug, specSlug)?.name ?? null
}

/**
 * Same lookup as resolveSpecName but returns both the display name AND the
 * actual matched slug (from data.ts or manifest). When the requested
 * `specSlug` resolves via an alias, the returned `slug` is the canonical
 * one the university uses in its programDetails / manifest. Route pages
 * should 301-redirect when `resolved.slug !== specSlug` so aliased URLs
 * consolidate onto one indexable URL per programme instead of creating
 * duplicate-content pairs.
 *
 * Slug-drift audit that motivated this: audits/slug-drift-2026-08-22.md
 * (43 drift groups, 28 uncovered before this pass).
 */
export function resolveSpec(
  uniId: string,
  programLabel: string,
  programSlug: string,
  specSlug: string
): { slug: string; name: string } | null {
  const u = getUniversityById(uniId)
  if (!u) return null
  const pd = (u.programDetails as Record<string, { specs?: unknown[] } | undefined>)[programLabel]
  const specs = (pd?.specs ?? []) as Array<string | { slug: string; name: string }>

  // 1. data.ts programDetails with alias fanout. data.ts is the source of
  // truth for which spec slug the uni actually offers, so we check it first.
  // Cross-verify audit (2026-08-22) caught 19 unis where checking manifest
  // first caused a canonical slug like `human-resource-management` to
  // redirect to the manifest's short form `hr-management`.
  const candidates = [specSlug]
  const canonical = _aliasToCanonical[specSlug]
  if (canonical) {
    candidates.push(canonical)
    const siblings = SPEC_ALIASES[canonical]
    if (siblings) candidates.push(...siblings)
  }
  const directAliases = SPEC_ALIASES[specSlug]
  if (directAliases) candidates.push(...directAliases)

  const prog = programSlug.toLowerCase()
  for (const cand of candidates) {
    const match = specs.find(s => toSlug(s as never) === cand)
    if (match) {
      let resolvedSlug = toSlug(match as never)
      // Apply MBA site-wide canonical override so the returned slug agrees
      // with next.config.js redirects. See MBA_CANONICAL_OVERRIDES above.
      if (prog === 'mba' && MBA_CANONICAL_OVERRIDES[resolvedSlug]) {
        resolvedSlug = MBA_CANONICAL_OVERRIDES[resolvedSlug]
      }
      // Prefer the manifest's Excel-sourced display name when it has one
      // for this exact triple, else fall back to the data.ts name.
      const manifestRow = loadManifest().find(
        r => r.university_slug === uniId && r.program === prog && r.spec_slug === resolvedSlug
      )
      const name = manifestRow?.spec_name || toName(match as never)
      return { slug: resolvedSlug, name }
    }
  }

  // 2. Manifest-only path for specs that live in the Excel manifest but not
  // in data.ts programDetails (Excel-only additions).
  const row = getProgram(uniId, programSlug, specSlug)
  if (row && row.spec_name) return { slug: row.spec_slug, name: row.spec_name }

  // 3. Last-resort title-case: only when the manifest carries a row for this
  // exact (uni, program, specSlug) triple but its spec_name is empty. Those
  // are the 238 rows enumerated in audits/fabricated-spec-urls-2026-08-17.csv
  // and audits/empty-spec-names-2026-08-17.csv. Any slug with no manifest row
  // returns null so the page 404s. The manifest is the allowlist.
  if (loadManifest().some(r => r.university_slug === uniId && r.program === prog && r.spec_slug === specSlug)) {
    return { slug: specSlug, name: titleCaseSlug(specSlug) }
  }
  return null
}

// Preserve casing of common acronyms that title-casing would otherwise mangle
// ("hr-management" → "Hr Management" instead of "HR Management"). Extend when
// a new acronym appears in a manifest slug.
const ACRONYMS = new Set(['HR', 'IT', 'AI', 'ML', 'ESG', 'MBA', 'BFSI', 'HRM', 'UI', 'UX'])

function titleCaseSlug(slug: string): string {
  return slug.split('-').map(w => {
    const up = w.toUpperCase()
    if (ACRONYMS.has(up)) return up
    return w.charAt(0).toUpperCase() + w.slice(1)
  }).join(' ')
}

/**
 * All (id, spec) param pairs for a program — used in generateStaticParams.
 *
 * Sources both the Excel manifest AND lib/data.ts programDetails so that
 * every spec linked from a /universities/{id}/{program} listing page also
 * gets statically generated. Without the data.ts source, ~1k spec links
 * 404 because the Excel manifest has drifted out of sync.
 */
export function getProgramSpecParams(
  program: string
): Array<{ id: string; spec: string }> {
  const prog = program.toLowerCase()
  const seen = new Set<string>()
  const out: Array<{ id: string; spec: string }> = []

  // Map lowercase program slug to the programDetails key used in lib/data.ts
  const PROG_LABEL: Record<string, string> = {
    mba: 'MBA', mca: 'MCA', bba: 'BBA', bca: 'BCA',
    bcom: 'B.Com', mcom: 'M.Com',
    ba: 'BA', ma: 'MA', msc: 'MSc', bsc: 'BSc',
  }
  const label = PROG_LABEL[prog]

  for (const r of loadManifest()) {
    if (r.program !== prog || !r.spec_slug) continue
    // If the university has no programDetails for this program, the spec page
    // calls redirect() during static generation. Next.js encodes that as a
    // meta-refresh HTML file instead of an HTTP 301. Skip those params so the
    // pages are never pre-rendered with meta-refresh behavior.
    if (label) {
      const u = getUniversityById(r.university_slug)
      if (u && !(u.programDetails as Record<string, unknown>)[label]) continue
    }
    const key = `${r.university_slug}|${r.spec_slug}`
    if (!seen.has(key)) {
      seen.add(key)
      out.push({ id: r.university_slug, spec: r.spec_slug })
    }
  }

  // Also include slugs derived from lib/data.ts programDetails.
  if (label) {
    for (const u of UNIVERSITIES) {
      const pd = (u.programDetails as Record<string, { specs?: unknown[] } | undefined>)[label]
      const specs = (pd?.specs ?? []) as Array<string | { slug: string; name: string }>
      for (const s of specs) {
        const slug = toSlug(s as never)
        if (!slug) continue
        const key = `${u.id}|${slug}`
        if (!seen.has(key)) {
          seen.add(key)
          out.push({ id: u.id, spec: slug })
        }
      }
    }
  }

  // Canonicalise before returning: prerender the slug the route settles on,
  // never an alias of it. Prerendering an alias makes Next encode the page's
  // redirect() as a meta-refresh 200 rather than an HTTP 308, the same trap the
  // programDetails guard above avoids. Measured 2026-08-29: 195 spec URLs were
  // served that way, e.g. /universities/amity-university-online/mba/hrm, each a
  // 200 whose canonical pointed somewhere else.
  //
  // Mapping every param through resolveSpec keeps the real page static and lets
  // the alias fall through to ISR, where redirect() returns a proper 308.
  // Params resolveSpec rejects are dropped: they only ever prerendered a
  // not-found shell, and middleware section 2f now 404s them at the edge.
  if (!label) return out
  const canonical: Array<{ id: string; spec: string }> = []
  const canonicalSeen = new Set<string>()
  for (const p of out) {
    const r = resolveSpec(p.id, label, prog, p.spec)
    if (!r) continue
    const key = `${p.id}|${r.slug}`
    if (canonicalSeen.has(key)) continue
    canonicalSeen.add(key)
    canonical.push({ id: p.id, spec: r.slug })
  }
  return canonical
}
