/**
 * lib/data/programs.ts
 * Server-only module. Reads programs-manifest.json (generated by scripts/build-valid-urls.js)
 * and provides typed lookups used by dynamic route pages and the sitemap.
 *
 * If the manifest is missing, run: npm run build:urls
 */

import { readFileSync } from 'fs'
import { join } from 'path'

export interface ProgramRow {
  university_slug: string
  /** Lowercase program code: mba | mca | bba | bca | bcom | mcom | ba | ma | msc | bsc */
  program: string
  /** URL-safe spec slug, e.g. "human-resource-management". Empty string when row is the general program. */
  spec_slug: string
  /** Clean display name, e.g. "Human Resource Management". From the Excel `specialisation` column. */
  spec_name: string
}

let _rows: ProgramRow[] | null = null

function loadManifest(): ProgramRow[] {
  if (_rows !== null) return _rows
  try {
    const p = join(process.cwd(), 'lib', 'data', 'programs-manifest.json')
    _rows = JSON.parse(readFileSync(p, 'utf8')) as ProgramRow[]
  } catch {
    console.warn(
      '[lib/data/programs.ts] programs-manifest.json not found. Run: npm run build:urls'
    )
    _rows = []
  }
  return _rows
}

/**
 * Look up a single row by (university_slug, program[, spec_slug]).
 * Returns null if the Excel has no matching row.
 */
export function getProgram(
  slug: string,
  program: string,
  specSlug?: string
): ProgramRow | null {
  const prog = program.toLowerCase()
  const rows = loadManifest()
  if (specSlug) {
    return rows.find(
      r => r.university_slug === slug && r.program === prog && r.spec_slug === specSlug
    ) ?? null
  }
  return rows.find(r => r.university_slug === slug && r.program === prog) ?? null
}

/**
 * All rows for a given university (all programs + specs).
 */
export function getUniversityPrograms(slug: string): ProgramRow[] {
  return loadManifest().filter(r => r.university_slug === slug)
}

/**
 * All specialisation rows for a (university, program) pair.
 * Excludes general-program rows (empty spec_slug).
 */
export function getAllSpecsForProgram(slug: string, program: string): ProgramRow[] {
  const prog = program.toLowerCase()
  return loadManifest().filter(
    r => r.university_slug === slug && r.program === prog && r.spec_slug !== ''
  )
}

/**
 * Clean display name for a specialisation, sourced from Excel.
 * Returns null when the (uni, program, specSlug) triple is not in the manifest.
 */
export function getSpecDisplayName(
  slug: string,
  program: string,
  specSlug: string
): string | null {
  const row = getProgram(slug, program.toLowerCase(), specSlug)
  if (!row) return null
  if (row.spec_name) return row.spec_name
  // Fallback: convert slug to Title Case when spec_name is empty in manifest
  return specSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

/**
 * All (id, spec) param pairs for a program — used in generateStaticParams.
 * Replaces iterating over UNIVERSITIES from lib/data.ts for spec pages.
 */
export function getProgramSpecParams(
  program: string
): Array<{ id: string; spec: string }> {
  const prog = program.toLowerCase()
  // Deduplicate: manifest may have duplicate (slug, spec_slug) from multiple Excel rows
  const seen = new Set<string>()
  const out: Array<{ id: string; spec: string }> = []
  for (const r of loadManifest()) {
    if (r.program !== prog || !r.spec_slug) continue
    const key = `${r.university_slug}|${r.spec_slug}`
    if (!seen.has(key)) {
      seen.add(key)
      out.push({ id: r.university_slug, spec: r.spec_slug })
    }
  }
  return out
}
