/**
 * lib/data/programs.ts
 * Server-only module. Reads programs-manifest.json (generated by scripts/build-valid-urls.js)
 * and provides typed lookups used by dynamic route pages and the sitemap.
 *
 * If the manifest is missing, run: npm run build:urls
 */

import { readFileSync } from 'fs'
import { join } from 'path'
import { UNIVERSITIES, getUniversityById, specSlug as toSlug, specName as toName } from '@/lib/data'

export interface ProgramRow {
  university_slug: string
  /** Lowercase program code: mba | mca | bba | bca | bcom | mcom | ba | ma | msc | bsc */
  program: string
  /** URL-safe spec slug, e.g. "human-resource-management". Empty string when row is the general program. */
  spec_slug: string
  /** Clean display name, e.g. "Human Resource Management". From the Excel `specialisation` column. */
  spec_name: string
}

let _rows: ProgramRow[] | null = null

function loadManifest(): ProgramRow[] {
  if (_rows !== null) return _rows
  try {
    const p = join(process.cwd(), 'lib', 'data', 'programs-manifest.json')
    _rows = JSON.parse(readFileSync(p, 'utf8')) as ProgramRow[]
  } catch {
    console.warn(
      '[lib/data/programs.ts] programs-manifest.json not found. Run: npm run build:urls'
    )
    _rows = []
  }
  return _rows
}

// Spec slug aliases: different names for the same specialization
// e.g. "financial-management" and "finance" are the same spec
const SPEC_ALIASES: Record<string, string[]> = {
  'finance': ['financial-management', 'finance-management', 'finance-and-accounting'],
  'marketing': ['marketing-management', 'sales-and-marketing'],
  'human-resource-management': ['hr-management', 'hrm', 'hr'],
  'operations-management': ['operations', 'production-and-operations-management', 'production-management'],
  'business-analytics': ['analytics', 'business-analytics-and-ai', 'data-analytics'],
  'digital-marketing': ['digital-marketing-management', 'digital-mktg'],
  'international-business': ['international-business-management', 'intl-business', 'ib'],
  'healthcare-management': ['hospital-management', 'hospital-administration', 'hospital-healthcare-management', 'hospital-and-healthcare-management'],
  'information-technology': ['it-management', 'information-technology-management', 'it'],
  'supply-chain-management': ['logistics-and-supply-chain-management', 'logistics-supply-chain-management', 'logistics-scm', 'logistics-supply-chain', 'supply-chain-logistics'],
  'entrepreneurship': ['entrepreneurship-and-leadership-management', 'entrepreneur'],
  'data-science': ['data-science-and-analytics', 'data-science-analytics', 'data-science--ai'],
  'general-management': ['general'],
  'cyber-security': ['cybersecurity', 'cyber-security-and-forensics', 'cyber-security-forensics'],
  'artificial-intelligence-and-machine-learning': ['ai-ml', 'ai-and-ml', 'artificial-intelligence-machine-learning', 'artificial-intelligence'],
  'blockchain-technology': ['blockchain', 'blockchain-technologies'],
  'cloud-computing': ['cloud-computing-and-internet-of-things', 'cloud-technology'],
  'full-stack-development': ['full-stack-web-development', 'full-stack-development-and-devops', 'full-stack'],
  'project-management': ['project-management-and-leadership'],
  'retail-management': ['retail', 'retail-ops'],
  'banking-and-insurance': ['banking-insurance', 'banking-finance', 'banking-and-financial-services', 'bfsi-banking-financial-services-and-insurance'],
}

// Build reverse map: alias -> canonical
const _aliasToCanonical: Record<string, string> = {}
for (const [canonical, aliases] of Object.entries(SPEC_ALIASES)) {
  for (const alias of aliases) {
    _aliasToCanonical[alias] = canonical
  }
}

/**
 * Look up a single row by (university_slug, program[, spec_slug]).
 * Falls back to alias matching if exact slug not found.
 * Returns null if no matching row exists.
 */
export function getProgram(
  slug: string,
  program: string,
  specSlug?: string
): ProgramRow | null {
  const prog = program.toLowerCase()
  const rows = loadManifest()
  if (specSlug) {
    // 1. Exact match
    const exact = rows.find(
      r => r.university_slug === slug && r.program === prog && r.spec_slug === specSlug
    )
    if (exact) return exact

    // 2. Try alias: specSlug might be an alias for a canonical slug
    const canonical = _aliasToCanonical[specSlug]
    if (canonical) {
      const aliasMatch = rows.find(
        r => r.university_slug === slug && r.program === prog && r.spec_slug === canonical
      )
      if (aliasMatch) return aliasMatch
    }

    // 3. Try reverse: specSlug might be a canonical, check if any alias exists in manifest
    const aliases = SPEC_ALIASES[specSlug]
    if (aliases) {
      for (const alias of aliases) {
        const rev = rows.find(
          r => r.university_slug === slug && r.program === prog && r.spec_slug === alias
        )
        if (rev) return rev
      }
    }

    return null
  }
  return rows.find(r => r.university_slug === slug && r.program === prog) ?? null
}

/**
 * All rows for a given university (all programs + specs).
 */
export function getUniversityPrograms(slug: string): ProgramRow[] {
  return loadManifest().filter(r => r.university_slug === slug)
}

/**
 * All specialisation rows for a (university, program) pair.
 * Excludes general-program rows (empty spec_slug).
 */
export function getAllSpecsForProgram(slug: string, program: string): ProgramRow[] {
  const prog = program.toLowerCase()
  return loadManifest().filter(
    r => r.university_slug === slug && r.program === prog && r.spec_slug !== ''
  )
}

/**
 * Clean display name for a specialisation, sourced from Excel.
 * Returns null when the (uni, program, specSlug) triple is not in the manifest.
 */
export function getSpecDisplayName(
  slug: string,
  program: string,
  specSlug: string
): string | null {
  const row = getProgram(slug, program.toLowerCase(), specSlug)
  if (!row) return null
  if (row.spec_name) return row.spec_name
  // Fallback: convert slug to Title Case when spec_name is empty in manifest
  return specSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

/**
 * Resolve a spec for a (university, program, specSlug) triple by checking
 * the manifest first, then falling back to lib/data.ts programDetails.
 *
 * Why both: the program-listing page (UniProgramBody → SpecializationGrid)
 * generates href slugs from `lib/data.ts` programDetails specs via specSlug().
 * The manifest is built from a separate Excel sheet that has drifted out of
 * sync. When a user clicks a listing link, we should always render content,
 * even if the manifest is missing that spec — otherwise the page 404s.
 *
 * Returns the canonical display name when found, null otherwise.
 */
export function resolveSpecName(
  uniId: string,
  programLabel: string,
  programSlug: string,
  specSlug: string
): string | null {
  // 1. Manifest path (preserves Excel-sourced display names + alias resolution)
  const fromManifest = getSpecDisplayName(uniId, programSlug, specSlug)
  if (fromManifest) return fromManifest

  const u = getUniversityById(uniId)
  if (!u) return null
  const pd = (u.programDetails as Record<string, { specs?: unknown[] } | undefined>)[programLabel]
  const specs = (pd?.specs ?? []) as Array<string | { slug: string; name: string }>
  const match = specs.find(s => toSlug(s as never) === specSlug)
  if (match) return toName(match as never)

  // 3. Last-resort: title-case the slug so we still render something readable
  // when a sitemap/external link points at a spec we know nothing about.
  // We only do this when the slug is at least plausible (alphanumeric + dashes).
  if (/^[a-z0-9][a-z0-9-]*$/.test(specSlug)) {
    return specSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
  }
  return null
}

/**
 * All (id, spec) param pairs for a program — used in generateStaticParams.
 *
 * Sources both the Excel manifest AND lib/data.ts programDetails so that
 * every spec linked from a /universities/{id}/{program} listing page also
 * gets statically generated. Without the data.ts source, ~1k spec links
 * 404 because the Excel manifest has drifted out of sync.
 */
export function getProgramSpecParams(
  program: string
): Array<{ id: string; spec: string }> {
  const prog = program.toLowerCase()
  const seen = new Set<string>()
  const out: Array<{ id: string; spec: string }> = []

  for (const r of loadManifest()) {
    if (r.program !== prog || !r.spec_slug) continue
    const key = `${r.university_slug}|${r.spec_slug}`
    if (!seen.has(key)) {
      seen.add(key)
      out.push({ id: r.university_slug, spec: r.spec_slug })
    }
  }

  // Also include slugs derived from lib/data.ts programDetails. Map lowercase
  // program slug to the case used in programDetails keys (MBA, MCA, BBA, BCA,
  // B.Com, M.Com, BA, MA, MSc, BSc).
  const PROG_LABEL: Record<string, string> = {
    mba: 'MBA', mca: 'MCA', bba: 'BBA', bca: 'BCA',
    bcom: 'B.Com', mcom: 'M.Com',
    ba: 'BA', ma: 'MA', msc: 'MSc', bsc: 'BSc',
  }
  const label = PROG_LABEL[prog]
  if (label) {
    for (const u of UNIVERSITIES) {
      const pd = (u.programDetails as Record<string, { specs?: unknown[] } | undefined>)[label]
      const specs = (pd?.specs ?? []) as Array<string | { slug: string; name: string }>
      for (const s of specs) {
        const slug = toSlug(s as never)
        if (!slug) continue
        const key = `${u.id}|${slug}`
        if (!seen.has(key)) {
          seen.add(key)
          out.push({ id: u.id, spec: slug })
        }
      }
    }
  }
  return out
}
