// lib/blog-quick-facts.ts
// Quick Facts data for blog posts — NOT auto-generated. Edit manually here.
// CMS sync never touches this file, so data survives every sync.

export const BLOG_QUICK_FACTS: Record<string, { label: string; value: string; green?: boolean }[]> = {
  'nmims-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Mode',              value: '100% Online' },
    { label: 'Semesters',         value: '4' },
    { label: 'Total Fee',         value: '₹1.96 Lakhs' },
    { label: 'Per Semester',      value: '₹55,000' },
    { label: 'Specialisations',   value: '5' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'AACSB Accredited',  value: 'Yes', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50%' },
  ],
  'symbiosis-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Total Fee',         value: '₹2.65 Lakhs' },
    { label: 'Per Semester',      value: '₹78,750' },
    { label: 'Specialisations',   value: '9' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'UGC-DEB Entitled',  value: 'Yes', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50%' },
  ],
  'amity-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Mode',              value: '100% Online' },
    { label: 'Indian Fee',        value: '₹2.07L (one-time) / ₹2.25L' },
    { label: 'Dual Spec Fee',     value: '₹2.99L' },
    { label: 'Intl Fee',          value: 'USD 5,000' },
    { label: 'Specialisations',   value: '19' },
    { label: 'NAAC Grade',        value: 'A+' },
    { label: 'QS Ranking',        value: 'Asia Top 10', green: true },
    { label: 'Entrance Exam',     value: 'None (40%+)', green: true },
    { label: 'Min. Marks',        value: '40%' },
  ],
  'ignou-online-mba-review-2026': [
    { label: 'Total Fee',         value: '₹66,000' },
    { label: 'Per Semester',      value: 'Confirmed by counsellor' },
    { label: 'Duration',          value: '2 to 4 Years' },
    { label: 'Mode',              value: 'Online (MBAOL)' },
    { label: 'Specialisations',   value: '5' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'NIRF Rank',         value: '#1 Open Univ' },
    { label: 'WES',               value: 'Recognised', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50% (45% reserved)' },
  ],
  'nmims-vs-symbiosis-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'NAAC (Both)',       value: 'A++', green: true },
    { label: 'NMIMS Fee',         value: '₹1.96L (standard)' },
    { label: 'Symbiosis Fee',     value: '₹3.70L (₹3.15L after 2+ yrs exp concession)' },
    { label: 'NMIMS NIRF Mgt',    value: '#24' },
    { label: 'Symbiosis NIRF Mgt', value: '#11' },
    { label: 'NMIMS Specs',       value: '6' },
    { label: 'Symbiosis Specs',   value: '9' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'jain-vs-amity-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'JAIN NAAC',         value: 'A++', green: true },
    { label: 'Amity NAAC',        value: 'A+' },
    { label: 'JAIN Fee',          value: '₹1.96L (standard)' },
    { label: 'Amity Fee',         value: '₹2.25L (standard)' },
    { label: 'JAIN NIRF Mgt',     value: '#73' },
    { label: 'Amity NIRF Mgt',    value: '#49' },
    { label: 'Specs (Both)',      value: '19 each' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'do-employers-accept-online-mba-india-2026': [
    { label: 'Type',              value: 'Pillar Guide' },
    { label: 'Focus',             value: 'Resume + Interview' },
    { label: 'Cluster',           value: 'Employer Perception' },
    { label: 'Key Insight',       value: 'Mode fading as filter', green: true },
    { label: 'Top Sectors',       value: 'IT, BFSI, FMCG, Govt' },
    { label: 'Best With',         value: 'MBA + Certification' },
    { label: 'UGC-DEB Required',  value: 'Yes', green: true },
    { label: 'NAAC Matters',      value: 'A+ / A++ strongest' },
  ],
  'best-online-bca-colleges-india-2026': [
    { label: 'Type',              value: 'Pillar (BCA Hub)' },
    { label: 'Universities',      value: '14 Ranked' },
    { label: 'Fee Range',         value: '₹49.8K - ₹1.77L' },
    { label: 'Top Pick',          value: 'LPU (₹1.22L, A++)' },
    { label: 'Budget Pick',       value: 'KL Univ (₹79K, A++)' },
    { label: 'Floor Price',       value: 'IGNOU ₹49,800' },
    { label: 'Duration',          value: '3 Years' },
    { label: 'UGC-DEB Required',  value: 'Yes', green: true },
  ],
  'amity-vs-manipal-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'Amity Fee',         value: '₹2.07L (one-time)' },
    { label: 'MUJ Fee',           value: '₹1.53L (one-time)' },
    { label: 'NAAC (Both)',       value: 'A+', green: true },
    { label: 'Amity NIRF Mgt',    value: '#49' },
    { label: 'MUJ NIRF Mgt',      value: '#81' },
    { label: 'Amity Specs',       value: '19' },
    { label: 'MUJ Specs',         value: '13' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'online-mba-business-analysts-india-2026': [
    { label: 'What the degree changes',                       value: '' },
    { label: 'Universities with a Business Analytics label',  value: '' },
    { label: 'Maths needed for admission',                    value: '' },
    { label: 'What decides programme quality',                value: '' },
  ],
  'online-mba-sales-professionals-india-2026': [
    { label: 'MBA labels that name sales',           value: '' },
    { label: 'Universities with a Marketing label',  value: '' },
    { label: 'What you will actually buy',           value: '' },
    { label: 'The paper to look for',                value: '' },
  ],
  'online-mba-medical-representatives-pharma-2026': [
    { label: 'What a field promotion runs on',                       value: '' },
    { label: 'What the degree opens',                                value: '' },
    { label: 'Universities with a Pharmaceutical Management label',  value: '' },
    { label: 'Do before you pay',                                    value: '' },
  ],
  'online-mba-hr-executives-india-2026': [
    { label: 'Universities with an HR Management label',  value: '' },
    { label: 'HR Analytics labels in our index',          value: '' },
    { label: 'The paper that must be there',              value: '' },
    { label: 'What the degree cannot supply',             value: '' },
  ],
  'online-mba-civil-site-engineers-project-management-2026': [
    { label: 'Universities with a Project Management label',        value: '' },
    { label: 'Project Management programmes with a NIRF Mgt rank',  value: '' },
    { label: 'The paper that matters most',                         value: '' },
    { label: 'When a certification beats the degree',               value: '' },
  ],
  'online-mba-nurses-healthcare-professionals-india-2026': [
    { label: 'Is BSc Nursing eligible for an MBA',  value: "Yes, it is a bachelor's degree" },
    { label: 'The one to check in writing',         value: '' },
    { label: 'Your real advantage',                 value: '' },
    { label: 'Watch on clinical institutions',      value: '' },
  ],
  'online-mba-chartered-accountants-india-2026': [
    { label: 'What the finance core gives a CA',   value: '' },
    { label: 'What you are actually buying',       value: '' },
    { label: 'Universities with a Finance label',  value: '' },
    { label: 'Ask in writing about ACCA labels',   value: '' },
  ],
  'online-mba-product-managers-india-2026': [
    { label: 'MBA labels naming Product Management',  value: '' },
    { label: 'What product hiring reads',             value: '' },
    { label: 'Most common route into product',        value: '' },
    { label: 'Buy the degree when',                   value: '' },
  ],
}

