// lib/blog.ts — Auto-generated by Edify CMS sync on 2026-03-25
// DO NOT edit manually — update via the "✍️ Blog Posts" Google Sheet

export interface BlogPost {
  slug: string; title: string; metaDescription: string; category: string
  tags: string[]; publishedAt: string; readTime: number; content: string
  faqs: { q: string; a: string }[]; relatedUniversities: string[]
  targetKeyword: string; status: 'published' | 'draft'
  ctaTitle?: string; ctaDesc?: string
}

export function getPublishedPosts() {
  return BLOG_POSTS
    .filter(p => p.status === 'published')
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
}
export function getPostBySlug(slug: string) { return BLOG_POSTS.find(p => p.slug === slug) || null }

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'amity-online-mba-hr-worth-it',
    title: 'Is Amity University Online MBA in HR Worth It? Real Talk from Someone Who Researched It',
    metaDescription: 'Considering Amity\'s online MBA in HR? Here\'s what actually matters - fees, placements, UGC recognition, and whether it\'ll help your career. No fluff.',
    category: 'Online MBA Programs',
    tags: ['amity university online mba', 'mba in hr online', 'online mba human resources', 'amity university distance mba', 'ugc approved online mba', 'best online mba hr', 'amity mba fees'],
    publishedAt: '2025-03-25',
    readTime: 8,
    targetKeyword: 'amity university online mba hr',
    relatedUniversities: [],
    status: 'published',
    faqs: [

    ],
    ctaTitle: '',
    ctaDesc: '',
    content: `
<h2>Why I Started Looking at Amity's Online MBA in HR</h2>

<p>I was three years into my HR career and stuck. Good job, decent pay, but no way up without an MBA. Problem was, I couldn't quit to do a full-time program. Can't afford two years without salary.</p>

<p>So I started looking at online MBAs. Amity kept showing up. Big name, tons of ads, friends mentioning it. But I needed to know if it was actually worth the money or just another overpriced degree mill.</p>

<p>Here's what I found out after weeks of research, talking to alumni, and nearly enrolling myself.</p>

<h2>The Basics (What Amity Won't Put in Bold)</h2>

<p>Amity University's online MBA in Human Resource Management is a two-year program. You need a bachelor's degree to apply - any stream works. The fees are somewhere between ₹2.5 to ₹3 lakhs for the full program, though they keep changing it.</p>

<p>It's UGC-DEB approved, which matters more than people think. Some companies won't touch online degrees that lack this approval. With UGC recognition, you're safe for most corporate jobs and even if you want to do PhD later.</p>

<h3>What You Actually Get</h3>

<p>The program includes:</p>
<ul>
<li>Live weekend classes (recorded if you miss them)</li>
<li>Online study materials and e-books</li>
<li>Access to their learning portal</li>
<li>Project work and case studies</li>
<li>Exams (online or at centers, depending on the semester)</li>
</ul>

<p>You're not getting classroom networking or campus placements like a regular MBA. But you knew that already.</p>

<h2>The HR Specialization - Is It Decent?</h2>

<p>The HR track covers what you'd expect: talent acquisition, performance management, labor laws, compensation planning, organizational behavior. Standard MBA HR stuff.</p>

<p>What I liked: The syllabus includes newer topics like HR analytics and digital HR transformation. Not every online program does this.</p>

<p>What felt weak: The practical exposure is limited. You'll do case studies, but you won't get hands-on experience with HRIS software or recruitment tools unless you're already using them at work.</p>

<p>Alumni I spoke with said the program gave them frameworks and concepts. One person told me it helped her move from HR executive to manager because she could finally talk strategy, not just operations.</p>

<h2>Who Actually Benefits from This Program</h2>

<p>This MBA makes sense if you're:</p>
<ul>
<li>Already working in HR and need the degree for promotion</li>
<li>In a related field (admin, operations) wanting to switch to HR</li>
<li>Running a small business and handling your own HR</li>
<li>Taking a career break and need flexibility</li>
</ul>

<p>It doesn't make sense if you're:</p>
<ul>
<li>Fresh out of college with no work experience (regular MBA would be better)</li>
<li>Expecting campus placements and a huge salary jump</li>
<li>Looking for intensive networking with classmates</li>
<li>Wanting IIM-level brand value (let's be real)</li>
</ul>

<h2>The Brand Factor - Does Amity's Name Help?</h2>

<p>Amity is well-known. That counts for something, especially in North India. HR managers recognize the name, which is more than you can say for random online universities.</p>

<p>But it's not going to open doors by itself. One recruiter told me she values Amity online MBA about the same as other UGC-approved online programs - it checks the box, but your experience matters more.</p>

<p>Where the brand helps: Internal promotions, government jobs that need a recognized MBA, and mid-level HR roles where degree + experience matter more than the college name.</p>

<h2>The Real Cost (Beyond Fees)</h2>

<p>Tuition is ₹2.5-3 lakhs. But there's more:</p>
<ul>
<li>Books and materials (if you want physical copies): ₹5,000-10,000</li>
<li>Exam center fees (varies by location)</li>
<li>Internet and laptop (you need decent specs for video classes)</li>
<li>Your time: 10-15 hours weekly minimum</li>
</ul>

<p>The time cost is the real one. Weekend classes cut into family time. Assignments pile up when work gets busy. Two years is long when you're juggling a job.</p>

<h2>How It Compares to Other Options</h2>

<p>I looked at Manipal, NMIMS, and Symbiosis online MBAs too.</p>

<p>Amity is cheaper than NMIMS and Symbiosis. It's similar to Manipal in fees and structure. The brand recognition is comparable.</p>

<p>What made Amity stand out (barely): Slightly better learning portal based on reviews, and more flexibility in exam schedules. But honestly, the differences aren't huge.</p>

<h2>What Current Students and Alumni Say</h2>

<p>I found a few people on LinkedIn who'd done the program:</p>

<p><strong>The good:</strong> Flexible schedule worked well with jobs. Faculty responded to queries (eventually). Degree got accepted for promotions and job switches. Exams weren't too difficult if you studied.</p>

<p><strong>The complaints:</strong> Portal glitches sometimes. Some faculty clearly recorded lectures years ago and haven't updated them. Placement support is basically just resume tips and a job portal - nothing like campus placements. Peer interaction is minimal unless you actively reach out.</p>

<p>One person switched from HR operations to talent acquisition six months after finishing. Another got promoted to HRBP. But both had 4-5 years of experience already.</p>

<h2>The Admission Process (Easier Than You Think)</h2>

<p>There's no entrance exam for most applicants. You need:</p>
<ul>
<li>Bachelor's degree (50% minimum, 45% for reserved categories)</li>
<li>Application form and fees</li>
<li>Documents (mark sheets, ID proof)</li>
</ul>

<p>If you have a valid CAT/MAT/XAT score, it might help, but it's not mandatory. The admission is pretty straightforward - they want students.</p>

<h2>My Honest Take - Should You Do It?</h2>

<p>If you're working in HR and need an MBA to move up, yes. It's affordable, flexible, and recognized. The ROI makes sense if you're looking at a ₹3-5 lakh salary jump or a promotion within two years.</p>

<p>If you're early in your career or not working in HR yet, think harder. A regular MBA might give you better placement support and networking. Or consider getting work experience first, then doing online.</p>

<p>The program isn't going to transform your career by itself. It's a checkbox, a credential, and a knowledge upgrade. That's valuable, but know what you're buying.</p>

<h2>Final Checklist Before You Enroll</h2>

<p>Before paying the fees:</p>
<ul>
<li>Check current fee structure on their official website (not third-party sites)</li>
<li>Confirm UGC-DEB approval status</li>
<li>Talk to at least one alumnus (LinkedIn is your friend)</li>
<li>Make sure your employer will recognize the degree if you need it for promotion</li>
<li>Test your internet and laptop for video streaming</li>
<li>Realistically block out 10-15 hours weekly for two years</li>
</ul>

<p>If all that checks out and you need the degree for career growth, Amity's online MBA in HR is a reasonable choice. Not the best, not the worst, but solid enough to get you where you need to go.</p>
    `,
  }
]
