// lib/blog-quick-facts.ts
// Quick Facts data for blog posts — NOT auto-generated. Edit manually here.
// CMS sync never touches this file, so data survives every sync.

export const BLOG_QUICK_FACTS: Record<string, { label: string; value: string; green?: boolean }[]> = {
  'nmims-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Mode',              value: '100% Online' },
    { label: 'Semesters',         value: '4' },
    { label: 'Total Fee',         value: '₹1.96 Lakhs' },
    { label: 'Per Semester',      value: '₹55,000' },
    { label: 'Specialisations',   value: '5' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'AACSB Accredited',  value: 'Yes', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50%' },
  ],
  'symbiosis-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Total Fee',         value: '₹2.65 Lakhs' },
    { label: 'Per Semester',      value: '₹78,750' },
    { label: 'Specialisations',   value: '9' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'UGC-DEB Entitled',  value: 'Yes', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50%' },
  ],
  'amity-online-mba-review-2026': [
    { label: 'Duration',          value: '2 Years' },
    { label: 'Mode',              value: '100% Online' },
    { label: 'Indian Fee',        value: '₹2.07L (one-time) / ₹2.25L' },
    { label: 'Dual Spec Fee',     value: '₹2.99L' },
    { label: 'Intl Fee',          value: 'USD 5,000' },
    { label: 'Specialisations',   value: '19' },
    { label: 'NAAC Grade',        value: 'A+' },
    { label: 'QS Ranking',        value: 'Asia Top 10', green: true },
    { label: 'Entrance Exam',     value: 'None (40%+)', green: true },
    { label: 'Min. Marks',        value: '40%' },
  ],
  'ignou-online-mba-review-2026': [
    { label: 'Total Fee',         value: '₹66,000' },
    { label: 'Per Semester',      value: 'Confirmed by counsellor' },
    { label: 'Duration',          value: '2 to 4 Years' },
    { label: 'Mode',              value: 'Online (MBAOL)' },
    { label: 'Specialisations',   value: '5' },
    { label: 'NAAC Grade',        value: 'A++' },
    { label: 'NIRF Rank',         value: '#1 Open Univ' },
    { label: 'WES',               value: 'Recognised', green: true },
    { label: 'Entrance Exam',     value: 'None', green: true },
    { label: 'Min. Marks',        value: '50% (45% reserved)' },
  ],
  'nmims-vs-symbiosis-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'NAAC (Both)',       value: 'A++', green: true },
    { label: 'NMIMS Fee',         value: '₹1.96L (standard)' },
    { label: 'Symbiosis Fee',     value: '₹3.70L (₹3.15L after 2+ yrs exp concession)' },
    { label: 'NMIMS NIRF Mgt',    value: '#24' },
    { label: 'Symbiosis NIRF Mgt', value: '#11' },
    { label: 'NMIMS Specs',       value: '6' },
    { label: 'Symbiosis Specs',   value: '9' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'jain-vs-amity-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'JAIN NAAC',         value: 'A++', green: true },
    { label: 'Amity NAAC',        value: 'A+' },
    { label: 'JAIN Fee',          value: '₹1.96L (standard)' },
    { label: 'Amity Fee',         value: '₹2.25L (standard)' },
    { label: 'JAIN NIRF Mgt',     value: '#73' },
    { label: 'Amity NIRF Mgt',    value: '#49' },
    { label: 'Specs (Both)',      value: '19 each' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'do-employers-accept-online-mba-india-2026': [
    { label: 'Type',              value: 'Pillar Guide' },
    { label: 'Focus',             value: 'Resume + Interview' },
    { label: 'Cluster',           value: 'Employer Perception' },
    { label: 'Key Insight',       value: 'Mode fading as filter', green: true },
    { label: 'Top Sectors',       value: 'IT, BFSI, FMCG, Govt' },
    { label: 'Best With',         value: 'MBA + Certification' },
    { label: 'UGC-DEB Required',  value: 'Yes', green: true },
    { label: 'NAAC Matters',      value: 'A+ / A++ strongest' },
  ],
  'best-online-bca-colleges-india-2026': [
    { label: 'Type',              value: 'Pillar (BCA Hub)' },
    { label: 'Universities',      value: '14 Ranked' },
    { label: 'Fee Range',         value: '₹49.8K - ₹1.77L' },
    { label: 'Top Pick',          value: 'LPU (₹1.22L, A++)' },
    { label: 'Budget Pick',       value: 'KL Univ (₹79K, A++)' },
    { label: 'Floor Price',       value: 'IGNOU ₹49,800' },
    { label: 'Duration',          value: '3 Years' },
    { label: 'UGC-DEB Required',  value: 'Yes', green: true },
  ],
  'amity-vs-manipal-online-mba-2026': [
    { label: 'Type',              value: 'Comparison' },
    { label: 'Amity Fee',         value: '₹2.07L (one-time)' },
    { label: 'MUJ Fee',           value: '₹1.53L (one-time)' },
    { label: 'NAAC (Both)',       value: 'A+', green: true },
    { label: 'Amity NIRF Mgt',    value: '#49' },
    { label: 'MUJ NIRF Mgt',      value: '#81' },
    { label: 'Amity Specs',       value: '19' },
    { label: 'MUJ Specs',         value: '13' },
    { label: 'UGC-DEB (Both)',    value: 'Yes', green: true },
  ],
  'online-mba-business-analysts-india-2026': [
    { label: 'What the degree changes',                       value: 'Permission, not capability' },
    { label: 'Universities with a Business Analytics label',  value: '26 in our index' },
    { label: 'Maths needed for admission',                    value: 'No' },
    { label: 'What decides programme quality',                value: 'The semester-wise curriculum' },
  ],
  'online-mba-sales-professionals-india-2026': [
    { label: 'MBA labels that name sales',           value: '4 out of 171' },
    { label: 'Universities with a Marketing label',  value: '62' },
    { label: 'What you will actually buy',           value: 'An MBA in marketing' },
    { label: 'The paper to look for',                value: 'Sales and distribution management' },
  ],
  'online-mba-medical-representatives-pharma-2026': [
    { label: 'What a field promotion runs on',                       value: 'Your sales number' },
    { label: 'What the degree opens',                                value: 'Head office roles' },
    { label: 'Universities with a Pharmaceutical Management label',  value: '6 in our index' },
    { label: 'Do before you pay',                                    value: 'Read three head office postings' },
  ],
  'online-mba-hr-executives-india-2026': [
    { label: 'Universities with an HR Management label',  value: '77, the highest of any spec' },
    { label: 'HR Analytics labels in our index',          value: '1' },
    { label: 'The paper that must be there',              value: 'Indian labour law' },
    { label: 'What the degree cannot supply',             value: 'One number you changed' },
  ],
  'online-mba-civil-site-engineers-project-management-2026': [
    { label: 'Universities with a Project Management label',        value: '7 in our index' },
    { label: 'Project Management programmes with a NIRF Mgt rank',  value: 'None on record' },
    { label: 'The paper that matters most',                         value: 'Contracts and claims management' },
    { label: 'When a certification beats the degree',               value: 'Planning and project controls' },
  ],
  'online-mba-nurses-healthcare-professionals-india-2026': [
    { label: 'Is BSc Nursing eligible for an MBA',  value: "Yes, it is a bachelor's degree" },
    { label: 'The one to check in writing',         value: 'GNM diploma without post-basic BSc' },
    { label: 'Your real advantage',                 value: 'Ward experience nobody can teach' },
    { label: 'Watch on clinical institutions',      value: 'NIRF Medical rank is not Management' },
  ],
  'online-mba-chartered-accountants-india-2026': [
    { label: 'What the finance core gives a CA',   value: 'Mostly revision' },
    { label: 'What you are actually buying',       value: 'Marketing, operations, strategy' },
    { label: 'Universities with a Finance label',  value: '74, nearly all redundant for you' },
    { label: 'Ask in writing about ACCA labels',   value: 'Exactly which exemptions apply' },
  ],
  'online-mba-product-managers-india-2026': [
    { label: 'MBA labels naming Product Management',  value: '1 out of 171' },
    { label: 'What product hiring reads',             value: 'Shipped evidence, not transcripts' },
    { label: 'Most common route into product',        value: 'An internal move' },
    { label: 'Buy the degree when',                   value: 'Your band gates the grade' },
  ],
  'online-mba-bank-employees-promotion-2026': [
    { label: 'What governs your promotion',   value: 'Your bank policy circular' },
    { label: 'What governs degree validity',  value: 'UGC-DEB entitlement' },
    { label: 'Entitlement granted',           value: 'Per programme, per session' },
    { label: 'Banking-labelled online MBAs',  value: 'A short list, not a wide field' },
  ],
  'online-mba-bfsi-india-2026': [
    { label: 'BFSI stands for',            value: 'Banking, Financial Services, Insurance' },
    { label: 'Exact BFSI label found at',  value: 'One university in our dataset' },
    { label: 'Adjacent banking labels',    value: 'Two more universities' },
    { label: 'What decides the content',   value: 'The elective list, not the label' },
  ],
  'mba-vs-jaiib-caiib-bank-officers-2026': [
    { label: 'JAIIB and CAIIB issued by',    value: 'IIBF, a professional body' },
    { label: 'MBA issued by',                value: 'A UGC-recognised university' },
    { label: 'Certification recognised by',  value: 'The banking sector' },
    { label: 'Degree recognised by',         value: 'Employers and universities generally' },
  ],
  'online-mba-banking-insurance-vs-finance-vs-bfsi-2026': [
    { label: 'Labels compared',     value: 'Three, plus FinTech' },
    { label: 'What differs most',   value: 'The elective list' },
    { label: 'What differs least',  value: 'The general management core' },
    { label: 'Document to demand',  value: 'Semester-wise curriculum' },
  ],
  'online-mba-it-professionals-india-2026': [
    { label: 'What promotes you in IT services',  value: 'Band and role criteria' },
    { label: 'Where the degree bites',            value: 'Lane changes, not level changes' },
    { label: 'Biggest avoidable mistake',         value: 'Ignoring mode in verification' },
    { label: 'Entitlement granted',               value: 'Per programme, per session' },
  ],
  'mba-tech-lead-to-engineering-manager-india-2026': [
    { label: 'What the jump is evidenced by',  value: 'Scope, not credentials' },
    { label: 'What an MBA supplies',           value: 'Commercial and people vocabulary' },
    { label: 'What it does not supply',        value: 'The scope itself' },
    { label: 'Best timing',                    value: 'Alongside scope, not instead of it' },
  ],
  'online-mba-information-technology-management-india-2026': [
    { label: 'Common labels',    value: 'IT Management, Systems' },
    { label: 'Degree type',      value: 'Management, not technical' },
    { label: 'Who it suits',     value: 'Delivery and technology leadership' },
    { label: 'Who it does not',  value: 'Engineers wanting technical depth' },
  ],
  'online-mba-vs-ms-vs-executive-pgp-software-engineers-2026': [
    { label: 'MBA',           value: 'UGC degree, management track' },
    { label: 'MS or M.Tech',  value: 'UGC degree, technical track' },
    { label: 'PGP or PGDM',   value: 'Often a diploma, not a degree' },
    { label: 'Check first',   value: 'Degree or diploma status' },
  ],
  'online-mba-artificial-intelligence-india-2026': [
    { label: 'Plain AI label found at',       value: 'One university in our dataset' },
    { label: 'Combined Data Science and AI',  value: 'Three universities' },
    { label: 'What it is',                    value: 'A management degree' },
    { label: 'What it is not',                value: 'An engineering degree' },
  ],
  'mba-ai-vs-mca-ai-vs-mtech-ai-india-2026': [
    { label: 'MBA in AI',         value: "Management roles, any bachelor's" },
    { label: 'MCA in AI',         value: 'Software roles, computing background' },
    { label: 'M.Tech in AI',      value: 'Engineering roles, BE or B.Tech' },
    { label: 'Decides it first',  value: 'Your eligibility, not your preference' },
  ],
  'mba-data-science-vs-business-analytics-2026': [
    { label: 'Business Analytics offered by',  value: 'Eight universities in our dataset' },
    { label: 'Data Science offered by',        value: 'A smaller group' },
    { label: 'Business Analytics points at',   value: 'Decisions' },
    { label: 'Data Science points at',         value: 'Models and methods' },
  ],
  'online-mba-ai-eligibility-maths-coding-2026': [
    { label: 'Admission maths requirement',   value: 'Usually none' },
    { label: 'Admission coding requirement',  value: 'Usually none' },
    { label: 'Coursework assumes',            value: 'Spreadsheet and chart literacy' },
    { label: 'Real barrier',                  value: 'No exposure to organisational data' },
  ],
}

