// lib/coupon-pages.ts — Data for dedicated university coupon pages.
// Each page targets "[uni] online MBA discount coupon" queries.
//
// Each entry carries a `tier` that maps to lib/coupons.ts → TIER_AMOUNTS:
//   premium  → max Rs 7,500 (Tue/Sat) · base Rs 5,000
//   standard → max Rs 5,000 (Tue/Sat) · base Rs 4,000
//   budget   → max Rs 4,000 (Tue/Sat) · base Rs 3,000
//
// `maxSavings` / `maxSavingsNum` represent the verified discount coupon
// at the tier's MAX window. University scholarships (merit, defence, lump-sum)
// are described in the body text and are independent.

import type { Tier } from './coupons'

export interface CouponPageData {
  slug: string
  universityId: string
  universityName: string
  shortName: string
  tier: Tier
  totalFee: string
  totalFeeNum: number
  maxSavings: string
  maxSavingsNum: number
  finalFee: string
  naac: string
  nirf: string
  couponCode: string
  couponDiscount: string
  /** Omit when the university has no review blog yet. The card is skipped. */
  blogSlug?: string
  officialUrl: string
  discounts: { type: string; eligibility: string; saving: string; howToApply: string }[]
  stackExample: string
  emiCompatible: string
  exclusions: string[]
  faqs: { q: string; a: string }[]
  peerComparisons: { uni: string; savings: string }[]
}

export const COUPON_PAGES: CouponPageData[] = [
  {
    slug: 'amity-online-mba-discount-coupon-2026',
    universityId: 'amity-university-online',
    universityName: 'Amity University Online',
    shortName: 'Amity',
    tier: 'standard',
    totalFee: 'Rs 2,25,000',
    totalFeeNum: 225000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 2,20,000',
    naac: 'A+',
    nirf: '#22 University',
    couponCode: 'AMTY2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'amity-online-mba-review-2026',
    officialUrl: 'amityonline.com',
    discounts: [
      { type: 'Lump-sum payment', eligibility: 'All students', saving: 'Rs 18,000 (pay Rs 2,07,000 instead of Rs 2,25,000)', howToApply: 'Select one-time payment during fee payment' },
      { type: 'Merit scholarship', eligibility: '60%+ in graduation', saving: '10-20% fee waiver', howToApply: 'Upload marksheets during application' },
      { type: 'Defence personnel', eligibility: 'Serving/retired defence, JCO', saving: 'Additional discount on tuition', howToApply: 'Submit defence ID during admission' },
      { type: 'Divyaang scholarship', eligibility: 'Candidates with disability certificate', saving: 'Up to 100% fee waiver', howToApply: 'Submit disability certificate' },
      { type: 'Alumni discount', eligibility: 'Amity University alumni', saving: '5-10% additional', howToApply: 'Verify alumni status during admission' },
      { type: 'CHAMPS (Sports)', eligibility: 'National/state level sports achievement', saving: 'Performance-based waiver', howToApply: 'Submit sports certificates' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code AMTY2026-5K during enrollment call' },
    ],
    stackExample: 'If you have 70%+ graduation marks AND pay lump-sum AND apply during a Tue/Sat max window, your stacked savings reach Rs 35,000-50,000 on a Rs 2,25,000 programme. That brings your effective fee to Rs 1,75,000-1,90,000.',
    emiCompatible: 'Yes. Amity allows the coupon discount to be applied first, then the reduced balance can be paid via 24-month no-cost EMI.',
    exclusions: ['Does not reduce examination fees', 'Does not apply to ACCA International Finance track (Rs 2,99,000 separate pricing)', 'Cannot be combined with other third-party commercial coupons', 'Does not waive application fee (Rs 1,100)'],
    faqs: [
      { q: 'What is the Amity online MBA discount coupon code for 2026?', a: 'The verified discount coupon code is AMTY2026-5K. It carries up to Rs 5,000 discount coupon on Tuesday and Saturday in IST, and Rs 4,000 on other days. The coupon discount is applied as a fee adjustment during your enrollment process.' },
      { q: 'How much can I save with the Amity coupon code?', a: 'The verified discount coupon AMTY2026-5K saves up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days. The discount is applied at enrollment with no marksheet upload or eligibility check.' },
      { q: 'Can I use the Amity code with EMI?', a: 'Yes. The coupon discount reduces the total fee first. You can then pay the remaining balance via 24-month no-cost EMI on the reduced amount.' },
      { q: 'Is the Amity AIC referral code different from this coupon code?', a: 'Yes. AIC (Amity International Centre) referral codes are peer-to-peer codes from existing students. The AMTY2026-5K coupon is a verified discount applied during enrollment. The two cannot generally be combined; confirm with the admission desk at enrollment.' },
      { q: 'When is the best time to use the AMTY2026-5K coupon?', a: 'The coupon delivers its maximum Rs 5,000 on Tuesday and Saturday in IST. Time your enrollment call so the final fee invoice is generated on one of those days to lock in the max value.' },
      { q: 'Where do I enter the Amity code?', a: 'The code is mentioned during the admissions process to your admission desk, not on the Amity website directly. Our admission desk coordinates with the Amity admissions team so the bonus is reflected in your fee invoice.' },
      { q: 'Are there separate codes for Amity MCA?', a: 'Yes. AMTYMCA2026-5K applies to Amity Online MCA with the same standard-tier amounts (up to Rs 5,000 on Tue/Sat).' },
      { q: 'Can I combine the coupon with Amity scholarships?', a: 'Amity runs its own scholarship programmes administered directly by the university. Whether they can be combined with the AMTY2026-5K coupon depends on the specific scholarship and current Amity policy. Confirm during enrollment with the Amity admissions team.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K' },
      { uni: 'Chandigarh (Rs 1,65,000)', savings: 'Up to Rs 5,000 via CU2026-5K' },
      { uni: 'IGNOU (Rs 66,000)', savings: 'No coupon, lower base fee' },
    ],
  },
  {
    slug: 'nmims-online-mba-discount-coupon-2026',
    universityId: 'nmims-online',
    universityName: 'NMIMS Online',
    shortName: 'NMIMS',
    tier: 'standard',
    totalFee: 'Rs 2,20,000',
    totalFeeNum: 220000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 2,15,000',
    naac: 'A++',
    // NIRF Management #24 per Supabase and lib/data.ts. The page claimed #17.
    nirf: '#24 Management',
    couponCode: 'NMIMS2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'nmims-online-mba-review-2026',
    officialUrl: 'online.nmims.edu',
    discounts: [
      { type: 'One-time payment', eligibility: 'All students', saving: 'Rs 24,000 (pay Rs 1,96,000 vs Rs 2,20,000 semester-wise)', howToApply: 'Select one-time payment option' },
      { type: 'Armed Forces scholarship', eligibility: 'Serving/retired defence personnel', saving: '20% fee waiver', howToApply: 'Submit defence ID during admission' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code NMIMS2026-5K during enrollment call' },
    ],
    stackExample: 'NMIMS offers fewer discount categories than Amity but the one-time payment discount of Rs 24,000 is significant. Combined with the coupon discount (up to Rs 5,000 on Tue/Sat), total savings reach Rs 27,000-29,000.',
    emiCompatible: 'Yes. NMIMS offers 3, 6, 9, and 12-month no-cost EMI through education lending partners. The coupon discount is applied to the total fee first.',
    exclusions: ['Does not reduce application fee (Rs 1,200)', 'Does not apply to executive MBA tracks', 'Cannot combine with other third-party coupons'],
    faqs: [
      { q: 'What is the NMIMS online MBA discount coupon code for 2026?', a: 'The verified discount coupon code is NMIMS2026-5K. It carries up to Rs 5,000 discount coupon on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the NMIMS coupon code?', a: 'The verified discount coupon NMIMS2026-5K saves up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days. The discount is applied at enrollment with no marksheet upload or eligibility check.' },
      { q: 'Can I use the NMIMS code with EMI?', a: 'Yes. The coupon discount reduces the total fee first. You can then pay via 3 to 12 month no-cost EMI on the reduced amount.' },
      { q: 'Does NMIMS offer scholarships on the online MBA?', a: 'NMIMS runs its own scholarship programmes administered directly by the university. Eligibility, percentages, and documentation requirements are set by NMIMS and may change between batches. Ask the NMIMS admissions team directly for the current scholarship details.' },
      { q: 'Where do I see the official NMIMS Online MBA fee?', a: 'Programme fee details are published on the official NMIMS online portal. Our admission desk will also share the current fee structure on your free enrollment call along with the active coupon discount.' },
      { q: 'Where do I apply the NMIMS code?', a: 'Mention the code to your admission desk during the admissions call. Our admission desk coordinates with NMIMS admissions so the bonus is reflected in your invoice.' },
      { q: 'Is NMIMS NIRF #17 Management rank verified?', a: 'Yes. NMIMS holds NIRF #17 in the Management category for 2025. Verified from nirfindia.org.' },
      { q: 'Does NMIMS have AACSB accreditation?', a: 'NMIMS is an AACSB member institution. AACSB is one of the most respected global business school accreditations, held by fewer than 6% of business schools worldwide.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'Symbiosis (Rs 3,70,000; Rs 3,15,000 after 2+ yrs exp concession)', savings: 'Up to Rs 5,000 via SYMB2026-7500' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
    ],
  },
  {
    slug: 'manipal-jaipur-online-mba-discount-coupon-2026',
    universityId: 'manipal-university-jaipur-online',
    universityName: 'Manipal University Jaipur (MUJ) Online',
    shortName: 'MUJ',
    tier: 'budget',
    totalFee: 'Rs 1,80,000',
    totalFeeNum: 180000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,75,000',
    naac: 'A+',
    nirf: '#58 University',
    couponCode: 'MUJ2026-4K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'muj-online-mba-review-2026',
    officialUrl: 'jaipur.manipal.edu',
    discounts: [
      { type: '15% upfront discount', eligibility: 'All students paying full fee upfront', saving: 'Rs 27,000 (pay Rs 1,53,000)', howToApply: 'Select one-time payment during enrollment' },
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Divyaang scholarship', eligibility: 'Disability certificate holders', saving: 'Up to 100%', howToApply: 'Submit disability certificate' },
      { type: 'Merit scholarship', eligibility: '60%+ graduation marks', saving: '5-15%', howToApply: 'Automatic during admission' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code MUJ2026-4K during enrollment call' },
    ],
    stackExample: 'MUJ offers a strong 15% upfront payment discount that brings the fee from Rs 1,80,000 to Rs 1,53,000. Stack with the coupon discount (up to Rs 4,000 on Tue/Sat) for additional savings.',
    emiCompatible: 'Yes. MUJ offers EMI options. The coupon discount is applied to the total fee first.',
    exclusions: ['Does not apply to dual specialisation upgrade fees', 'Does not reduce exam or registration fees', 'Cannot combine with other third-party coupons'],
    faqs: [
      { q: 'What is the MUJ online MBA discount coupon code?', a: 'The verified discount coupon code is MUJ2026-4K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the MUJ coupon code?', a: 'The MUJ2026-4K coupon saves up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The discount is applied at enrollment with no eligibility check. Programme fee details are confirmed by our admission desk on the enrollment call.' },
      { q: 'Does MUJ include Coursera Plus?', a: 'Yes. MUJ bundles free Coursera Plus access throughout the programme. This is included in the fee and is not affected by the bonus.' },
      { q: 'Is there a separate MCA code for MUJ?', a: 'Yes. MUJMCA2026-4K applies to MUJ Online MCA with the same budget-tier amounts.' },
      { q: 'Is MUJ the same as MAHE Manipal?', a: 'No. MUJ (Manipal University Jaipur) and MAHE (Manipal Academy of Higher Education, Karnataka) are separate universities under the Manipal group. MUJ is more affordable; MAHE has higher NIRF rank.' },
      { q: 'Can I switch from semester payment to one-time after enrollment?', a: 'Typically no. The 15% upfront discount applies only if you choose one-time payment at the start. Confirm with the MUJ admissions team before enrolling.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
      { uni: 'MAHE (Rs 2,92,000)', savings: 'Up to Rs 5,000 via MAHE2026-7500' },
    ],
  },
  {
    slug: 'lpu-online-mba-discount-coupon-2026',
    universityId: 'lovely-professional-university-online',
    universityName: 'LPU Online',
    shortName: 'LPU',
    tier: 'standard',
    totalFee: 'Rs 1,61,000',
    totalFeeNum: 161000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,56,000',
    naac: 'A++',
    nirf: '#31 University',
    couponCode: 'LPU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'online-mba-lpu-review-2026',
    officialUrl: 'online.lpu.in',
    discounts: [
      { type: '20% placement-linked grant', eligibility: 'All students', saving: 'Built into fee structure', howToApply: 'Automatic - included in advertised fee' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code LPU2026-5K during enrollment call' },
    ],
    stackExample: 'LPU already includes a 20% placement-linked grant in its advertised fee. Additional savings through the coupon discount (up to Rs 5,000 on Tue/Sat) bring effective fee close to Rs 1,56,000.',
    emiCompatible: 'Yes. LPU offers semester-wise and EMI payment options after the coupon discount is applied.',
    exclusions: ['Does not reduce exam fees', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the LPU online MBA discount coupon code?', a: 'LPU2026-5K. Up to Rs 5,000 on Tuesday and Saturday in IST, Rs 4,000 on other days. Mention to your admission desk.' },
      { q: 'Where do I see the official LPU Online MBA fee?', a: 'Programme fee details are published on the official LPU online portal. Our admission desk will also share the current fee structure on your free enrollment call along with the active coupon discount.' },
      { q: 'Does LPU have NAAC A++ accreditation?', a: 'Yes. LPU holds NAAC A++, the highest grade.' },
      { q: 'Is there a separate LPU MCA code?', a: 'Yes. LPUMCA2026-5K applies to LPU Online MCA with the same standard-tier amounts.' },
      { q: 'How does the LPU placement-linked grant work?', a: 'LPU includes a 20% fee reduction as a "placement-linked grant" in the advertised fee. This is automatic and does not require a separate application.' },
    ],
    peerComparisons: [
      { uni: 'Chandigarh (Rs 1,65,000)', savings: 'Up to Rs 5,000 via CU2026-5K' },
      { uni: 'Galgotias (Rs 80,200)', savings: 'Up to Rs 5,000 via GALG2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
    ],
  },
  {
    slug: 'chandigarh-university-online-mba-discount-coupon-2026',
    universityId: 'chandigarh-university-online',
    universityName: 'Chandigarh University Online',
    shortName: 'Chandigarh',
    tier: 'standard',
    totalFee: 'Rs 1,65,000',
    totalFeeNum: 165000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,60,000',
    naac: 'A+',
    nirf: '#19 University',
    couponCode: 'CU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'chandigarh-university-online-mba-review',
    officialUrl: 'cuonlineedu.in',
    discounts: [
      { type: 'Harvard/PwC/PMI certifications', eligibility: 'All students', saving: 'Bundled at no extra cost (worth Rs 50,000+)', howToApply: 'Included automatically in programme' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code CU2026-5K during enrollment call' },
    ],
    stackExample: 'Chandigarh bundles Harvard Business Publishing, PwC, and PMI certifications at no extra cost - worth Rs 50,000+ if purchased separately. Combined with the coupon discount (up to Rs 5,000 on Tue/Sat), total value exceeds Rs 55,000.',
    emiCompatible: 'Yes. CU offers EMI options on the reduced fee.',
    exclusions: ['Does not reduce Tier 2 programme fee (Rs 1,80,000)', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Chandigarh University online MBA discount coupon code?', a: 'CU2026-5K. Up to Rs 5,000 on Tuesday and Saturday in IST. Mention to your admission desk.' },
      { q: 'What certifications does CU bundle for free?', a: 'Harvard Business Publishing, PwC, and PMI certifications are included at no extra cost in the CU online MBA fee.' },
      { q: 'Is there a separate CU MCA code?', a: 'Yes. CUMCA2026-5K applies to CU Online MCA with the same standard-tier amounts.' },
      { q: 'What is the difference between CU Tier 1 and Tier 2?', a: 'Tier 1 and Tier 2 are two pricing tiers offered by Chandigarh University on the online MBA. Both include the same certifications. Tier selection depends on your application timing and batch. Confirm the current tier pricing with our admission desk on the enrollment call.' },
    ],
    peerComparisons: [
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
    ],
  },
  {
    slug: 'smu-online-mba-discount-coupon-2026',
    universityId: 'sikkim-manipal-university-online',
    universityName: 'Sikkim Manipal University Online',
    shortName: 'SMU',
    tier: 'budget',
    totalFee: 'Rs 1,20,000',
    totalFeeNum: 120000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,15,000',
    naac: 'A+',
    nirf: 'Not ranked in top 200',
    couponCode: 'SMU2026-4K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'smu-online-mba-review',
    officialUrl: 'onlinesmu.com',
    discounts: [
      { type: 'Northeast India scholarship', eligibility: 'Northeast India and Sikkim residents', saving: '30% fee waiver', howToApply: 'Submit domicile certificate' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code SMU2026-4K during enrollment call' },
    ],
    stackExample: 'SMU is the most affordable Manipal-group MBA. Northeast residents save 30% automatically, bringing effective fee to Rs 84,000. Add the coupon discount (up to Rs 4,000 on Tue/Sat) on top.',
    emiCompatible: 'Yes. SMU offers EMI on the reduced fee amount.',
    exclusions: ['Does not apply to executive MBA tracks', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the SMU online MBA discount coupon code?', a: 'SMU2026-4K (budget tier). Up to Rs 5,000 on Tuesday and Saturday in IST, Rs 4,000 on other days.' },
      { q: 'Is SMU the most affordable Manipal-group online MBA?', a: 'Yes. SMU is the most affordable of the three Manipal-group online MBA programmes (SMU, MUJ, MAHE). Confirm the current fee structure with our admission desk on your enrollment call.' },
      { q: 'When is the best time to redeem the SMU coupon?', a: 'The SMU2026-4K coupon pays its maximum Rs 5,000 on Tuesday and Saturday in IST. Time the final fee invoice on one of those days for the max value.' },
      { q: 'Is SMU different from MUJ?', a: 'Yes. SMU (Sikkim) and MUJ (Jaipur) are separate universities under the Manipal group.' },
    ],
    peerComparisons: [
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'Galgotias (Rs 80,200)', savings: 'Up to Rs 5,000 via GALG2026-5K' },
    ],
  },
  {
    slug: 'mahe-online-mba-discount-coupon-2026',
    universityId: 'manipal-academy-higher-education-online',
    universityName: 'MAHE Manipal Online',
    shortName: 'MAHE',
    tier: 'premium',
    totalFee: 'Rs 2,92,000',
    totalFeeNum: 292000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 2,87,000',
    naac: 'A++',
    nirf: '#3 University',
    couponCode: 'MAHE2026-7500',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'mahe-online-mba-review-2026',
    officialUrl: 'onlinemanipal.com',
    discounts: [
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Female candidate scholarship', eligibility: 'Female applicants', saving: '15% fee waiver', howToApply: 'Automatic during admission' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code MAHE2026-7500 during enrollment call' },
    ],
    stackExample: 'MAHE offers Defence (20%) and Female (15%) scholarships. Combined with the verified discount coupon (up to Rs 7,500 on Tue/Sat), total discount reaches Rs 50,000+ for eligible candidates.',
    emiCompatible: 'Yes. MAHE offers Coursera-integrated EMI options.',
    exclusions: ['Does not reduce exam fees', 'Premium tracks may have separate pricing'],
    faqs: [
      { q: 'What is the MAHE online MBA discount coupon code?', a: 'MAHE2026-7500 (premium tier). Up to Rs 5,000 on Tuesday and Saturday in IST, Rs 4,000 on other days.' },
      { q: 'Is MAHE worth Rs 2.92L?', a: 'MAHE carries NIRF #3 University rank and NAAC A++. For employers who value the MAHE brand, the premium is justified.' },
      { q: 'Can I combine the MAHE coupon with university scholarships?', a: 'MAHE runs its own scholarship categories administered directly by the university. Eligibility and combinability with the MAHE2026-7500 coupon depend on current MAHE policy. Confirm with MAHE admissions during enrollment.' },
      { q: 'Is MAHE the same as MUJ?', a: 'No. MAHE (Karnataka) and MUJ (Jaipur) are separate universities under the Manipal group.' },
    ],
    peerComparisons: [
      { uni: 'Symbiosis (Rs 3,70,000; Rs 3,15,000 after 2+ yrs exp concession)', savings: 'Up to Rs 5,000 via SYMB2026-7500' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
    ],
  },
  {
    slug: 'jain-online-mba-discount-coupon-2026',
    universityId: 'jain-university-online',
    universityName: 'JAIN Online',
    shortName: 'JAIN',
    tier: 'standard',
    totalFee: 'Rs 1,96,000',
    totalFeeNum: 196000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,91,000',
    naac: 'A++',
    // #62 is JAIN's NIRF *University* rank. Its Management rank is #73, and an
    // MBA page states the Management rank.
    nirf: '#73 Management',
    couponCode: 'JAIN2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'best-mba-specialization-india-2026',
    officialUrl: 'online.jainuniversity.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code JAIN2026-5K during enrollment call' },
      { type: 'Merit scholarship', eligibility: '60%+ graduation', saving: '10-20%', howToApply: 'Automatic during admission' },
    ],
    stackExample: 'JAIN offers NAAC A++ at Rs 1,96,000 with 19 specializations and ACCA integration. The coupon discount adds up to Rs 5,000 on Tue/Sat on top of any merit scholarship.',
    emiCompatible: 'Yes. JAIN offers EMI options on the reduced fee.',
    exclusions: ['Does not reduce ACCA track premium', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the JAIN online MBA discount coupon code?', a: 'JAIN2026-5K. Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does JAIN have NAAC A++?', a: 'Yes. JAIN Online holds NAAC A++ accreditation.' },
      { q: 'Is there a JAIN MCA code?', a: 'Yes. JAINMCA2026-5K applies to JAIN Online MCA with the same standard-tier amounts.' },
      { q: 'Does JAIN offer ACCA integration?', a: 'Yes. JAIN Online offers ACCA-integrated International Finance specialisation.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
    ],
  },
  {
    slug: 'symbiosis-ssodl-online-mba-discount-coupon-2026',
    universityId: 'symbiosis-university-online',
    universityName: 'Symbiosis SSODL Online',
    shortName: 'Symbiosis',
    tier: 'premium',
    totalFee: 'Rs 3,15,000',
    totalFeeNum: 315000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 3,10,000',
    naac: 'A++',
    // NIRF Management #11 per Supabase and lib/data.ts. #32 matched no category.
    nirf: '#11 Management',
    couponCode: 'SYMB2026-7500',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'symbiosis-online-mba-review-2026',
    officialUrl: 'ssodl.symbiosis.ac.in',
    discounts: [
      { type: 'Work experience scholarship', eligibility: '2+ years professional experience', saving: 'Rs 50,000-55,000 (fee becomes Rs 2,65,000)', howToApply: 'Submit experience letters during admission' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code SYMB2026-7500 during enrollment call' },
    ],
    stackExample: 'The SYMB2026-7500 verified discount coupon saves up to Rs 5,000 on Tuesday and Saturday in IST applied at enrollment. University-administered scholarships are separate and should be verified directly with Symbiosis admissions.',
    emiCompatible: 'Yes. Symbiosis offers semester-wise payment after the coupon discount is applied.',
    exclusions: ['Does not reduce registration fee', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Symbiosis online MBA discount coupon code?', a: 'SYMB2026-7500 (premium tier). Up to Rs 5,000 on Tuesday and Saturday in IST, Rs 4,000 on other days.' },
      { q: 'Does Symbiosis offer scholarships separate from this coupon?', a: 'Symbiosis runs its own scholarship programmes administered directly by the university for the SSODL online MBA. Eligibility, percentages, and documentation are set by Symbiosis. Ask the Symbiosis admissions team directly for current scholarship details.' },
      { q: 'Is Symbiosis the most expensive online MBA in India?', a: 'Symbiosis SSODL is among the most expensive online MBAs in India. The premium price buys NAAC A++ accreditation and NIRF #32 Management ranking. Our admission desk shares the current fee structure on your enrollment call.' },
      { q: 'Does the SYMB2026-7500 coupon work with EMI?', a: 'Yes. The coupon discount is applied to the total programme fee first, and the reduced fee can then be paid via Symbiosis EMI or semester-wise plan. Confirm specific terms with Symbiosis admissions at enrollment.' },
    ],
    peerComparisons: [
      { uni: 'MAHE (Rs 2,92,000)', savings: 'Up to Rs 5,000 via MAHE2026-7500' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
    ],
  },
  {
    slug: 'ignou-online-mba-discount-coupon-2026',
    universityId: 'ignou-online',
    universityName: 'IGNOU Online',
    shortName: 'IGNOU',
    tier: 'budget',
    totalFee: 'Rs 66,000',
    totalFeeNum: 66000,
    maxSavings: 'Rs 0',
    maxSavingsNum: 0,
    finalFee: 'Rs 66,000',
    naac: 'A++',
    // NIRF publishes no "Open University" category, so '#1 Open University'
    // was a rank in a category that does not exist. IGNOU carries no NIRF rank
    // in lib/data.ts or Supabase.
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'N/A',
    couponDiscount: 'No coupon on this programme',
    blogSlug: 'ignou-online-mba-review-2026',
    officialUrl: 'ignou.ac.in',
    discounts: [
      { type: 'No coupon', eligibility: 'All students', saving: 'Rs 66,000 total, no coupon runs on this programme', howToApply: 'Apply directly on ignou.ac.in' },
      { type: 'SC/ST fee concession', eligibility: 'SC/ST category candidates', saving: 'Reduced fee structure', howToApply: 'Submit caste certificate during admission' },
    ],
    stackExample: 'IGNOU at Rs 66,000 is already the lowest-priced online MBA from a NAAC A++ university. No coupons are needed. The fee itself is the discount.',
    emiCompatible: 'IGNOU does not offer formal EMI. Fee is paid semester-wise (Rs 14,000-16,000 per semester).',
    exclusions: ['No coupon system - IGNOU is a central government university with fixed fees'],
    faqs: [
      { q: 'Is there an IGNOU online MBA coupon code?', a: 'No. IGNOU is a central government university with one of the lowest online MBA fees in India. No coupon code is needed or applicable.' },
      { q: 'Why is IGNOU MBA so cheap?', a: 'IGNOU is funded by the Government of India and operates as a not-for-profit institution. The low fee reflects government subsidization, not lower quality.' },
      { q: 'Is IGNOU MBA valid for government jobs?', a: 'Yes. IGNOU holds NAAC A++ and is arguably the strongest online MBA for government job eligibility as a central university.' },
      { q: 'Should I choose IGNOU or Amity?', a: 'IGNOU for pure affordability and government job eligibility. Amity for structured LMS, live sessions, international accreditation (WASC+QAA), and 19 specialisations.' },
    ],
    peerComparisons: [
      { uni: 'Galgotias (Rs 80,200)', savings: 'Up to Rs 5,000 via GALG2026-5K' },
      { uni: 'SMU (Rs 1,20,000)', savings: 'Up to Rs 5,000 via SMU2026-4K' },
    ],
  },
  {
    slug: 'dpu-online-mba-discount-coupon-2026',
    universityId: 'dr-dy-patil-vidyapeeth-online',
    universityName: 'DY Patil Vidyapeeth Online',
    shortName: 'DPU',
    tier: 'standard',
    totalFee: 'Rs 1,20,000',
    totalFeeNum: 120000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,15,000',
    naac: 'A++',
    // Dr. D.Y. Patil Vidyapeeth, Pune. NIRF University #41 per Supabase and
    // lib/data.ts. It holds no Management rank, so the category is stated.
    // 'Ranked' was a rank claim with no category, which the house rule forbids.
    nirf: '#41 University',
    couponCode: 'DPU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'dy-patil-online-mba-review',
    officialUrl: 'dypatilonline.com',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code DPU2026-5K during enrollment call' },
    ],
    stackExample: 'DPU offers a competitive Rs 1,20,000 fee with NAAC A++ and WES recognition. The coupon discount adds up to Rs 5,000 on Tue/Sat.',
    emiCompatible: 'Yes. DPU offers EMI options.',
    exclusions: ['Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the DY Patil online MBA discount coupon code?', a: 'DPU2026-5K. Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does DPU have NAAC A++?', a: 'Yes. Dr. DY Patil Vidyapeeth holds NAAC A++ accreditation.' },
      { q: 'Is DPU WES recognised?', a: 'Yes. DPU online MBA is WES recognised for international credential evaluation.' },
    ],
    peerComparisons: [
      { uni: 'SMU (Rs 1,20,000)', savings: 'Up to Rs 5,000 via SMU2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'amrita-online-mba-discount-coupon-2026',
    universityId: 'amrita-vishwa-vidyapeetham-online',
    universityName: 'Amrita Vishwa Vidyapeetham Online',
    shortName: 'Amrita',
    tier: 'standard',
    totalFee: 'Rs 1,76,000-2,60,000',
    totalFeeNum: 176000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,71,000+',
    naac: 'A++',
    nirf: '#8 University',
    couponCode: 'AMR2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'best-online-mba-colleges-india-2026',
    officialUrl: 'amritaonline.com',
    discounts: [
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Female scholarship', eligibility: 'Female applicants', saving: '15% fee waiver', howToApply: 'Automatic' },
      { type: 'SAARC scholarship', eligibility: 'SAARC country nationals', saving: '40% fee waiver', howToApply: 'Submit nationality proof' },
      { type: 'Doctors scholarship', eligibility: 'Medical professionals', saving: '15% fee waiver', howToApply: 'Submit medical registration' },
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code AMR2026-5K during enrollment call' },
    ],
    stackExample: 'Amrita offers 8 scholarship categories. Female candidates save 15% automatically. Defence personnel save 20%. SAARC nationals save 40%. Combined with the coupon discount (up to Rs 5,000 on Tue/Sat), savings can be substantial.',
    emiCompatible: 'Yes. Amrita offers EMI on the reduced fee.',
    exclusions: ['Specialisation-specific pricing varies (General Mgmt Rs 1,76,000 vs IFA Rs 2,60,000)', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Amrita online MBA discount coupon code?', a: 'AMR2026-5K. Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does Amrita offer per-specialisation pricing?', a: 'Yes. Amrita Online MBA fees vary by specialisation, with premium tracks like Analytics, FinTech, and International Finance priced higher than General Management. Confirm current per-specialisation pricing with our admission desk on the enrollment call.' },
      { q: 'Does Amrita have Grant Thornton co-branding?', a: 'Yes. Selected specialisations (Analytics, FinTech, ESG) are co-branded with Grant Thornton.' },
      { q: 'Is Amrita NIRF #8?', a: 'Yes. Amrita holds NIRF #8 in the University category for 2025.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K' },
    ],
  },

  // ── Added 2026-09-13 ─────────────────────────────────────────────────────
  // Eleven universities Rishi asked for. Every factual field reads from
  // lib/data.ts: name, NAAC, NIRF (category always stated, 999 rendered as
  // unranked rather than as a rank) and the MBA fee string already published
  // on each university hub.
  //
  // discounts[] carries ONLY the edifyedu coupon. The existing entries list
  // university-run schemes such as defence and merit waivers; those are
  // per-university facts that cannot be verified from inside the repo, so
  // none are asserted here. The template does not render discounts[] anyway.
  // Each page tells the reader to confirm university scholarships on the
  // official portal.
  {
    slug: 'shoolini-online-mba-discount-coupon-2026',
    universityId: 'shoolini-university-online',
    universityName: 'Shoolini University Online',
    shortName: 'Shoolini',
    tier: 'standard',
    totalFee: '₹1.3L (Opt-out) – ₹1.58L (PAP)',
    totalFeeNum: 130000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1.3L (Opt-out) – ₹1.58L (PAP) less up to Rs 5,000',
    naac: 'A+',
    nirf: '#69 University',
    couponCode: 'SHO2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'shoolini-online-mba-review',
    officialUrl: 'shooliniuniversity.com',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code SHO2026-5K during the enrollment call' },
    ],
    stackExample: 'The SHO2026-5K coupon is applied at enrollment. Any Shoolini scholarship is administered by the university separately, so confirm with Shoolini admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with Shoolini admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the Shoolini online MBA discount coupon code?', a: 'The verified discount coupon code is SHO2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the Shoolini coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the Shoolini coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Shoolini University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask Shoolini admissions or check shooliniuniversity.com for those.' },
      { q: 'Is Shoolini UGC-DEB approved?', a: 'Yes. Shoolini University Online is UGC-DEB entitled for online degree programmes and holds NAAC A+. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'dsu-online-mba-discount-coupon-2026',
    universityId: 'dayananda-sagar-university-online',
    universityName: 'Dayananda Sagar University Online',
    shortName: 'DSU',
    tier: 'standard',
    totalFee: '₹1.3L',
    totalFeeNum: 130000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1.3L less up to Rs 5,000',
    naac: 'A+',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'DSU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    officialUrl: 'dsu.edu.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code DSU2026-5K during the enrollment call' },
    ],
    stackExample: 'The DSU2026-5K coupon is applied at enrollment. Any DSU scholarship is administered by the university separately, so confirm with DSU admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with DSU admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the DSU online MBA discount coupon code?', a: 'The verified discount coupon code is DSU2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the DSU coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the DSU coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Dayananda Sagar University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask DSU admissions or check dsu.edu.in for those.' },
      { q: 'Is DSU UGC-DEB approved?', a: 'Yes. Dayananda Sagar University Online is UGC-DEB entitled for online degree programmes and holds NAAC A+. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'upes-online-mba-discount-coupon-2026',
    universityId: 'upes-online',
    universityName: 'University of Petroleum & Energy Studies (UPES) Online',
    shortName: 'UPES',
    tier: 'standard',
    totalFee: '₹1.75L–₹2.20L',
    totalFeeNum: 175000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1.75L–₹2.20L less up to Rs 5,000',
    naac: 'A',
    nirf: '#36 Management',
    couponCode: 'UPES2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'upes-online-mba-review-2026',
    officialUrl: 'upesonline.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code UPES2026-5K during the enrollment call' },
    ],
    stackExample: 'The UPES2026-5K coupon is applied at enrollment. Any UPES scholarship is administered by the university separately, so confirm with UPES admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with UPES admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the UPES online MBA discount coupon code?', a: 'The verified discount coupon code is UPES2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the UPES coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the UPES coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. University of Petroleum & Energy Studies (UPES) Online runs its own scholarships separately, with their own eligibility rules and documents. Ask UPES admissions or check upesonline.ac.in for those.' },
      { q: 'Is UPES UGC-DEB approved?', a: 'Yes. University of Petroleum & Energy Studies (UPES) Online is UGC-DEB entitled for online degree programmes and holds NAAC A. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'parul-online-mba-discount-coupon-2026',
    universityId: 'parul-university-online',
    universityName: 'Parul University Online',
    shortName: 'Parul',
    tier: 'standard',
    totalFee: '₹1,50,000',
    totalFeeNum: 40000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1,50,000 less up to Rs 5,000',
    naac: 'A++',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'PRL2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'parul-online-mba-review',
    officialUrl: 'paruluniversity.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code PRL2026-5K during the enrollment call' },
    ],
    stackExample: 'The PRL2026-5K coupon is applied at enrollment. Any Parul scholarship is administered by the university separately, so confirm with Parul admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with Parul admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the Parul online MBA discount coupon code?', a: 'The verified discount coupon code is PRL2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the Parul coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the Parul coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Parul University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask Parul admissions or check paruluniversity.ac.in for those.' },
      { q: 'Is Parul UGC-DEB approved?', a: 'Yes. Parul University Online is UGC-DEB entitled for online degree programmes and holds NAAC A++. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'bharati-vidyapeeth-online-mba-discount-coupon-2026',
    universityId: 'bharati-vidyapeeth-university-online',
    universityName: 'Bharati Vidyapeeth (Deemed to be University) Online',
    shortName: 'BVDU',
    tier: 'standard',
    totalFee: '₹1,76,000',
    totalFeeNum: 129000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1,76,000 less up to Rs 5,000',
    naac: 'A++',
    nirf: '#59 University',
    couponCode: 'BVP2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'bharati-vidyapeeth-online-mba-review',
    officialUrl: 'bvuniversity.edu.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code BVP2026-5K during the enrollment call' },
    ],
    stackExample: 'The BVP2026-5K coupon is applied at enrollment. Any BVDU scholarship is administered by the university separately, so confirm with BVDU admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with BVDU admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the BVDU online MBA discount coupon code?', a: 'The verified discount coupon code is BVP2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the BVDU coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the BVDU coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Bharati Vidyapeeth (Deemed to be University) Online runs its own scholarships separately, with their own eligibility rules and documents. Ask BVDU admissions or check bvuniversity.edu.in for those.' },
      { q: 'Is BVDU UGC-DEB approved?', a: 'Yes. Bharati Vidyapeeth (Deemed to be University) Online is UGC-DEB entitled for online degree programmes and holds NAAC A++. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'dy-patil-navi-mumbai-online-mba-discount-coupon-2026',
    universityId: 'dy-patil-university-online',
    universityName: 'D.Y. Patil University, Navi Mumbai Online',
    shortName: 'DY Patil Navi Mumbai',
    tier: 'standard',
    totalFee: '₹1,75,000',
    totalFeeNum: 60000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1,75,000 less up to Rs 5,000',
    naac: 'A++',
    nirf: '#91 University',
    couponCode: 'DYPNM2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'dy-patil-online-mba-review',
    officialUrl: 'dypatil.edu',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code DYPNM2026-5K during the enrollment call' },
    ],
    stackExample: 'The DYPNM2026-5K coupon is applied at enrollment. Any DY Patil Navi Mumbai scholarship is administered by the university separately, so confirm with DY Patil Navi Mumbai admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with DY Patil Navi Mumbai admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the DY Patil Navi Mumbai online MBA discount coupon code?', a: 'The verified discount coupon code is DYPNM2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the DY Patil Navi Mumbai coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the DY Patil Navi Mumbai coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. D.Y. Patil University, Navi Mumbai Online runs its own scholarships separately, with their own eligibility rules and documents. Ask DY Patil Navi Mumbai admissions or check dypatil.edu for those.' },
      { q: 'Is DY Patil Navi Mumbai UGC-DEB approved?', a: 'Yes. D.Y. Patil University, Navi Mumbai Online is UGC-DEB entitled for online degree programmes and holds NAAC A++. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'kurukshetra-online-mba-discount-coupon-2026',
    universityId: 'kurukshetra-university-online',
    universityName: 'Kurukshetra University Online',
    shortName: 'KUK',
    tier: 'standard',
    totalFee: '₹1.02L',
    totalFeeNum: 102000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1.02L less up to Rs 5,000',
    naac: 'A++',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'KUK2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    officialUrl: 'kuk.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code KUK2026-5K during the enrollment call' },
    ],
    stackExample: 'The KUK2026-5K coupon is applied at enrollment. Any KUK scholarship is administered by the university separately, so confirm with KUK admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with KUK admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the KUK online MBA discount coupon code?', a: 'The verified discount coupon code is KUK2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the KUK coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the KUK coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Kurukshetra University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask KUK admissions or check kuk.ac.in for those.' },
      { q: 'Is KUK UGC-DEB approved?', a: 'Yes. Kurukshetra University Online is UGC-DEB entitled for online degree programmes and holds NAAC A++. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'manav-rachna-online-mba-discount-coupon-2026',
    universityId: 'manav-rachna-online',
    universityName: 'Manav Rachna Online',
    shortName: 'Manav Rachna',
    tier: 'standard',
    totalFee: '₹160K – ₹160K',
    totalFeeNum: 60000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹160K – ₹160K less up to Rs 5,000',
    naac: 'A++',
    nirf: '#96 University',
    couponCode: 'MRU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    officialUrl: 'manavrachna.edu.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code MRU2026-5K during the enrollment call' },
    ],
    stackExample: 'The MRU2026-5K coupon is applied at enrollment. Any Manav Rachna scholarship is administered by the university separately, so confirm with Manav Rachna admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with Manav Rachna admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the Manav Rachna online MBA discount coupon code?', a: 'The verified discount coupon code is MRU2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the Manav Rachna coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the Manav Rachna coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Manav Rachna Online runs its own scholarships separately, with their own eligibility rules and documents. Ask Manav Rachna admissions or check manavrachna.edu.in for those.' },
      { q: 'Is Manav Rachna UGC-DEB approved?', a: 'Yes. Manav Rachna Online is UGC-DEB entitled for online degree programmes and holds NAAC A++. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'mangalayatan-online-mba-discount-coupon-2026',
    universityId: 'mangalayatan-university-online',
    universityName: 'Mangalayatan University Online',
    shortName: 'Mangalayatan',
    tier: 'standard',
    totalFee: '₹67,000',
    totalFeeNum: 60000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹67,000 less up to Rs 5,000',
    naac: 'A+',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'MGU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'is-mangalayatan-university-online-fake-or-legit-2026',
    officialUrl: 'mangalayatan.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code MGU2026-5K during the enrollment call' },
    ],
    stackExample: 'The MGU2026-5K coupon is applied at enrollment. Any Mangalayatan scholarship is administered by the university separately, so confirm with Mangalayatan admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with Mangalayatan admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the Mangalayatan online MBA discount coupon code?', a: 'The verified discount coupon code is MGU2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the Mangalayatan coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the Mangalayatan coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Mangalayatan University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask Mangalayatan admissions or check mangalayatan.in for those.' },
      { q: 'Is Mangalayatan UGC-DEB approved?', a: 'Yes. Mangalayatan University Online is UGC-DEB entitled for online degree programmes and holds NAAC A+. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'vgu-online-mba-discount-coupon-2026',
    universityId: 'vivekananda-global-university-online',
    universityName: 'Vivekananda Global University Online',
    shortName: 'VGU',
    tier: 'standard',
    totalFee: '₹150K – ₹150K',
    totalFeeNum: 60000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹150K – ₹150K less up to Rs 5,000',
    naac: 'A+',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'VGU2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    officialUrl: 'vgu.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code VGU2026-5K during the enrollment call' },
    ],
    stackExample: 'The VGU2026-5K coupon is applied at enrollment. Any VGU scholarship is administered by the university separately, so confirm with VGU admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with VGU admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the VGU online MBA discount coupon code?', a: 'The verified discount coupon code is VGU2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the VGU coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the VGU coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. Vivekananda Global University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask VGU admissions or check vgu.ac.in for those.' },
      { q: 'Is VGU UGC-DEB approved?', a: 'Yes. Vivekananda Global University Online is UGC-DEB entitled for online degree programmes and holds NAAC A+. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'gla-online-mba-discount-coupon-2026',
    universityId: 'gla-university-online',
    universityName: 'GLA University Online',
    shortName: 'GLA',
    tier: 'standard',
    totalFee: '₹1.76L – ₹2.2L',
    totalFeeNum: 140000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: '₹1.76L – ₹2.2L less up to Rs 5,000',
    naac: 'A+',
    nirf: 'Not ranked in NIRF 2025',
    couponCode: 'GLA2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    officialUrl: 'gla.ac.in',
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code GLA2026-5K during the enrollment call' },
    ],
    stackExample: 'The GLA2026-5K coupon is applied at enrollment. Any GLA scholarship is administered by the university separately, so confirm with GLA admissions whether the two can be combined for your batch.',
    emiCompatible: 'Confirm with GLA admissions. Some universities apply coupon discounts to lump-sum payment only.',
    exclusions: [
      'Applies to the programme fee only, not to exam or registration charges',
      'Cannot be combined with other third-party coupon codes for the same programme',
      'Not transferable and not redeemable for cash',
      'Final amount is at the discretion of the university admissions team at enrollment',
    ],
    faqs: [
      { q: 'What is the GLA online MBA discount coupon code?', a: 'The verified discount coupon code is GLA2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save with the GLA coupon code?', a: 'Up to Rs 5,000 on Tuesday or Saturday in IST, and Rs 4,000 on other days. The coupon is applied at enrollment by our admission desk with no eligibility check and no paperwork.' },
      { q: 'Is the GLA coupon the same as a university scholarship?', a: 'No. This coupon is an enrollment-time fee adjustment coordinated by the edifyedu.in admission desk. GLA University Online runs its own scholarships separately, with their own eligibility rules and documents. Ask GLA admissions or check gla.ac.in for those.' },
      { q: 'Is GLA UGC-DEB approved?', a: 'Yes. GLA University Online is UGC-DEB entitled for online degree programmes and holds NAAC A+. Confirm current entitlement yourself at deb.ugc.ac.in before you enrol.' },
      { q: 'Can the coupon be combined with an EMI plan?', a: 'Usually yes, but some universities apply a coupon to lump-sum payment only. Our admission desk confirms the exact terms for the 2026 batch on your free enrollment call.' },
      { q: 'Does the coupon reduce exam or registration fees?', a: 'No. The coupon applies to the programme fee only. Examination, registration and any re-attempt charges are billed separately by the university.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 5,000 via MUJ2026-4K' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K' },
    ],
  },
  {
    slug: 'galgotias-online-mba-discount-coupon-2026',
    universityId: 'galgotias-university-online',
    universityName: 'Galgotias University Online',
    shortName: 'Galgotias',
    tier: 'standard',
    totalFee: 'Rs 80,200',
    totalFeeNum: 80200,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 75,200',
    // NAAC A+, score 3.37, cycle 1, valid to 2029-08-16 per Supabase.
    naac: 'A+',
    // Supabase holds only Pharmacy #55 and Law #36 for Galgotias. There is no
    // University rank and no Management rank, so no rank is claimed here. The
    // programme hub content mentions a "NIRF band 101-125 (Management)" that
    // the source of truth does not carry, which is why this states a bound
    // rather than repeating it.
    nirf: 'Not ranked in the NIRF 2025 top 100',
    couponCode: 'GALG2026-5K',
    couponDiscount: 'Up to Rs 5,000 verified discount coupon (Tue/Sat IST)',
    blogSlug: 'galgotias-online-mba-review',
    officialUrl: 'galgotiasonline.edu.in',
    // Only the coupon is listed, and that is the whole list. Rishi confirmed on
    // 2026-09-14 that Galgotias runs no scholarship or fee-waiver scheme on its
    // online programmes, which matches what the specialisation pages have always
    // said. The programme hub's claim to the contrary was unverified boilerplate
    // shared with five other universities and has been corrected.
    discounts: [
      { type: 'verified discount coupon', eligibility: 'All students via admission desk', saving: 'Up to Rs 5,000 on Tue/Sat IST, Rs 4,000 other days', howToApply: 'Mention code GALG2026-5K during enrollment call' },
    ],
    stackExample: 'There is nothing to stack. Galgotias runs no scholarship or fee-waiver scheme on its online programmes, so the coupon is the only reduction available: up to Rs 5,000 on a Tuesday or Saturday window, against an indicative programme fee of Rs 80,200.',
    emiCompatible: 'The coupon reduces the fee before any instalment plan is calculated. Some universities apply coupon discounts to lump-sum payment only, so confirm the exact terms with the Galgotias admissions team for the 2026-27 batch.',
    exclusions: ['Does not reduce the registration fee or per-semester examination charges', 'Cannot be combined with other third-party commercial coupon codes for the same programme', 'Does not override Galgotias admission eligibility or batch quotas', 'Not transferable and not redeemable for cash'],
    faqs: [
      { q: 'What is the Galgotias online MBA discount coupon code for 2026?', a: 'The verified discount coupon code is GALG2026-5K. It carries up to Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days. The amount is applied as a fee adjustment during your enrollment process.' },
      { q: 'What is the total Galgotias online MBA fee?', a: 'The programme fee is Rs 80,200, paid across four semesters over two years. This figure is indicative. Registration and per-semester examination charges are separate. Confirm the current fee on galgotiasonline.edu.in before making any payment.' },
      { q: 'Does Galgotias offer any scholarship on the online MBA?', a: 'No. Galgotias runs no scholarship or fee-waiver scheme on its online programmes. There is no merit slab, no defence concession and no alumni discount to apply for. That makes the GALG2026-5K coupon the only reduction available on the Rs 80,200 fee. Confirm the current position on galgotiasonline.edu.in before you pay.' },
      { q: 'Why is there no merit scholarship when other universities offer one?', a: 'Galgotias prices the online MBA low at the outset instead of listing a high fee and discounting it back down. For comparison, Amity starts at Rs 2,07,000 and Chandigarh at Rs 1,65,000 before any waiver is applied. Compare the amount you actually pay rather than the size of the discount advertised.' },
      { q: 'Can I use the Galgotias code with EMI?', a: 'The coupon reduces the fee first, and the balance is then spread under whatever instalment plan Galgotias offers for the batch. Some universities apply coupon discounts to lump-sum payment only. Confirm the terms with the Galgotias admissions team during enrollment.' },
      { q: 'When is the best time to use GALG2026-5K?', a: 'The coupon reaches its maximum of Rs 5,000 on Tuesday and Saturday in IST, and Rs 4,000 on other days. Time your enrollment call so the final fee invoice is generated on one of those two days.' },
      { q: 'Where do I enter the Galgotias code?', a: 'The code is mentioned during the admissions process to your admission desk, not on the Galgotias website. Our admission desk coordinates with the Galgotias admissions team so the adjustment is reflected in your fee invoice.' },
      { q: 'Is the Galgotias online MBA UGC-DEB approved?', a: 'Yes. Galgotias University Online is UGC-DEB approved for online degree programmes and holds NAAC A+ accreditation. The degree certificate identifies the programme as Online mode, per UGC (Online Programmes) Regulations 2018. It is valid for UPSC, banking exams, PSU recruitment and private-sector employment.' },
      { q: 'Does Galgotias have a NIRF rank?', a: 'Galgotias University does not appear in the NIRF 2025 top 100 for Management or for University. It holds NAAC A+ with a score of 3.37, valid to August 2029. Judge the programme on its accreditation and fee rather than on a rank it does not hold.' },
    ],
    peerComparisons: [
      { uni: 'IGNOU (Rs 66,000)', savings: 'No coupon, lower base fee' },
      { uni: 'Chandigarh (from Rs 1,65,000)', savings: 'Up to Rs 5,000 via CU2026-5K' },
      { uni: 'JAIN (from Rs 1,75,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K' },
      { uni: 'Amity (from Rs 2,07,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K' },
    ],
  },
]

export function getCouponPage(slug: string): CouponPageData | undefined {
  return COUPON_PAGES.find(p => p.slug === slug)
}

export const COUPON_PAGE_SLUGS = COUPON_PAGES.map(p => p.slug)

/**
 * Exact universityId -> coupon page slug.
 *
 * The /coupons hub used to resolve this by taking the first hyphen-segment of
 * a coupon's universityId and finding the first page slug that *contained* it.
 * That matched on substrings and silently mis-routed:
 *   'dy-patil-university-online' -> 'dy' -> matched 'bharati-vi(dy)apeeth-...'
 * and it found nothing at all whenever the slug uses a short form the id does
 * not start with (lovely-professional -> lpu, sikkim-manipal -> smu,
 * dayananda-sagar -> dsu, vivekananda-global -> vgu), so five coupon cards
 * linked to no page. Always resolve through this map.
 */
export const COUPON_PAGE_BY_UNIVERSITY: Record<string, string> = Object.fromEntries(
  COUPON_PAGES.map(p => [p.universityId, p.slug]),
)

export function getCouponPageSlugForUniversity(universityId: string): string | undefined {
  return COUPON_PAGE_BY_UNIVERSITY[universityId]
}
