// lib/coupon-pages.ts — Data for dedicated university coupon pages.
// Each page targets "[uni] online MBA enrollment bonus" queries.
//
// Each entry carries a `tier` that maps to lib/coupons.ts → TIER_AMOUNTS:
//   premium  → max Rs 7,500 (Tue/Sat) · base Rs 5,000
//   standard → max Rs 5,000 (Tue/Sat) · base Rs 4,000
//   budget   → max Rs 4,000 (Tue/Sat) · base Rs 3,000
//
// `maxSavings` / `maxSavingsNum` represent the edifyedu.in enrollment bonus
// at the tier's MAX window. University scholarships (merit, defence, lump-sum)
// are described in the body text and are independent.

import type { Tier } from './coupons'

export interface CouponPageData {
  slug: string
  universityId: string
  universityName: string
  shortName: string
  tier: Tier
  totalFee: string
  totalFeeNum: number
  maxSavings: string
  maxSavingsNum: number
  finalFee: string
  naac: string
  nirf: string
  couponCode: string
  couponDiscount: string
  blogSlug: string
  officialUrl: string
  discounts: { type: string; eligibility: string; saving: string; howToApply: string }[]
  stackExample: string
  emiCompatible: string
  exclusions: string[]
  faqs: { q: string; a: string }[]
  peerComparisons: { uni: string; savings: string }[]
}

export const COUPON_PAGES: CouponPageData[] = [
  {
    slug: 'amity-online-mba-discount-coupon-2026',
    universityId: 'amity-university-online',
    universityName: 'Amity University Online',
    shortName: 'Amity',
    tier: 'standard',
    totalFee: 'Rs 2,25,000',
    totalFeeNum: 225000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 2,20,000',
    naac: 'A+',
    nirf: '#22 University',
    couponCode: 'AMTY2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'amity-online-mba-review-2026',
    officialUrl: 'amityonline.com',
    discounts: [
      { type: 'Lump-sum payment', eligibility: 'All students', saving: 'Rs 18,000 (pay Rs 2,07,000 instead of Rs 2,25,000)', howToApply: 'Select one-time payment during fee payment' },
      { type: 'Merit scholarship', eligibility: '60%+ in graduation', saving: '10-20% fee waiver', howToApply: 'Upload marksheets during application' },
      { type: 'Defence personnel', eligibility: 'Serving/retired defence, JCO', saving: 'Additional discount on tuition', howToApply: 'Submit defence ID during admission' },
      { type: 'Divyaang scholarship', eligibility: 'Candidates with disability certificate', saving: 'Up to 100% fee waiver', howToApply: 'Submit disability certificate' },
      { type: 'Alumni discount', eligibility: 'Amity University alumni', saving: '5-10% additional', howToApply: 'Verify alumni status during admission' },
      { type: 'CHAMPS (Sports)', eligibility: 'National/state level sports achievement', saving: 'Performance-based waiver', howToApply: 'Submit sports certificates' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code AMTY2026-5K during advisor call' },
    ],
    stackExample: 'If you have 70%+ graduation marks AND pay lump-sum AND apply during a Tue/Sat max window, your stacked savings reach Rs 35,000-50,000 on a Rs 2,25,000 programme. That brings your effective fee to Rs 1,75,000-1,90,000.',
    emiCompatible: 'Yes. Amity allows the edifyedu.in bonus to be applied first, then the reduced balance can be paid via 24-month no-cost EMI.',
    exclusions: ['Does not reduce examination fees', 'Does not apply to ACCA International Finance track (Rs 2,99,000 separate pricing)', 'Cannot be combined with other third-party commercial coupons', 'Does not waive application fee (Rs 1,100)'],
    faqs: [
      { q: 'What is the Amity online MBA enrollment bonus code for 2026?', a: 'The verified edifyedu.in code is AMTY2026-5K. It carries up to Rs 5,000 enrollment bonus on Tuesday and Saturday in IST, and Rs 4,000 on other days. The bonus is applied as a fee adjustment during your advisor-assisted enrollment.' },
      { q: 'How much can I save in total on Amity Online MBA fees?', a: 'Stacked savings reach Rs 35,000-50,000 when you combine the lump-sum payment discount (Rs 18,000 from Amity), merit scholarship (10-20% from Amity), and the edifyedu.in enrollment bonus (up to Rs 5,000 on Tue/Sat). Standard fee is Rs 2,25,000.' },
      { q: 'Can I use the Amity code with EMI?', a: 'Yes. The bonus reduces the total fee first. You can then pay the remaining balance via 24-month no-cost EMI on the reduced amount.' },
      { q: 'Is the Amity AIC referral code different from the edifyedu.in code?', a: 'Yes. AIC (Amity International Centre) referral codes are peer-to-peer codes from existing students. The edifyedu.in code is an enrollment bonus from edifyedu.in. They can potentially be stacked. Ask your advisor for details.' },
      { q: 'Does Amity offer an early-bird discount?', a: 'Amity periodically offers early-bird discounts for new batches (January and July intakes). The discount varies by batch. Contact our advisor for the current early-bird deadline and saving amount.' },
      { q: 'Where do I enter the Amity code?', a: 'The code is mentioned during the admissions process to your edifyedu.in advisor, not on the Amity website directly. Your advisor coordinates with the Amity admissions team so the bonus is reflected in your fee invoice.' },
      { q: 'Are there separate codes for Amity MCA?', a: 'Yes. AMTYMCA2026-5K applies to Amity Online MCA with the same standard-tier amounts (up to Rs 5,000 on Tue/Sat).' },
      { q: 'Is the Amity merit scholarship automatic?', a: 'Yes. Merit scholarships (based on graduation marks) are evaluated automatically during admission. Upload your marksheets and the scholarship is assessed. Defence and divyaang scholarships require additional documentation.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K (standard tier)' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K (standard tier)' },
      { uni: 'Chandigarh (Rs 1,65,000)', savings: 'Up to Rs 5,000 via CU2026-5K (standard tier)' },
      { uni: 'IGNOU (Rs 66,000)', savings: 'No coupon but lowest base fee in India' },
    ],
  },
  {
    slug: 'nmims-online-mba-discount-coupon-2026',
    universityId: 'nmims-online',
    universityName: 'NMIMS Online',
    shortName: 'NMIMS',
    tier: 'standard',
    totalFee: 'Rs 2,20,000',
    totalFeeNum: 220000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 2,15,000',
    naac: 'A++',
    nirf: '#17 Management',
    couponCode: 'NMIMS2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'nmims-online-mba-review-2026',
    officialUrl: 'online.nmims.edu',
    discounts: [
      { type: 'One-time payment', eligibility: 'All students', saving: 'Rs 24,000 (pay Rs 1,96,000 vs Rs 2,20,000 semester-wise)', howToApply: 'Select one-time payment option' },
      { type: 'Armed Forces scholarship', eligibility: 'Serving/retired defence personnel', saving: '20% fee waiver', howToApply: 'Submit defence ID during admission' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code NMIMS2026-5K during advisor call' },
    ],
    stackExample: 'NMIMS offers fewer discount categories than Amity but the one-time payment discount of Rs 24,000 is significant. Combined with the edifyedu.in bonus (up to Rs 5,000 on Tue/Sat), total savings reach Rs 27,000-29,000.',
    emiCompatible: 'Yes. NMIMS offers 3, 6, 9, and 12-month no-cost EMI through education lending partners. The bonus is applied to the total fee first.',
    exclusions: ['Does not reduce application fee (Rs 1,200)', 'Does not apply to executive MBA tracks', 'Cannot combine with other third-party coupons'],
    faqs: [
      { q: 'What is the NMIMS online MBA enrollment bonus code for 2026?', a: 'The verified edifyedu.in code is NMIMS2026-5K. It carries up to Rs 5,000 enrollment bonus on Tuesday and Saturday in IST, and Rs 4,000 on other days.' },
      { q: 'How much can I save on NMIMS Online MBA?', a: 'Total savings of Rs 27,000-29,000 when combining the one-time payment discount (Rs 24,000 from NMIMS) and the edifyedu.in enrollment bonus (up to Rs 5,000 on Tue/Sat). Semester-wise total is Rs 2,20,000.' },
      { q: 'Can I use the NMIMS code with EMI?', a: 'Yes. The bonus reduces the total fee first. You can then pay via 3 to 12 month no-cost EMI on the reduced amount.' },
      { q: 'Does NMIMS offer a merit scholarship for the online MBA?', a: 'NMIMS does not prominently advertise merit-based scholarships for the online MBA. The primary savings come from one-time payment and the Armed Forces scholarship (20% for defence personnel).' },
      { q: 'Is NMIMS online MBA Rs 1,96,000 or Rs 2,20,000?', a: 'Both are correct. Rs 1,96,000 is the one-time payment price. Rs 2,20,000 is the semester-wise total (Rs 55,000 x 4). The difference of Rs 24,000 is the lump-sum payment discount.' },
      { q: 'Where do I apply the NMIMS code?', a: 'Mention the code to your edifyedu.in advisor during the admissions call. Your advisor coordinates with NMIMS admissions so the bonus is reflected in your invoice.' },
      { q: 'Is NMIMS NIRF #17 Management rank verified?', a: 'Yes. NMIMS holds NIRF #17 in the Management category for 2025. Verified from nirfindia.org.' },
      { q: 'Does NMIMS have AACSB accreditation?', a: 'NMIMS is an AACSB member institution. AACSB is one of the most respected global business school accreditations, held by fewer than 6% of business schools worldwide.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K (standard tier)' },
      { uni: 'Symbiosis (Rs 3,15,000)', savings: 'Up to Rs 7,500 via SYMB2026-7500 (premium tier)' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K (standard tier)' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 4,000 via MUJ2026-4K (budget tier)' },
    ],
  },
  {
    slug: 'manipal-jaipur-online-mba-discount-coupon-2026',
    universityId: 'manipal-university-jaipur-online',
    universityName: 'Manipal University Jaipur (MUJ) Online',
    shortName: 'MUJ',
    tier: 'budget',
    totalFee: 'Rs 1,80,000',
    totalFeeNum: 180000,
    maxSavings: 'Rs 4,000',
    maxSavingsNum: 4000,
    finalFee: 'Rs 1,76,000',
    naac: 'A+',
    nirf: '#58 University',
    couponCode: 'MUJ2026-4K',
    couponDiscount: 'Up to Rs 4,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'muj-online-mba-review-2026',
    officialUrl: 'jaipur.manipal.edu',
    discounts: [
      { type: '15% upfront discount', eligibility: 'All students paying full fee upfront', saving: 'Rs 27,000 (pay Rs 1,53,000)', howToApply: 'Select one-time payment during enrollment' },
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Divyaang scholarship', eligibility: 'Disability certificate holders', saving: 'Up to 100%', howToApply: 'Submit disability certificate' },
      { type: 'Merit scholarship', eligibility: '60%+ graduation marks', saving: '5-15%', howToApply: 'Automatic during admission' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 4,000 (Tue/Sat max window, Rs 3,000 other days)', howToApply: 'Mention code MUJ2026-4K during advisor call' },
    ],
    stackExample: 'MUJ offers a strong 15% upfront payment discount that brings the fee from Rs 1,80,000 to Rs 1,53,000. Stack with the edifyedu.in bonus (up to Rs 4,000 on Tue/Sat) for additional savings.',
    emiCompatible: 'Yes. MUJ offers EMI options. The bonus is applied to the total fee first.',
    exclusions: ['Does not apply to dual specialisation upgrade fees', 'Does not reduce exam or registration fees', 'Cannot combine with other third-party coupons'],
    faqs: [
      { q: 'What is the MUJ online MBA enrollment bonus code?', a: 'The verified edifyedu.in code is MUJ2026-4K (budget tier). It carries up to Rs 4,000 on Tuesday and Saturday in IST, and Rs 3,000 on other days.' },
      { q: 'How much does MUJ online MBA cost after the bonus?', a: 'Standard fee is Rs 1,80,000. With 15% upfront discount from MUJ: Rs 1,53,000. With the edifyedu.in bonus on top: an additional Rs 3,000-4,000 saving.' },
      { q: 'Does MUJ include Coursera Plus?', a: 'Yes. MUJ bundles free Coursera Plus access throughout the programme. This is included in the fee and is not affected by the bonus.' },
      { q: 'Is there a separate MCA code for MUJ?', a: 'Yes. MUJMCA2026-4K applies to MUJ Online MCA with the same budget-tier amounts.' },
      { q: 'Is MUJ the same as MAHE Manipal?', a: 'No. MUJ (Manipal University Jaipur) and MAHE (Manipal Academy of Higher Education, Karnataka) are separate universities under the Manipal group. MUJ is more affordable; MAHE has higher NIRF rank.' },
      { q: 'Can I switch from semester payment to one-time after enrollment?', a: 'Typically no. The 15% upfront discount applies only if you choose one-time payment at the start. Confirm with the MUJ admissions team before enrolling.' },
    ],
    peerComparisons: [
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K (standard tier)' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K (standard tier)' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K (standard tier)' },
      { uni: 'MAHE (Rs 2,92,000)', savings: 'Up to Rs 7,500 via MAHE2026-7500 (premium tier)' },
    ],
  },
  {
    slug: 'lpu-online-mba-discount-coupon-2026',
    universityId: 'lovely-professional-university-online',
    universityName: 'LPU Online',
    shortName: 'LPU',
    tier: 'standard',
    totalFee: 'Rs 1,61,000',
    totalFeeNum: 161000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,56,000',
    naac: 'A++',
    nirf: '#31 University',
    couponCode: 'LPU2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'online-mba-lpu-review-2026',
    officialUrl: 'online.lpu.in',
    discounts: [
      { type: '20% placement-linked grant', eligibility: 'All students', saving: 'Built into fee structure', howToApply: 'Automatic - included in advertised fee' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code LPU2026-5K during advisor call' },
    ],
    stackExample: 'LPU already includes a 20% placement-linked grant in its advertised fee. Additional savings through the edifyedu.in bonus (up to Rs 5,000 on Tue/Sat) bring effective fee close to Rs 1,56,000.',
    emiCompatible: 'Yes. LPU offers semester-wise and EMI payment options after the bonus is applied.',
    exclusions: ['Does not reduce exam fees', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the LPU online MBA enrollment bonus code?', a: 'LPU2026-5K (standard tier). Up to Rs 5,000 on Tuesday and Saturday in IST, Rs 4,000 on other days. Mention to your edifyedu.in advisor.' },
      { q: 'What is the LPU online MBA total fee?', a: 'Rs 1,61,000 total with the 20% placement-linked grant already included. Without grant: Rs 2,00,000.' },
      { q: 'Does LPU have NAAC A++ accreditation?', a: 'Yes. LPU holds NAAC A++, the highest grade.' },
      { q: 'Is there a separate LPU MCA code?', a: 'Yes. LPUMCA2026-5K applies to LPU Online MCA with the same standard-tier amounts.' },
      { q: 'How does the LPU placement-linked grant work?', a: 'LPU includes a 20% fee reduction as a "placement-linked grant" in the advertised fee. This is automatic and does not require a separate application.' },
    ],
    peerComparisons: [
      { uni: 'Chandigarh (Rs 1,65,000)', savings: 'Up to Rs 5,000 via CU2026-5K (standard tier)' },
      { uni: 'Galgotias (Rs 76,200)', savings: 'Up to Rs 5,000 via GALG2026-5K (standard tier)' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 4,000 via MUJ2026-4K (budget tier)' },
    ],
  },
  {
    slug: 'chandigarh-university-online-mba-discount-coupon-2026',
    universityId: 'chandigarh-university-online',
    universityName: 'Chandigarh University Online',
    shortName: 'Chandigarh',
    tier: 'standard',
    totalFee: 'Rs 1,65,000',
    totalFeeNum: 165000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,60,000',
    naac: 'A+',
    nirf: '#19 University',
    couponCode: 'CU2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'chandigarh-university-online-mba-review',
    officialUrl: 'cuonlineedu.in',
    discounts: [
      { type: 'Harvard/PwC/PMI certifications', eligibility: 'All students', saving: 'Bundled at no extra cost (worth Rs 50,000+)', howToApply: 'Included automatically in programme' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code CU2026-5K during advisor call' },
    ],
    stackExample: 'Chandigarh bundles Harvard Business Publishing, PwC, and PMI certifications at no extra cost - worth Rs 50,000+ if purchased separately. Combined with the edifyedu.in bonus (up to Rs 5,000 on Tue/Sat), total value exceeds Rs 55,000.',
    emiCompatible: 'Yes. CU offers EMI options on the reduced fee.',
    exclusions: ['Does not reduce Tier 2 programme fee (Rs 1,80,000)', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Chandigarh University online MBA enrollment bonus code?', a: 'CU2026-5K (standard tier). Up to Rs 5,000 on Tuesday and Saturday in IST. Mention to your edifyedu.in advisor.' },
      { q: 'What certifications does CU bundle for free?', a: 'Harvard Business Publishing, PwC, and PMI certifications are included at no extra cost in the CU online MBA fee.' },
      { q: 'Is there a separate CU MCA code?', a: 'Yes. CUMCA2026-5K applies to CU Online MCA with the same standard-tier amounts.' },
      { q: 'What is the difference between CU Tier 1 and Tier 2?', a: 'Tier 1 costs Rs 1,65,000 and Tier 2 costs Rs 1,80,000. Both include the same certifications. Tier selection depends on your application timing and batch.' },
    ],
    peerComparisons: [
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K (standard tier)' },
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 4,000 via MUJ2026-4K (budget tier)' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'smu-online-mba-discount-coupon-2026',
    universityId: 'sikkim-manipal-university-online',
    universityName: 'Sikkim Manipal University Online',
    shortName: 'SMU',
    tier: 'budget',
    totalFee: 'Rs 1,20,000',
    totalFeeNum: 120000,
    maxSavings: 'Rs 4,000',
    maxSavingsNum: 4000,
    finalFee: 'Rs 1,16,000',
    naac: 'A+',
    nirf: 'Not ranked in top 200',
    couponCode: 'SMU2026-4K',
    couponDiscount: 'Up to Rs 4,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'smu-online-mba-review',
    officialUrl: 'onlinesmu.com',
    discounts: [
      { type: 'Northeast India scholarship', eligibility: 'Northeast India and Sikkim residents', saving: '30% fee waiver', howToApply: 'Submit domicile certificate' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 4,000 (Tue/Sat max window, Rs 3,000 other days)', howToApply: 'Mention code SMU2026-4K during advisor call' },
    ],
    stackExample: 'SMU is the most affordable Manipal-group MBA. Northeast residents save 30% automatically, bringing effective fee to Rs 84,000. Add the edifyedu.in bonus (up to Rs 4,000 on Tue/Sat) on top.',
    emiCompatible: 'Yes. SMU offers EMI on the reduced fee amount.',
    exclusions: ['Does not apply to executive MBA tracks', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the SMU online MBA enrollment bonus code?', a: 'SMU2026-4K (budget tier). Up to Rs 4,000 on Tuesday and Saturday in IST, Rs 3,000 on other days.' },
      { q: 'Is SMU the cheapest Manipal MBA?', a: 'Yes. SMU at Rs 1,20,000 is cheaper than MUJ (Rs 1,80,000) and MAHE (Rs 2,92,000).' },
      { q: 'Does SMU offer the Northeast India scholarship?', a: 'Yes. 30% fee waiver for Northeast India and Sikkim residents.' },
      { q: 'Is SMU different from MUJ?', a: 'Yes. SMU (Sikkim) and MUJ (Jaipur) are separate universities under the Manipal group.' },
    ],
    peerComparisons: [
      { uni: 'MUJ (Rs 1,80,000)', savings: 'Up to Rs 4,000 via MUJ2026-4K (budget tier)' },
      { uni: 'Galgotias (Rs 76,200)', savings: 'Up to Rs 5,000 via GALG2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'mahe-online-mba-discount-coupon-2026',
    universityId: 'manipal-academy-higher-education-online',
    universityName: 'MAHE Manipal Online',
    shortName: 'MAHE',
    tier: 'premium',
    totalFee: 'Rs 2,92,000',
    totalFeeNum: 292000,
    maxSavings: 'Rs 7,500',
    maxSavingsNum: 7500,
    finalFee: 'Rs 2,84,500',
    naac: 'A++',
    nirf: '#3 University',
    couponCode: 'MAHE2026-7500',
    couponDiscount: 'Up to Rs 7,500 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'mahe-online-mba-review-2026',
    officialUrl: 'onlinemanipal.com',
    discounts: [
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Female candidate scholarship', eligibility: 'Female applicants', saving: '15% fee waiver', howToApply: 'Automatic during admission' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 7,500 (Tue/Sat max window, Rs 5,000 other days)', howToApply: 'Mention code MAHE2026-7500 during advisor call' },
    ],
    stackExample: 'MAHE offers Defence (20%) and Female (15%) scholarships. Combined with the edifyedu.in premium-tier bonus (up to Rs 7,500 on Tue/Sat), total discount reaches Rs 50,000+ for eligible candidates.',
    emiCompatible: 'Yes. MAHE offers Coursera-integrated EMI options.',
    exclusions: ['Does not reduce exam fees', 'Premium tracks may have separate pricing'],
    faqs: [
      { q: 'What is the MAHE online MBA enrollment bonus code?', a: 'MAHE2026-7500 (premium tier). Up to Rs 7,500 on Tuesday and Saturday in IST, Rs 5,000 on other days.' },
      { q: 'Is MAHE worth Rs 2.92L?', a: 'MAHE carries NIRF #3 University rank and NAAC A++. For employers who value the MAHE brand, the premium is justified.' },
      { q: 'Does MAHE offer a female scholarship?', a: 'Yes. 15% fee waiver for female applicants, applied automatically.' },
      { q: 'Is MAHE the same as MUJ?', a: 'No. MAHE (Karnataka) and MUJ (Jaipur) are separate universities under the Manipal group.' },
    ],
    peerComparisons: [
      { uni: 'Symbiosis (Rs 3,15,000)', savings: 'Up to Rs 7,500 via SYMB2026-7500 (premium tier)' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'jain-online-mba-discount-coupon-2026',
    universityId: 'jain-university-online',
    universityName: 'JAIN Online',
    shortName: 'JAIN',
    tier: 'standard',
    totalFee: 'Rs 1,96,000',
    totalFeeNum: 196000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,91,000',
    naac: 'A++',
    nirf: '#62 Management',
    couponCode: 'JAIN2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'best-mba-specialization-india-2026',
    officialUrl: 'online.jainuniversity.ac.in',
    discounts: [
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code JAIN2026-5K during advisor call' },
      { type: 'Merit scholarship', eligibility: '60%+ graduation', saving: '10-20%', howToApply: 'Automatic during admission' },
    ],
    stackExample: 'JAIN offers NAAC A++ at Rs 1,96,000 with 19 specializations and ACCA integration. The edifyedu.in bonus adds up to Rs 5,000 on Tue/Sat on top of any merit scholarship.',
    emiCompatible: 'Yes. JAIN offers EMI options on the reduced fee.',
    exclusions: ['Does not reduce ACCA track premium', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the JAIN online MBA enrollment bonus code?', a: 'JAIN2026-5K (standard tier). Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does JAIN have NAAC A++?', a: 'Yes. JAIN Online holds NAAC A++ accreditation.' },
      { q: 'Is there a JAIN MCA code?', a: 'Yes. JAINMCA2026-5K applies to JAIN Online MCA with the same standard-tier amounts.' },
      { q: 'Does JAIN offer ACCA integration?', a: 'Yes. JAIN Online offers ACCA-integrated International Finance specialisation.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K (standard tier)' },
      { uni: 'Amity (Rs 2,25,000)', savings: 'Up to Rs 5,000 via AMTY2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'symbiosis-ssodl-online-mba-discount-coupon-2026',
    universityId: 'symbiosis-university-online',
    universityName: 'Symbiosis SSODL Online',
    shortName: 'Symbiosis',
    tier: 'premium',
    totalFee: 'Rs 3,15,000',
    totalFeeNum: 315000,
    maxSavings: 'Rs 7,500',
    maxSavingsNum: 7500,
    finalFee: 'Rs 3,07,500',
    naac: 'A++',
    nirf: '#32 Management',
    couponCode: 'SYMB2026-7500',
    couponDiscount: 'Up to Rs 7,500 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'symbiosis-online-mba-review-2026',
    officialUrl: 'ssodl.symbiosis.ac.in',
    discounts: [
      { type: 'Work experience scholarship', eligibility: '2+ years professional experience', saving: 'Rs 50,000-55,000 (fee becomes Rs 2,65,000)', howToApply: 'Submit experience letters during admission' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 7,500 (Tue/Sat max window, Rs 5,000 other days)', howToApply: 'Mention code SYMB2026-7500 during advisor call' },
    ],
    stackExample: 'Symbiosis offers a Rs 50,000-55,000 work experience scholarship for 2+ years professionals. This brings the fee from Rs 3,15,000 to Rs 2,65,000. The edifyedu.in premium-tier bonus adds up to Rs 7,500 on Tue/Sat on top.',
    emiCompatible: 'Yes. Symbiosis offers semester-wise payment after the bonus is applied.',
    exclusions: ['Does not reduce registration fee', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Symbiosis online MBA enrollment bonus code?', a: 'SYMB2026-7500 (premium tier). Up to Rs 7,500 on Tuesday and Saturday in IST, Rs 5,000 on other days.' },
      { q: 'What is the Symbiosis work experience scholarship?', a: 'Rs 50,000-55,000 fee waiver for candidates with 2+ years of professional experience.' },
      { q: 'Is Symbiosis the most expensive online MBA?', a: 'Symbiosis is among the most expensive at Rs 3,15,000 (with scholarship) to Rs 3,70,000 (without). The premium buys NAAC A++ and NIRF #32 Management rank.' },
      { q: 'Does Symbiosis require work experience?', a: 'No. Work experience is not required for admission but it qualifies you for the Rs 50,000+ scholarship.' },
    ],
    peerComparisons: [
      { uni: 'MAHE (Rs 2,92,000)', savings: 'Up to Rs 7,500 via MAHE2026-7500 (premium tier)' },
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'ignou-online-mba-discount-coupon-2026',
    universityId: 'ignou-online',
    universityName: 'IGNOU Online',
    shortName: 'IGNOU',
    tier: 'budget',
    totalFee: 'Rs 66,000',
    totalFeeNum: 66000,
    maxSavings: 'Rs 0',
    maxSavingsNum: 0,
    finalFee: 'Rs 66,000',
    naac: 'A++',
    nirf: '#1 Open University',
    couponCode: 'N/A',
    couponDiscount: 'No coupon - lowest base fee in India',
    blogSlug: 'ignou-online-mba-review-2026',
    officialUrl: 'ignou.ac.in',
    discounts: [
      { type: 'Already lowest fee', eligibility: 'All students', saving: 'Rs 66,000 total - no further discount needed', howToApply: 'Apply directly on ignou.ac.in' },
      { type: 'SC/ST fee concession', eligibility: 'SC/ST category candidates', saving: 'Reduced fee structure', howToApply: 'Submit caste certificate during admission' },
    ],
    stackExample: 'IGNOU at Rs 66,000 is already the lowest-priced online MBA from a NAAC A++ university. No coupons are needed. The fee itself is the discount.',
    emiCompatible: 'IGNOU does not offer formal EMI. Fee is paid semester-wise (Rs 14,000-16,000 per semester).',
    exclusions: ['No coupon system - IGNOU is a central government university with fixed fees'],
    faqs: [
      { q: 'Is there an IGNOU online MBA coupon code?', a: 'No. IGNOU is a central government university with the lowest online MBA fee in India (Rs 66,000). No coupon is needed or applicable.' },
      { q: 'Why is IGNOU MBA so cheap?', a: 'IGNOU is funded by the Government of India and operates as a not-for-profit institution. The low fee reflects government subsidization, not lower quality.' },
      { q: 'Is IGNOU MBA valid for government jobs?', a: 'Yes. IGNOU holds NAAC A++ and is arguably the strongest online MBA for government job eligibility as a central university.' },
      { q: 'Should I choose IGNOU or Amity?', a: 'IGNOU for pure affordability and government job eligibility. Amity for structured LMS, live sessions, international accreditation (WASC+QAA), and 19 specialisations.' },
    ],
    peerComparisons: [
      { uni: 'Galgotias (Rs 76,200)', savings: 'Up to Rs 5,000 via GALG2026-5K (standard tier)' },
      { uni: 'SMU (Rs 1,20,000)', savings: 'Up to Rs 4,000 via SMU2026-4K (budget tier)' },
    ],
  },
  {
    slug: 'dpu-online-mba-discount-coupon-2026',
    universityId: 'dr-dy-patil-vidyapeeth-online',
    universityName: 'DY Patil Vidyapeeth Online',
    shortName: 'DPU',
    tier: 'standard',
    totalFee: 'Rs 1,20,000',
    totalFeeNum: 120000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,15,000',
    naac: 'A++',
    nirf: 'Ranked',
    couponCode: 'DPU2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'dy-patil-online-mba-review',
    officialUrl: 'dypatilonline.com',
    discounts: [
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code DPU2026-5K during advisor call' },
    ],
    stackExample: 'DPU offers a competitive Rs 1,20,000 fee with NAAC A++ and WES recognition. The edifyedu.in bonus adds up to Rs 5,000 on Tue/Sat.',
    emiCompatible: 'Yes. DPU offers EMI options.',
    exclusions: ['Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the DY Patil online MBA enrollment bonus code?', a: 'DPU2026-5K (standard tier). Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does DPU have NAAC A++?', a: 'Yes. Dr. DY Patil Vidyapeeth holds NAAC A++ accreditation.' },
      { q: 'Is DPU WES recognised?', a: 'Yes. DPU online MBA is WES recognised for international credential evaluation.' },
    ],
    peerComparisons: [
      { uni: 'SMU (Rs 1,20,000)', savings: 'Up to Rs 4,000 via SMU2026-4K (budget tier)' },
      { uni: 'LPU (Rs 1,61,000)', savings: 'Up to Rs 5,000 via LPU2026-5K (standard tier)' },
    ],
  },
  {
    slug: 'amrita-online-mba-discount-coupon-2026',
    universityId: 'amrita-vishwa-vidyapeetham-online',
    universityName: 'Amrita Vishwa Vidyapeetham Online',
    shortName: 'Amrita',
    tier: 'standard',
    totalFee: 'Rs 1,76,000-2,60,000',
    totalFeeNum: 176000,
    maxSavings: 'Rs 5,000',
    maxSavingsNum: 5000,
    finalFee: 'Rs 1,71,000+',
    naac: 'A++',
    nirf: '#8 University',
    couponCode: 'AMR2026-5K',
    couponDiscount: 'Up to Rs 5,000 edifyedu.in enrollment bonus (Tue/Sat)',
    blogSlug: 'top-online-mba-india-2026',
    officialUrl: 'amritaonline.com',
    discounts: [
      { type: 'Defence scholarship', eligibility: 'Serving/retired defence', saving: '20% fee waiver', howToApply: 'Submit defence ID' },
      { type: 'Female scholarship', eligibility: 'Female applicants', saving: '15% fee waiver', howToApply: 'Automatic' },
      { type: 'SAARC scholarship', eligibility: 'SAARC country nationals', saving: '40% fee waiver', howToApply: 'Submit nationality proof' },
      { type: 'Doctors scholarship', eligibility: 'Medical professionals', saving: '15% fee waiver', howToApply: 'Submit medical registration' },
      { type: 'edifyedu.in enrollment bonus', eligibility: 'All students via edifyedu.in', saving: 'Up to Rs 5,000 (Tue/Sat max window, Rs 4,000 other days)', howToApply: 'Mention code AMR2026-5K during advisor call' },
    ],
    stackExample: 'Amrita offers 8 scholarship categories. Female candidates save 15% automatically. Defence personnel save 20%. SAARC nationals save 40%. Combined with the edifyedu.in bonus (up to Rs 5,000 on Tue/Sat), savings can be substantial.',
    emiCompatible: 'Yes. Amrita offers EMI on the reduced fee.',
    exclusions: ['Specialisation-specific pricing varies (General Mgmt Rs 1,76,000 vs IFA Rs 2,60,000)', 'Cannot combine with other third-party offers'],
    faqs: [
      { q: 'What is the Amrita online MBA enrollment bonus code?', a: 'AMR2026-5K (standard tier). Up to Rs 5,000 on Tuesday and Saturday in IST.' },
      { q: 'Does Amrita offer per-specialisation pricing?', a: 'Yes. General Management is Rs 1,76,000. Analytics/FinTech is Rs 2,44,000. International Finance is Rs 2,60,000.' },
      { q: 'Does Amrita have Grant Thornton co-branding?', a: 'Yes. Selected specialisations (Analytics, FinTech, ESG) are co-branded with Grant Thornton.' },
      { q: 'Is Amrita NIRF #8?', a: 'Yes. Amrita holds NIRF #8 in the University category for 2025.' },
    ],
    peerComparisons: [
      { uni: 'NMIMS (Rs 2,20,000)', savings: 'Up to Rs 5,000 via NMIMS2026-5K (standard tier)' },
      { uni: 'JAIN (Rs 1,96,000)', savings: 'Up to Rs 5,000 via JAIN2026-5K (standard tier)' },
    ],
  },
]

export function getCouponPage(slug: string): CouponPageData | undefined {
  return COUPON_PAGES.find(p => p.slug === slug)
}

export const COUPON_PAGE_SLUGS = COUPON_PAGES.map(p => p.slug)
