// lib/data.ts — Auto-generated by Edify CMS sync on 2026-03-25
// DO NOT edit manually — update via Google Sheets → /admin/cms → Sync to Live
// ─────────────────────────────────────────────────────────────────────────────

export type Program = 'MBA' | 'MCA' | 'BBA' | 'BCA' | 'BA' | 'B.Com' | 'M.Com' | 'MA' | 'MSc' | 'BSc' | 'MBA (WX)'

export interface ProgramDetail {
  specs: string[]; fees: string; duration: string; roles: string[]
  avgSalary: string; topCompanies: string[]
  internshipType: string; careerOutcome: string
}

export interface University {
  id: string; name: string; abbr: string; city: string; state: string
  region: 'North' | 'South' | 'West' | 'East' | 'Central'
  nirf: number; nirfMgt?: number; nirfCategory?: string; qsRank?: string
  naac: string; naacScore?: string; ugc: boolean; approvals: string[]
  examMode: string; govtRecognised: boolean; psuEligible: boolean
  feeMin: number; feeMax: number; emiFrom: number
  eligibility: string; eligibilityPct: number
  highlight: string; tagline: string; description: string
  forWho: string[]; notFor: string[]
  programs: Program[]; programDetails: Partial<Record<Program, ProgramDetail>>
  color: string; logo?: string
}

export const PROGRAM_META: Record<string, { label: string; desc: string; icon?: string }> = {
  'MBA':      { label: 'Online MBA',    desc: 'Master of Business Administration', icon: '💼' },
  'MCA':      { label: 'Online MCA',    desc: 'Master of Computer Applications',   icon: '💻' },
  'BBA':      { label: 'Online BBA',    desc: 'Bachelor of Business Administration', icon: '📊' },
  'BCA':      { label: 'Online BCA',    desc: 'Bachelor of Computer Applications', icon: '🖥️' },
  'B.Com':    { label: 'Online B.Com',  desc: 'Bachelor of Commerce',              icon: '📒' },
  'M.Com':    { label: 'Online M.Com',  desc: 'Master of Commerce',                icon: '📈' },
  'BA':       { label: 'Online BA',     desc: 'Bachelor of Arts',                  icon: '🎓' },
  'MA':       { label: 'Online MA',     desc: 'Master of Arts',                    icon: '📚' },
  'MSc':      { label: 'Online M.Sc',   desc: 'Master of Science',                 icon: '🔬' },
  'BSc':      { label: 'Online B.Sc',   desc: 'Bachelor of Science',               icon: '⚗️' },
  'MBA (WX)': { label: 'Executive MBA', desc: 'Executive MBA (Work Integrated)',    icon: '🏛️' },
}

export function formatFee(n: number): string {
  if (n >= 100000) return `₹${(n/100000).toFixed(1)}L`
  return `₹${(n/1000).toFixed(0)}K`
}

export function getUniversityById(id: string) { return UNIVERSITIES.find(u => u.id === id) }
export function getUniversitiesByProgram(p: string) { return UNIVERSITIES.filter(u => u.programs.includes(p as Program)) }
export function getAllPrograms(): Program[] { return [...new Set(UNIVERSITIES.flatMap(u => u.programs))] }
export function getAllSpecs(prog: string): string[] { return [...new Set(UNIVERSITIES.flatMap(u => u.programDetails[prog as Program]?.specs ?? []))] }
export function getUniversitiesBySpec(prog: string, spec: string) { return UNIVERSITIES.filter(u => u.programDetails[prog as Program]?.specs?.includes(spec)) }
export function getPrograms(uid: string) { return UNIVERSITIES.find(u => u.id === uid)?.programs ?? [] }
export function getFees(uid: string, prog: Program) { const pd = UNIVERSITIES.find(u => u.id === uid)?.programDetails[prog]; return pd?.fees ?? '' }
export function getSpecs(uid: string, prog: Program) { return UNIVERSITIES.find(u => u.id === uid)?.programDetails[prog]?.specs ?? [] }

export const UNIVERSITIES: University[] = [
  {
    id: 'amity',
    name: 'Amity University Online',
    abbr: 'AUO',
    city: 'Noida',
    state: 'Uttar Pradesh',
    region: 'North',
    nirf: 51,
    nirfCategory: '',
    qsRank: '',
    naac: 'A+',
    ugc: true,
    approvals: ['UGC DEB', 'NAAC A+'],
    examMode: 'Online',
    govtRecognised: true,
    psuEligible: true,
    feeMin: 60000,
    feeMax: 200000,
    emiFrom: 2500,
    eligibility: '50% in graduation',
    eligibilityPct: 50,
    highlight: 'NAAC A+ · UGC DEB approved',
    tagline: 'Learn without limits',
    description: 'Quality education',
    forWho: ['Working professionals'],
    notFor: ['Those needing campus placements'],
    programs: ['MBA', 'MCA', 'BBA', 'BCA', 'B.Com'],
    programDetails: {
      'MBA': {
        specs: ['Finance', 'Marketing', 'HR'],
        fees: '₹1L–₹2L',
        duration: '2 years',
        roles: ['Business Analyst', 'Manager'],
        avgSalary: '₹6–12 LPA',
        topCompanies: ['TCS', 'Infosys'],
        internshipType: 'Live projects',
        careerOutcome: 'Qualify for management roles',
      },
      'MCA': {
        specs: [],
        fees: '',
        duration: '',
        roles: [],
        avgSalary: '',
        topCompanies: [],
        internshipType: '',
        careerOutcome: '',
      },
      'BBA': {
        specs: [],
        fees: '',
        duration: '',
        roles: [],
        avgSalary: '',
        topCompanies: [],
        internshipType: '',
        careerOutcome: '',
      },
      'BCA': {
        specs: [],
        fees: '',
        duration: '',
        roles: [],
        avgSalary: '',
        topCompanies: [],
        internshipType: '',
        careerOutcome: '',
      },
      'B.Com': {
        specs: [],
        fees: '',
        duration: '',
        roles: [],
        avgSalary: '',
        topCompanies: [],
        internshipType: '',
        careerOutcome: '',
      }
    },
    color: '#1C6BF4',
  }
]
