// lib/data-slim.ts — Lightweight university summaries for client bundles
// Only includes fields needed for cards, search, and navigation.
// ~15KB vs 420KB for the full lib/data.ts
// For full university objects, use lib/data-server.ts (server-only) or /api/universities

export interface UniSlim {
  id: string
  name: string
  logo?: string
  abbr: string
  nirf: number
  nirfMgt?: number
  nirfEng?: number
  naac: string
  feeMin: number
  feeMax: number
  emiFrom: number
  highlight: string
  programs: string[]
  color: string
  region: string
  city: string
  psuEligible: boolean
  programDetails?: Record<string, any>
  approvals?: string[]
  qsRank?: number
}

export const UNIS_SLIM: UniSlim[] = [
  { id: 'jain-university-online', logo: '/logos/university_logos/jain_university-logo.svg', name:'JAIN (Deemed-to-be University) Online', abbr:'JUJOD', nirf: 62, naac: 'A++', feeMin:220000, feeMax:220000, emiFrom:2500, highlight: 'NIRF #62 · NAAC A++ · WES Approved', programs:['MBA', 'MCA', 'BBA', 'BCA', 'M.Com'], color:'#1B4FBE', region:'South', city:'Bangalore',qsRank:62, psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #62', 'AICTE', 'WES Recognised'], nirfMgt: 73},
  { id: 'amity-university-online', logo: '/logos/university_logos/amity-online-university-logo_2.svg', name:'Amity University Online', abbr:'AUO', nirf: 22, naac: 'A+', feeMin:199000, feeMax:199000, emiFrom:2500, highlight: 'NAAC A+', qsRank: 45,
    programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com'], color:'#2563EB', region:'North', city:'Noida', psuEligible:true, approvals: ['UGC DEB', 'NAAC A+', 'AICTE', 'WES Recognised'], nirfMgt: 49, nirfEng: 37},
  { id: 'chandigarh-university-online', logo: '/logos/university_logos/cu-online.svg', name:'Chandigarh University Online', abbr:'CUO', nirf: 19, nirfMgt: 32, nirfEng: 31, naac: 'A+', feeMin:165000, feeMax:165000, emiFrom:2500, highlight: 'NIRF #19 · NAAC A+ · QS Ranked', programs:['MBA', 'MCA', 'BBA', 'BCA', 'MSc'], color:'#0E8A78', region:'North', city:'Chandigarh', psuEligible:true, approvals: ['UGC DEB', 'NAAC A+', 'NIRF #19', 'AICTE', 'QS Ranked']},
  { id: 'srm-institute-science-technology-online', name:'SRM Institute of Science and Technology Online', abbr:'SRMIST', nirf: 11, nirfEng: 14, naac: 'A++', feeMin:60000, feeMax:189000, emiFrom:2500, highlight: 'NIRF #11 · NAAC A++', programs:['MBA', 'MCA', 'M.Com', 'BBA', 'BCA'], color:'#C0392B', region:'South', city:'Chennai', psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #11', 'AICTE']},
  { id: 'lovely-professional-university-online', logo: '/logos/university_logos/lpu-logo.svg', name:'Lovely Professional University Online', abbr:'LPUO', nirf: 31, naac: 'A++', feeMin:146240, feeMax:146240, emiFrom:2500, highlight: 'NAAC A++ · WES Approved', qsRank: 51,
    programs:['MBA', 'MCA', 'BBA', 'BCA', 'BA', 'M.Com', 'MSc'], color:'#1B4FBE', region:'North', city:'Phagwara', psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'AICTE', 'WES Recognised', 'QS Ranked'], nirfMgt: 44, nirfEng: 48},
  { id: 'dayananda-sagar-university-online', name:'Dayananda Sagar University Online', abbr:'DSUO', nirf: 43, naac: 'A', feeMin:120000, feeMax:120000, emiFrom:2500, highlight: 'NIRF #43 · NAAC A · WES Approved', programs:['MBA', 'BCA', 'B.Com'], color:'#0891B2', region:'Central', city:'Central India',qsRank:43, psuEligible:true },
  { id: 'dy-patil-university-online', logo: '/logos/university_logos/dpu-online.svg', name:'D.Y. Patil University, Navi Mumbai Online', abbr:'DPUNM', nirf:999, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A · WES Approved', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#0891B2', region:'West', city:'West India', psuEligible:true },
  { id: 'upes-online', logo: '/logos/university_logos/upes-logo-black.svg', name:'University of Petroleum & Energy Studies (UPES) Online', abbr:'UOPES', nirf: 45, naac: 'A', feeMin:175000, feeMax:175000, emiFrom:2500, highlight: 'NIRF #45 · NAAC A · WES Approved', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#0891B2', region:'North', city:'North India',qsRank: 45, psuEligible:true, nirfMgt: 36, nirfEng: 43},
  { id: 'parul-university-online', logo: '/logos/university_logos/online_parul_university_logo.svg', name:'Parul University Online', abbr:'PUO', nirf: 0, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com', 'BA', 'M.Com'], color:'#1B4FBE', region:'West', city:'West India', psuEligible:true },
  { id: 'amrita-vishwa-vidyapeetham-online', logo: '/logos/university_logos/amrita-online-logo.svg', name:'Amrita Vishwa Vidyapeetham Online', abbr:'AVVA', nirf: 8, naac: 'A++', feeMin:170000, feeMax:170000, emiFrom:2500, highlight: 'NIRF #7 · NAAC A++ · WES Approved', programs:['MBA'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:7, psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #7', 'AICTE', 'WES Recognised'], nirfMgt: 26, nirfEng: 23},
  { id: 'mangalayatan-university-online', name:'Mangalayatan University Online', abbr:'MUO', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'MA', 'M.Com', 'MSc'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id:'shoolini-university-online', logo: '/logos/university_logos/shoolini-university-online-logo.svg', name:'Shoolini University Online', abbr:'SUSO', nirf:999, naac:'A+', feeMin:110000, feeMax:110000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com', 'MSc'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id: 'manipal-university-jaipur-online', logo: '/logos/university_logos/muj-logo.svg', name:'Manipal University Jaipur (MUJ) Online', abbr:'MUJOM', nirf: 58, naac: 'A+', feeMin:160000, feeMax:160000, emiFrom:2500, highlight: 'NIRF #58 · NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com', 'M.Com', 'MSc'], color:'#2563EB', region:'North', city:'North India',qsRank:58, psuEligible:true, approvals: ['UGC DEB', 'NAAC A+', 'NIRF #58', 'AICTE', 'WES Recognised'], nirfMgt: 81},
  { id: 'galgotias-university-online', name:'Galgotias University Online', abbr:'GUO', nirf: 101, naac: 'A+', feeMin:76200, feeMax:76200, emiFrom:2500, highlight: 'NIRF #36 · NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'M.Com'], color:'#2563EB', region:'North', city:'North India',qsRank:36, psuEligible:true, nirfMgt: 101},
  { id:'sikkim-manipal-university-online', logo: '/logos/university_logos/sikkim-manipal-university-logo.svg', name:'Sikkim Manipal University Online', abbr:'SMUOM', nirf:999, naac:'A+', feeMin:110000, feeMax:110000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'MCA', 'B.Com', 'BA', 'M.Com'], color:'#2563EB', region:'East', city:'East India', psuEligible:true },
  { id: 'symbiosis-university-online', logo: '/logos/university_logos/SSODL.svg', name:'Symbiosis School for Online and Digital Learning (SSODL), Pune Online', abbr:'SSODL', nirf: 24, naac: 'A++', feeMin:315000, feeMax:315000, emiFrom:2500, highlight: 'NIRF #11 · NAAC A++', programs:['MBA', 'BBA', 'BCA', 'MSc', 'BSc'], color:'#1B4FBE', region:'West', city:'West India',qsRank:11, psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #11', 'AICTE', 'WES Recognised'], nirfMgt: 11, nirfEng: 46},
  { id:'chitkara-university-online', logo: '/logos/university_logos/chitkara-university-online.svg', name:'Chitkara University Online', abbr:'CUCDO', nirf:54, naac:'A+', feeMin:200000, feeMax:200000, emiFrom:2500, highlight:'NIRF #54 · NAAC A+', programs:['MBA', 'BBA', 'BCA', 'B.Com'], color:'#2563EB', region:'North', city:'North India',qsRank:54, psuEligible:true },
  { id: 'yenepoya-university-online', name:'Yenepoya (Deemed to be University) Online', abbr:'YUO', nirf: 85, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #85 · NAAC A+', programs:['MBA', 'B.Com'], color:'#2563EB', region:'South', city:'South India',qsRank:85, psuEligible:true },
  { id:'sharda-university-online', name:'Sharda University Online', abbr:'SUO', nirf:87, naac:'A+', feeMin:150000, feeMax:150000, emiFrom:2500, highlight:'NIRF #87 · NAAC A+', programs:['MBA', 'BCA', 'M.Com'], color:'#2563EB', region:'North', city:'North India',qsRank:87, psuEligible:true },
  { id:'vignan-university-online', name:"Vignan's Foundation for Science, Technology & Research Online", abbr:'VFSTR', nirf:75, naac:'A+', feeMin:110000, feeMax:110000, emiFrom:2500, highlight:'NIRF #75 · NAAC A+ · WES Approved', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#2563EB', region:'South', city:'South India',qsRank:151, psuEligible:true, approvals:['UGC DEB','AICTE','QS'] },
  { id:'manonmaniam-sundaranar-university-online', name:'Manonmaniam Sundaranar University Online', abbr:'MSUO', nirf:151, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #151 · NAAC A', programs:['MBA', 'MA'], color:'#0891B2', region:'South', city:'South India', psuEligible:true },
  { id: 'nmims-online', logo: '/logos/university_logos/nmims-online-logo.svg', name:'NMIMS (Narsee Monjee Institute of Management Studies) Online', abbr:'NMIMS', nirf: 52, naac: 'A++', feeMin:220000, feeMax:220000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA', 'BBA', 'B.Com'], color:'#1B4FBE', region:'West', city:'West India',qsRank:14, psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'AICTE', 'WES Recognised'], nirfMgt: 24, nirfEng: 55},
  { id: 'manipal-academy-higher-education-online', logo: '/logos/university_logos/mahe-manipal-online-logo.svg', name:'Manipal Academy of Higher Education (MAHE) Online', abbr:'MAHEO', nirf: 3, naac: 'A++', feeMin:280000, feeMax:280000, emiFrom:2500, highlight: 'NIRF #14 · NAAC A++', programs:['MBA', 'MCA', 'BBA', 'B.Com', 'MSc'], color:'#1B4FBE', region:'South', city:'South India',qsRank: 32, psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #14', 'AICTE', 'WES Recognised'] },
  { id: 'kl-university-online', logo: '/logos/university_logos/kl-university-online-logo.svg', name:'Koneru Lakshmaiah Education Foundation (KL University) Online', abbr:'KLEFU', nirf: 26, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #46 · NAAC A++', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, approvals: ['UGC DEB', 'NAAC A++', 'NIRF #46', 'AICTE', 'WES Recognised'], nirfMgt: 70, nirfEng: 35},
  { id:'chandigarh-university-online', logo: '/logos/university_logos/cu-online.svg', name:'Chandigarh University Online', abbr:'CUO', nirf:999, naac:'A+', feeMin:165000, feeMax:165000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'MSc'], color:'#2563EB', region:'North', city:'North India',qsRank:100, psuEligible:true, approvals:['UGC DEB','AICTE','QS'] },
  { id: 'vtu-online', name:'Visvesvaraya Technological University (VTU) Online', abbr:'VTU', nirf: 100, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #100 · NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#2563EB', region:'Central', city:'Central India',qsRank:101, psuEligible:true },
  { id:'integral-university-online', name:'Integral University Online', abbr:'IUO', nirf:101, naac:'A+', feeMin:110000, feeMax:110000, emiFrom:2500, highlight:'NIRF #101 · NAAC A+', programs:['MBA', 'BCA', 'B.Com'], color:'#2563EB', region:'North', city:'North India',qsRank:71, psuEligible:true },
  { id:'manav-rachna-online', logo: '/logos/university_logos/manav-rachna-university-logo.svg', name:'Manav Rachna Online', abbr:'MRCDO', nirf:71, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #71 · NAAC A++', programs:['MBA', 'M.Com'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:68, psuEligible:true, approvals:['UGC DEB','AICTE','QS'] },
  { id: 'karnataka-state-open-university-online', name:'Karnataka State Open University (KSOU) Online', abbr:'KSOU', nirf: 68, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #68 · NAAC A++', programs:['MBA', 'B.Com'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:36, psuEligible:true },
  { id:'bharathidasan-university-online', name:'Bharathidasan University Online', abbr:'BUO', nirf:36, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #36 · NAAC A+', programs:['MBA', 'BBA', 'BA'], color:'#2563EB', region:'South', city:'South India',qsRank:101, psuEligible:true },
  { id: 'hindustan-institute-technology-online', name:'Hindustan Institute of Technology and Science (CODE) Online', abbr:'HITS', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #101 · NAAC A+', programs:['MBA', 'BCA', 'B.Com'], color:'#2563EB', region:'South', city:'South India',qsRank:107, psuEligible:true, nirfMgt: 101, nirfEng: 75},
  { id: 'guru-ghasidas-vishwavidyalaya-online', name:'Guru Ghasidas Vishwavidyalaya (GGU) Online', abbr:'GGV', nirf: 107, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #107 · NAAC A++', programs:['MBA', 'B.Com', 'MA', 'M.Com'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:3, psuEligible:true },
  { id: 'dr-babasaheb-ambedkar-open-university-online', name:'Dr. Babasaheb Ambedkar Open University Online', abbr:'DBAOU', nirf: 3, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #3 · NAAC A++', programs:['MBA', 'MCA', 'BCA', 'B.Com', 'MA'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:100, psuEligible:true },
  { id: 'marwadi-university-online', name:'Marwadi University Online', abbr:'MU', nirf: 100, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #100 · NAAC A+', programs:['MBA', 'B.Com'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id: 'pp-savani-university-online', name:'P P Savani University Online', abbr:'PPSU', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA', 'BBA', 'M.Com'], color:'#2563EB', region:'Central', city:'Central India',qsRank:44, psuEligible:true },
  { id: 'university-of-mysore-online', name:'University of Mysore Online', abbr:'UM', nirf: 71, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #44 · NAAC A', programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com', 'M.Com'], color:'#0891B2', region:'Central', city:'Central India',qsRank:9, psuEligible:true },
  { id:'aligarh-muslim-university-online', name:'Aligarh Muslim University Online', abbr:'AMUD', nirf:9, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #9 · NAAC A+', programs:['MBA', 'BA'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id:'gujarat-university-online', name:'Gujarat University Online', abbr:'GUDO', nirf:74, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #74 · NAAC A+', programs:['B.Com', 'BA', 'M.Com'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id: 'charusat-university-online', name:'CHARUSAT (Charotar University of Science and Online', abbr:'CUS', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA', 'MCA', 'BCA'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id:'gls-university-online', name:'GLS University Online', abbr:'GUDO', nirf:999, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'BBA', 'BCA', 'B.Com'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id: 'maharishi-markandeshwar-university-online', name:'Maharishi Markandeshwar (Deemed to be University) Online', abbr:'MMU', nirf: 85, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #71 · NAAC A++', programs:['MBA', 'MCA', 'BCA'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:74, psuEligible:true },
  { id: 'mizoram-university-online', name:'Mizoram University (MZU) Online', abbr:'MU', nirf: 82, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA'], color:'#0891B2', region:'East', city:'East India', psuEligible:true },
  { id:'vivekananda-global-university-online', logo: '/logos/university_logos/vivekananda-global-university-logo.svg', name:'Vivekananda Global University Online', abbr:'VGUO', nirf:999, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'BBA', 'BCA', 'BA', 'MSc'], color:'#2563EB', region:'North', city:'North India',qsRank:71, psuEligible:true },
  { id: 'dr-mgr-educational-research-institute-online', name:'Dr. MGR Educational and Research Institute Online', abbr:'DMERI', nirf: 0, naac: 'A+', feeMin:141000, feeMax:141000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA'], color:'#2563EB', region:'South', city:'South India', psuEligible:true },
  { id:'uttaranchal-university-online', logo: '/logos/university_logos/uttaranchal-online-university-logo_1.svg', name:'Uttaranchal University Online', abbr:'UUUDO', nirf:999, naac:'A+', feeMin:110000, feeMax:110000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'BA'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id: 'andhra-university-online', logo: '/logos/university_logos/andhra-university-online-logo.svg', name:'Andhra University Online', abbr:'AUOA', nirf: 23, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #23 · NAAC A++', programs:['MBA', 'MCA', 'MA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id:'sgt-university-online', name:'SGT University Online', abbr:'SUDO', nirf:101, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #101 · NAAC A+', programs:['MBA', 'B.Com'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id:'central-university-himachal-pradesh-online', name:'Central University of Himachal Pradesh Online', abbr:'CUHP', nirf:151, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #151 · NAAC A+', programs:['MBA', 'MA'], color:'#2563EB', region:'Central', city:'Central India',qsRank:23, psuEligible:true },
  { id: 'mahatma-gandhi-university-online', name:'Mahatma Gandhi University Online', abbr:'MGU', nirf: 43, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA'], color:'#0891B2', region:'South', city:'South India',qsRank:101, psuEligible:true },
  { id: 'vit-university-online', name:'Vellore Institute of Science and Technology (VIT Online', abbr:'VIST', nirf: 14, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #11 · NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, nirfEng: 16},
  { id: 'karunya-university-online', name:'Karunya Institute of Technology and Sciences (KCODE) Online', abbr:'KITS', nirf: 0, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA', 'B.Com'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, nirfEng: 73},
  { id: 'kurukshetra-university-online', logo: '/logos/university_logos/kurukshetra-university-logo.svg', name:'Kurukshetra University Online', abbr:'KUO', nirf: 0, naac: 'A++', feeMin:110000, feeMax:110000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA', 'MCA', 'BBA', 'B.Com', 'M.Com'], color:'#1B4FBE', region:'North', city:'North India',qsRank:11, psuEligible:true },
  { id: 'sastra-university-online', name:'SASTRA Deemed University Online', abbr:'SDUO', nirf: 29, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #29 · NAAC A++', programs:['MBA', 'MCA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, nirfEng: 40},
  { id: 'dr-dy-patil-vidyapeeth-online', name:'Dr. D.Y. Patil Vidyapeeth, Pune – Centre for Online Learning (DPU-COL) Online', abbr:'DDPVP', nirf: 41, naac: 'A++', feeMin:189400, feeMax:189400, emiFrom:2500, highlight: 'NIRF #47 · NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'West', city:'West India', psuEligible:true },
  { id: 'jamia-millia-islamia-online', name:'Jamia Millia Islamia (JMI) Online', abbr:'JMI', nirf: 4, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:29, psuEligible:true, nirfMgt: 28, nirfEng: 24},
  { id: 'christ-university-online', name:'Christ (Deemed to be University) Online', abbr:'CUO', nirf: 63, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #60 · NAAC A++', programs:['MBA', 'B.Com'], color:'#1B4FBE', region:'Central', city:'Central India', psuEligible:true, nirfMgt: 57},
  { id: 'shobhit-university-online', name:'Shobhit Institute of Engineering & Technology (Shobhit Online', abbr:'SIET', nirf: 0, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id: 'bharati-vidyapeeth-university-online', name:'Bharati Vidyapeeth (Deemed to be University) Online', abbr:'BVUO', nirf: 59, naac: 'A+', feeMin:160000, feeMax:160000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#2563EB', region:'West', city:'West India', psuEligible:true },
  { id:'assam-don-bosco-university-online', name:'Assam Don Bosco University Online', abbr:'ADBUC', nirf:151, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #151 · NAAC A', programs:['MBA', 'MCA', 'BBA', 'BCA', 'MA'], color:'#0891B2', region:'East', city:'East India',qsRank:47, psuEligible:true },
  { id:'university-of-lucknow-online', name: "University of Lucknow Online", abbr:'ULCDO', nirf:999, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A++', programs:['MBA', 'BBA', 'B.Com', 'M.Com'], color:'#1B4FBE', region:'North', city:'North India', psuEligible:true },
  { id: 'jss-university-online', name:'JSS Academy of Higher Education & Research (JSS AHER) Online', abbr:'JAHER', nirf: 21, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #21 · NAAC A++', programs:['MBA', 'BBA'], color:'#1B4FBE', region:'Central', city:'Central India',qsRank:60, psuEligible:true },
  { id: 'alliance-university-online', logo: '/logos/university_logos/alliance-university-logo.svg', name:'Alliance University Online', abbr:'AU', nirf: 0, naac: 'A', feeMin:175000, feeMax:175000, emiFrom:2500, highlight: 'NIRF #25 · NAAC A', programs:['MBA'], color:'#0891B2', region:'Central', city:'Central India', psuEligible:true, approvals: ['UGC DEB', 'NAAC A', 'NIRF #25', 'AICTE', 'WES Recognised'], nirfMgt: 71},
  { id:'desh-bhagat-university-online', name:'Desh Bhagat University Online', abbr:'DBUO', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['MBA', 'BBA', 'B.Com'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id: 'ganpat-university-online', name:'Ganpat University Online', abbr:'GU', nirf: 0, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA', 'MCA', 'BBA'], color:'#0891B2', region:'West', city:'West India',qsRank:151, psuEligible:true },
  { id: 'amet-university-online', name:'AMET University (Academy of Maritime Education and Online', abbr:'AUME', nirf: 0, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA', 'BBA', 'B.Com'], color:'#0891B2', region:'Central', city:'Central India', psuEligible:true },
  { id:'guru-nanak-dev-university-online', name:'Guru Nanak Dev University Online', abbr:'GNDUO', nirf:999, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A++', programs:['MBA', 'MCA', 'M.Com'], color:'#1B4FBE', region:'North', city:'North India',qsRank:21, psuEligible:true },
  { id: 'jaypee-university-online', logo: '/logos/university_logos/jaypee-institute-of-information-technology-logo.svg', name:'Jaypee Institute of Information Technology Online', abbr:'JIITO', nirf: 0, naac: 'A', feeMin:150000, feeMax:150000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA', 'BBA'], color:'#0891B2', region:'North', city:'North India',qsRank:25, psuEligible:true, nirfEng: 83},
  { id:'savitribai-phule-pune-university-online', name:'Savitribai Phule Pune University (SPPU) Online', abbr:'SPPUC', nirf:999, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A+', programs:['BBA', 'BCA'], color:'#2563EB', region:'West', city:'West India', psuEligible:true },
  { id: 'srm-university-sikkim-online', name:'SRM University Sikkim Online', abbr:'SRMUS', nirf: 0, naac: 'A+', feeMin:117000, feeMax:170000, emiFrom:3250, highlight: 'NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA'], color:'#C0392B', region:'East', city:'East India', psuEligible:true },
  { id: 'sathyabama-university-online', name:'Sathyabama Institute of Science and Technology (Centre Online', abbr:'SIST', nirf: 53, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #53 · NAAC A++', programs:['MBA', 'MSc'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, nirfEng: 53},
  { id:'vit-vellore-online', name:'Vellore Institute of Technology Online', abbr:'VITO', nirf:11, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #11 · NAAC A++', programs:['MCA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id: 'karunya-kcode-online', name:'Karunya Institute of Technology and Sciences (KCODE Online', abbr:'KITS', nirf: 0, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA', 'B.Com'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id:'anna-university-online', name:'Anna University Online', abbr:'AUDE', nirf:13, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #13 · NAAC A++', programs:['MBA', 'MCA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id: 'vels-university-online', name:'Vels Institute of Science, Technology & Advanced Online', abbr:'VISTA', nirf: 101, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #101 · NAAC A', programs:['MBA', 'BBA'], color:'#0891B2', region:'Central', city:'Central India', psuEligible:true },
  { id:'northcap-university-online', name:'The NorthCap University Online', abbr:'TNUO', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['BBA', 'B.Com'], color:'#0891B2', region:'North', city:'North India',qsRank:53, psuEligible:true },
  { id: 'noida-international-university-online', logo: '/logos/university_logos/noida-international-university.svg', name:'Noida International University Online', abbr:'NIUO', nirf: 0, naac: 'A', feeMin:110000, feeMax:110000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA', 'BBA'], color:'#0891B2', region:'North', city:'North India',qsRank:11, psuEligible:true },
  { id: 'iift-online', name:'Indian Institute of Foreign Trade (IIFT) Online', abbr:'IIFT', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #15 · NAAC A+', programs:['MBA'], color:'#2563EB', region:'North', city:'North India', psuEligible:true, nirfMgt: 17},
  { id: 'gujarat-technological-university-online', name:'Gujarat Technological University (GTU) Online', abbr:'GTU', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A+', programs:['MBA'], color:'#2563EB', region:'Central', city:'Central India',qsRank:13, psuEligible:true },
  { id: 'bits-pilani-online', name:'Birla Institute of Technology (BIT) Mesra Online', abbr:'BITM', nirf: 92, naac: 'A', feeMin:178000, feeMax:178000, emiFrom:2500, highlight: 'NIRF #77 · NAAC A', programs:['MBA'], color:'#0891B2', region:'Central', city:'Central India',qsRank:101, psuEligible:true, nirfMgt: 97, nirfEng: 54},
  { id:'alvas-college-online', name:"Alva's College - ACU Online", abbr:'ACAO', nirf:999, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A+', programs:['MBA'], color:'#2563EB', region:'Central', city:'Central India', psuEligible:true },
  { id: 'datta-meghe-university-online', name:'Datta Meghe Institute of Higher Education & Research Online', abbr:'DMIHE', nirf: 49, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'West', city:'West India', psuEligible:true },
  { id: 'kiit-university-online', name:'KIIT Deemed to be University Online', abbr:'KDU', nirf: 17, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A++', programs:['M.Com'], color:'#1B4FBE', region:'East', city:'East India', psuEligible:true, nirfMgt: 68, nirfEng: 36},
  { id: 'centurion-university-online', name:'Centurion University of Technology and Management Online', abbr:'CUTM', nirf: 151, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #151 · NAAC A+', programs:['MBA'], color:'#2563EB', region:'East', city:'East India', psuEligible:true },
  { id:'guru-kashi-university-online', name:'Guru Kashi University Online', abbr:'GKUO', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['MCA'], color:'#0891B2', region:'Central', city:'Central India', psuEligible:true },
  { id: 'jaipur-national-university-online', name:'Jaipur National University Online', abbr:'JNUJ', nirf: 0, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A+', programs:['BBA'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id: 'bs-abdur-rahman-university-online', name:'B.S. Abdur Rahman Crescent Institute of Science and Online', abbr:'BARCI', nirf: 102, naac: 'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #102 · NAAC A+', programs:['MBA'], color:'#2563EB', region:'South', city:'South India', psuEligible:true },
  { id:'srm-institute-science-technology-online', name:'SRM Institute of Science and Technology Online', abbr:'SRMIST', nirf:18, naac:'A++', feeMin:60000, feeMax:189000, emiFrom:2500, highlight:'NIRF #18 · NAAC A++', programs:['MBA', 'MCA', 'M.Com', 'BBA', 'BCA'], color:'#C0392B', region:'South', city:'South India', psuEligible:true },
  { id:'university-of-madras-online', name:'University of Madras Online', abbr:'UMDE', nirf:64, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #64 · NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id: 'kalasalingam-university-online', name:'Kalasalingam Academy of Research and Education (KARE) Online', abbr:'KARE', nirf: 28, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #35 · NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true, nirfEng: 33},
  { id:'alagappa-university-online', name:'Alagappa University Online', abbr:'AUOP', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['B.Com'], color:'#0891B2', region:'Central', city:'Central India', psuEligible:true },
  { id:'bharathiar-university-online', name:'Bharathiar University Online', abbr:'BUDE', nirf:44, naac:'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #44 · NAAC A++', programs:['BBA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id: 'sri-ramachandra-university-online', name:'Sri Ramachandra Institute of Higher Education and Online', abbr:'SRIHE', nirf: 60, naac: 'A++', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #57 · NAAC A++', programs:['BSc'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id:'icfai-university-online', name:'ICFAI Foundation for Higher Education Online', abbr:'IFHEO', nirf:39, naac:'A++', feeMin:120000, feeMax:120000, emiFrom:2500, highlight:'NIRF #39 · NAAC A++', programs:['MBA'], color:'#1B4FBE', region:'South', city:'South India', psuEligible:true },
  { id:'shiv-nadar-university-online', name:'Shiv Nadar University Online', abbr:'SNUE', nirf:62, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #62 · NAAC A', programs:['MBA'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id:'gla-university-online', name:'GLA University Online', abbr:'GUO', nirf:101, naac:'A+', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NIRF #101 · NAAC A+', programs:['MBA', 'MCA', 'BBA', 'BCA', 'B.Com'], color:'#2563EB', region:'North', city:'North India', psuEligible:true },
  { id: 'jagannath-university-online', name:'Jagan Nath University Online', abbr:'JNU', nirf: 0, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NAAC A', programs:['MBA'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id:'teerthanker-mahaveer-university-online', name:'Teerthanker Mahaveer University Online', abbr:'TMUO', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['MBA'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id:'subharti-university-online', name:'Swami Vivekanand Subharti University Online', abbr:'SVSUO', nirf:999, naac:'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight:'NAAC A', programs:['MBA'], color:'#0891B2', region:'North', city:'North India', psuEligible:true },
  { id: 'arka-jain-university-online', name:'ARKA JAIN University – JGI Online (arkajain.edu.in) Online', abbr:'AJUJO', nirf: 52, naac: 'A', feeMin:60000, feeMax:200000, emiFrom:2500, highlight: 'NIRF #52 · NAAC A', programs:['MBA'], color:'#0891B2', region:'East', city:'East India', psuEligible:true },
  { id: 'jawaharlal-nehru-university-online', name:'JAWAHARLAL NEHRU UNIVERSITY Online', abbr:'JNU', nirf: 2, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #2 · NAAC A++', programs:['MA'], color:'#6366f1', region:'North', city:'North India', psuEligible:true },
  { id: 'jamia-hamdard-online',
    logo: '/logos/university_logos/jamia-hamdard-online-logo.svg', name:'JAMIA HAMDARD Online', abbr:'JH', nirf: 47, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #8 · NAAC A+', programs:['B.Com', 'BBA', 'BCA', 'MA', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true, nirfMgt: 87},
  { id: 'kalinga-institute-industrial-technology-online', name:'KALINGA INSTITUTE OF INDUSTRIAL TECHNOLOGY Online', abbr:'KIOIT', nirf: 15, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #15 · NAAC A++', programs:['BA', 'B.Com', 'MA', 'M.Com'], color:'#1E3A5F', region:'East', city:'East India', psuEligible:true },
  { id: 'university-of-kerala-online', name:'UNIVERSITY OF KERALA Online', abbr:'UOK', nirf: 21, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #21 · NAAC A++', programs:['B.Com', 'BBA', 'M.Com', 'MBA'], color:'#1E3A5F', region:'South', city:'South India', psuEligible:true },
  { id: 'bits-pilani-work-integrated-online', name:'BITS Pilani Work Integrated Learning Programmes (WILP) Online', abbr:'BPWIL', nirf: 7, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #25 · NAAC A+', qsRank: 40,
    programs:['MBA'], color:'#86198f', region:'South', city:'South India', psuEligible:true, nirfEng: 11},
  { id: 'graphic-era-university-online', name:'GRAPHIC ERA UNIVERSITY Online', abbr:'GEU', nirf: 48, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #52 · NAAC A+', programs:['B.Com', 'BBA', 'BCA', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true, nirfMgt: 52, nirfEng: 56},
  { id: 'devi-ahilya-vishwavidyalaya-online', name:'DEVI AHILYA VISHWAVIDYALAYA Online', abbr:'DAV', nirf: 55, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #55 · NAAC A+', programs:['MA', 'MBA'], color:'#d97706', region:'Central', city:'Central India', psuEligible:true },
  { id: 'madurai-kamaraj-university-online', name:'MADURAI KAMARAJ UNIVERSITY Online', abbr:'MKU', nirf: 85, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #57 · NAAC A+', programs:['BA', 'B.Com', 'BBA', 'MA', 'M.Com'], color:'#1E3A5F', region:'South', city:'South India', psuEligible:true },
  { id: 'shanmugha-arts-science-technology-research-online', name:'SHANMUGHA ARTS, SCIENCE, TECHNOLOGY & RESEARCH ACADEMY Online', abbr:'SASTR', nirf: 57, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #57 · NAAC A+', programs:['B.Com', 'BBA', 'BCA', 'MA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'South', city:'South India', psuEligible:true },
  { id: 'university-of-mumbai-online', name:'UNIVERSITY OF MUMBAI Online', abbr:'UOM', nirf: 54, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #61 · NAAC A++', programs:['MA'], color:'#b45309', region:'West', city:'West India', psuEligible:true },
  { id: 'university-of-jammu-online', name:'UNIVERSITY OF JAMMU Online', abbr:'UOJ', nirf: 51, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #64 · NAAC A+', programs:['MA', 'M.Com'], color:'#0369a1', region:'South', city:'South India', psuEligible:true },
  { id: 'shivaji-university-online', name:'SHIVAJI UNIVERSITY Online', abbr:'SU', nirf: 65, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #65 · NAAC A++', programs:['M.Com', 'MBA'], color:'#15803d', region:'West', city:'West India', psuEligible:true },
  { id: 'banasthali-vidyapith-online', name:'BANASTHALI VIDYAPITH Online', abbr:'BV', nirf: 66, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #68 · NAAC A++', programs:['BA', 'B.Com', 'MA', 'M.Com', 'MBA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'guru-gobind-singh-indraprastha-university-online', name:'GURU GOBIND SINGH INDRAPRASTHA VISHWAVIDYALAYA Online', abbr:'GGSIV', nirf: 93, naac: 'A++', feeMin:90000, feeMax:200000, emiFrom:4500, highlight: 'NIRF #80 · NAAC A++', programs:['B.Com', 'BBA', 'MA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true, nirfMgt: 76},
  { id: 'bangalore-university-online', name:'BANGALORE UNIVERSITY Online', abbr:'BU', nirf: 65, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #81 · NAAC A', programs:['B.Com', 'MA', 'M.Com'], color:'#312e81', region:'South', city:'South India', psuEligible:true },
  { id: 'iiit-bangalore-online', name:'INTERNATIONAL INSTITUTE OF INFORMATION TECHNOLOGY Online', abbr:'IIOIT', nirf: 55, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #83 · NAAC A', programs:['MCA'], color:'#134e4a', region:'South', city:'South India', psuEligible:true, nirfEng: 38},
  { id: 'dayalbagh-educational-institute-online', name:'DAYAL BAGH EDUCATIONAL INSTITUTE Online', abbr:'DBEI', nirf: 0, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #95 · NAAC A+', programs:['BA', 'B.Com', 'BBA', 'MA', 'M.Com'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true, nirfEng: 70},
  { id: 'adichunchanagiri-university-online', name:'ADICHUNCHANAGIRI UNIVERSITY Online', abbr:'AU', nirf: 99, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['MBA'], color:'#059669', region:'South', city:'South India', psuEligible:true },
  { id: 'bharath-university-online', name:'BHARATH INSTITUTE OF HIGHER EDUCATION AND RESEARCH Online', abbr:'BIOHE', nirf: 76, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['BA', 'B.Com', 'M.Com'], color:'#1E3A5F', region:'South', city:'South India', psuEligible:true },
  { id: 'chhatrapati-shahu-ji-maharaj-university-online', name:'CHATRAPATI SHAHUJI MAHARAJ UNIVERSITY Online', abbr:'CSMU', nirf: 99, naac: 'B++', feeMin:50000, feeMax:120000, emiFrom:2500, highlight: 'NIRF #99 · NAAC B++', programs:['B.Com', 'BBA', 'BCA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'deen-dayal-upadhyay-gorakhpur-university-online', name:'DEEN DAYAL UPADHYAY GORAKHPUR UNIVERSITY Online', abbr:'DDUGU', nirf: 99, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['B.Com', 'BBA', 'MA', 'M.Com', 'MBA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'guru-jambheshwar-university-online', name:'GURU JAMBHESHWAR UNIVERSITY OF SCIENCE AND TECHNOLOGY Online', abbr:'GJUOS', nirf: 0, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['B.Com', 'MA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true, nirfMgt: 101},
  { id: 'maharshi-dayanand-university-online', name:'MAHARSHI DAYANAND UNIVERSITY Online', abbr:'MDU', nirf: 99, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['BA', 'MA', 'M.Com'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'mahatma-jyotiba-phule-rohilkhand-university-online', name:'MAHATMA JYOTIBA PHULE ROHILKHAND UNIVERSITY Online', abbr:'MJPRU', nirf: 99, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['BA', 'MA', 'M.Com'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'mats-university-online', name:'MATS UNIVERSITY Online', abbr:'MU', nirf: 99, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['B.Com', 'BBA', 'BCA', 'MBA', 'MCA'], color:'#1E3A5F', region:'Central', city:'Central India', psuEligible:true },
  { id: 'meenakshi-academy-higher-education-online', name:'MEENAKSHI ACADEMY OF HIGHER EDUCATION AND RESEARCH Online', abbr:'MAOHE', nirf: 99, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['BA', 'B.Com', 'MA'], color:'#1E3A5F', region:'South', city:'South India', psuEligible:true },
  { id: 'mody-university-online', name:'MODY UNIVERSITY OF SCIENCE AND TECHNOLOGY Online', abbr:'MUOSA', nirf: 99, naac: 'A+', feeMin:75000, feeMax:180000, emiFrom:4000, highlight: 'NIRF #99 · NAAC A+', programs:['BA', 'B.Com', 'BCA', 'MA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'sage-university-online', name:'SAGE UNIVERSITY Online', abbr:'SU', nirf: 99, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['BBA', 'BCA', 'MA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'Central', city:'Central India', psuEligible:true },
  { id: 'shree-guru-gobind-singh-tricentenary-university-online', name:'SHREE GURU GOBIND SINGH TRICENTENARY UNIVERSITY Online', abbr:'SGGST', nirf: 99, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['B.Com', 'BBA', 'BCA', 'MBA', 'MCA'], color:'#1E3A5F', region:'North', city:'North India', psuEligible:true },
  { id: 'shri-ramasamy-memorial-university-online', name:'SHRI RAMASAMY MEMORIAL UNIVERSITY Online', abbr:'SRMU', nirf: 99, naac: 'A', feeMin:60000, feeMax:150000, emiFrom:3000, highlight: 'NIRF #99 · NAAC A', programs:['B.Com', 'BBA', 'BCA', 'M.Com', 'MBA', 'MCA'], color:'#1E3A5F', region:'East', city:'East India', psuEligible:true }
]

export function getSlimById(id: string): UniSlim | undefined {
  return UNIS_SLIM.find(u => u.id === id)
}

export function getSlimByProgram(program: string): UniSlim[] {
  return UNIS_SLIM.filter(u => u.programs.includes(program))
}

export function formatFeeSlim(n: number): string {
  if (n >= 100000) return `₹${(n / 100000).toFixed(1)}L`
  if (n >= 1000)   return `₹${Math.round(n / 1000)}K`
  return `₹${n}`
}

export function getUniversitiesByProgram(program: string): UniSlim[] {
  return UNIS_SLIM.filter(u => u.programs.includes(program))
}

export function searchUnis(query: string): UniSlim[] {
  const q = query.toLowerCase()
  return UNIS_SLIM.filter(u =>
    u.name.toLowerCase().includes(q) ||
    u.abbr.toLowerCase().includes(q) ||
    u.naac.toLowerCase().includes(q)
  )
}

export const PREFERRED_UNI_IDS = [
  'amet-university-online', 'alliance-university-online', 'amity-university-online', 'amrita-vishwa-vidyapeetham-online',
  'arka-jain-university-online', 'assam-don-bosco-university-online', 'bharati-vidyapeeth-university-online',
  'bits-pilani-online', 'chandigarh-university-online', 'chitkara-university-online',
  'dayananda-sagar-university-online', 'dr-dy-patil-vidyapeeth-online', 'dr-mgr-educational-research-institute-online',
  'galgotias-university-online', 'icfai-university-online', 'iift-online', 'integral-university-online',
  'jain-university-online', 'jaypee-university-online', 'kurukshetra-university-online', 'lovely-professional-university-online', 'nmims-online',
  'noida-international-university-online', 'sharda-university-online', 'shoolini-university-online', 'symbiosis-university-online',
  'upes-online', 'uttaranchal-university-online', 'vignan-university-online',
  'manipal-university-jaipur-online', 'manipal-academy-higher-education-online', 'sikkim-manipal-university-online'
];

export function getSortRank(u: { id: string; nirf: number }): number {
  if (PREFERRED_UNI_IDS.includes(u.id)) {
    return -1000 + u.nirf;
  }
  return u.nirf;
}
