// Dictionary for enhanced specialization data (Roles, Companies, Skills, Projects)
// This is securely merged with the dynamic CMS spec content on the frontend.

export const IMPROVED_SPECS: Record<string, any> = {
  'agri operations management': {
    roles: ['Agribusiness Manager', 'Supply Chain Head (Agri)', 'Procurement Manager (Farm-to-Fork)', 'Agri-Tech Consultant', 'Operations Lead (Food Processing)'],
    topCompanies: ['ITC Agri Business', 'Ninjacart (Agri)', 'DeHaat', 'WayCool', 'Godrej Agrovet', 'Mahindra Agri', 'UPL', 'Cargill India', 'Haldirams'],
    skills: ['Agri-supply chain optimization', 'Cold chain logistics', 'Commodity trading basics', 'Quality control & precision farming tech', 'Procurement and vendor networking'],
    projectIdeas: ['Design a farm-to-fork supply chain model reducing post-harvest losses by 15%', 'Analyze cold storage logistics data for a fresh produce startup', 'Develop a strategic procurement plan for organic commodities'],
    internships: ['Agri-supply Chain Intern', 'Food Processing Operations Intern', 'Agri-Tech Startup Intern'],
    salaryRange: '₹6L – ₹16L per annum',
  },
  'finance': {
    roles: ['Financial Analyst', 'Investment Banker', 'Risk Manager', 'Portfolio Manager', 'Corporate Finance Executive'],
    topCompanies: ['Goldman Sachs', 'JP Morgan', 'HDFC Bank', 'ICICI Bank', 'Deloitte', 'KPMG', 'EY', 'PwC', 'Morgan Stanley'],
    skills: ['Financial modeling & valuation', 'Risk assessment', 'Advanced Excel & VBA', 'Corporate taxation', 'Equity research'],
    projectIdeas: ['Build a 3-statement financial model and DCF valuation for a publicly traded company', 'Analyze credit risk for a simulated portfolio of SME loans', 'Develop an algorithmic trading strategy backtest using historical data'],
    internships: ['Equity Research Intern', 'Financial Advisory Intern', 'Wealth Management Intern'],
    salaryRange: '₹7L – ₹22L per annum',
  },
  'human resource management': {
    roles: ['HR Business Partner (HRBP)', 'Talent Acquisition Manager', 'Compensation & Benefits Manager', 'L&D Manager', 'Organizational Development Lead'],
    topCompanies: ['TCS', 'Infosys', 'Accenture', 'Reliance Industries', 'Wipro', 'Amazon', 'Cognizant', 'IBM'],
    skills: ['HR analytics & reporting', 'Performance management systems', 'Talent acquisition strategy', 'Labor laws & compliance', 'Employee engagement profiling'],
    projectIdeas: ['Design a performance appraisal dashboard using HR analytics (Power BI)', 'Develop a comprehensive employee retention strategy for a tech startup', 'Create a 90-day onboarding program with measurable KPI milestones'],
    internships: ['Talent Acquisition Intern', 'HR Analytics Intern', 'Employee Engagement Intern'],
    salaryRange: '₹5L – ₹18L per annum',
  },
  'marketing': {
    roles: ['Brand Manager', 'Product Marketing Manager', 'Digital Marketing Head', 'Market Research Analyst', 'Growth Manager'],
    topCompanies: ['HUL', 'P&G', 'Nestle', 'Amazon', 'Flipkart', 'Google', 'ITC', 'L\'Oreal'],
    skills: ['Go-to-market strategy', 'Consumer behavior analytics', 'Brand positioning', 'Performance marketing alignment', 'Marketing mix modeling'],
    projectIdeas: ['Formulate a complete Go-To-Market (GTM) strategy for a new D2C brand', 'Conduct a competitive market analysis and positioning map for a SaaS startup', 'Calculate CAC/LTV and optimize a hypothetical ad spend budget of ₹1M'],
    internships: ['Brand Marketing Intern', 'Market Research Intern', 'Growth Marketing Intern'],
    salaryRange: '₹6L – ₹20L per annum',
  },
  'operations management': {
    roles: ['Operations Manager', 'Process Excellence Lead', 'Quality Assurance Manager', 'Operations Analyst', 'Plant Head'],
    topCompanies: ['Amazon', 'Flipkart', 'L&T', 'Tata Motors', 'Maruti Suzuki', 'Reliance Retail', 'Delhivery'],
    skills: ['Lean Six Sigma', 'Process optimization', 'Inventory management', 'Capacity planning', 'Operations analytics'],
    projectIdeas: ['Apply Lean Six Sigma (DMAIC) to reduce processing time in a simulated warehouse by 20%', 'Design an inventory optimization model using EOQ and safety stock formulas', 'Map and optimize a manufacturing value stream (VSM)'],
    internships: ['Process Excellence Intern', 'Operations Analyst Intern', 'Quality Control Intern'],
    salaryRange: '₹6L – ₹18L per annum',
  },
  'logistics & supply chain management': {
    roles: ['Supply Chain Manager', 'Logistics Head', 'Procurement Lead', 'Warehouse Manager', 'S&OP Analyst'],
    topCompanies: ['Delhivery', 'Blue Dart', 'DHL', 'Amazon Logistics', 'Maersk', 'Mahindra Logistics', 'Gati'],
    skills: ['Supply chain analytics', 'Vendor negotiation', 'Warehouse management systems (WMS)', 'Freight optimization', 'Inventory forecasting'],
    projectIdeas: ['Design a cross-docking network to reduce transit time by 2 days', 'Analyze and optimize a last-mile delivery route matrix using TSP models', 'Create a risk-mitigation strategy for global supply chain disruptions'],
    internships: ['Logistics Ops Intern', 'Supply Chain Analyst Intern', 'Warehouse Ops Intern'],
    salaryRange: '₹5L – ₹16L per annum',
  },
  'business analytics': {
    roles: ['Business Analyst', 'Data Analyst', 'BI Consultant', 'Pricing Analyst', 'Risk Analyst'],
    topCompanies: ['Mu Sigma', 'Fractal Analytics', 'LatentView', 'Deloitte', 'Accenture', 'TCS', 'Capgemini'],
    skills: ['Python/R programming', 'SQL & Database management', 'Data visualization (Tableau/Power BI)', 'Statistical modeling', 'Predictive analytics'],
    projectIdeas: ['Build an interactive Tableau dashboard tracking regional retail sales performance', 'Create a customer churn prediction model using logistic regression in Python', 'Analyze A/B testing data to recommend website UI changes for higher conversion'],
    internships: ['Business Intelligence Intern', 'Data Analytics Intern', 'Pricing Strategy Intern'],
    salaryRange: '₹7L – ₹20L per annum',
  },
  'data science': {
    roles: ['Data Scientist', 'Machine Learning Engineer', 'AI Specialist', 'Data Engineer', 'Quantitative Analyst'],
    topCompanies: ['Google', 'Microsoft', 'Amazon', 'Meta', 'IBM', 'TCS', 'Infosys', 'Wipro'],
    skills: ['Machine Learning algorithms', 'Deep learning (TensorFlow/PyTorch)', 'Natural Language Processing (NLP)', 'Big Data tools (Spark/Hadoop)', 'Data wrangling'],
    projectIdeas: ['Develop a recommendation engine using collaborative filtering for an e-commerce platform', 'Train a deep learning model to classify medical images with 95%+ accuracy', 'Deploy a real-time sentiment analysis API using NLP and FastAPI'],
    internships: ['Data Science Intern', 'ML Research Intern', 'Data Engineering Intern'],
    salaryRange: '₹8L – ₹25L per annum',
  },
  'artificial intelligence': {
    roles: ['AI Engineer', 'NLP Engineer', 'Computer Vision Engineer', 'AI Research Scientist', 'GenAI Architect'],
    topCompanies: ['Google', 'Microsoft', 'Amazon', 'OpenAI', 'Anthropic', 'TCS AI.Cloud', 'IBM Research'],
    skills: ['Prompt Engineering & GenAI (LLMs)', 'Computer Vision (OpenCV, YOLO)', 'TensorFlow & PyTorch', 'Data Structures', 'Model deployment (MLOps)'],
    projectIdeas: ['Build a specialized RAG (Retrieval-Augmented Generation) chatbot using enterprise documents', 'Develop a computer vision model for real-time defect detection in manufacturing', 'Fine-tune an open-source LLM for a specific industry task (e.g., legal contract review)'],
    internships: ['AI Engineering Intern', 'NLP Research Intern', 'Computer Vision Intern'],
    salaryRange: '₹10L – ₹30L per annum',
  },
  'cloud computing': {
    roles: ['Cloud Solutions Architect', 'Cloud DevOps Engineer', 'SysOps Administrator', 'Cloud Security Specialist', 'Cloud Consultant'],
    topCompanies: ['AWS', 'Microsoft Azure', 'Google Cloud', 'IBM', 'Oracle', 'Accenture', 'Capgemini'],
    skills: ['AWS/Azure/GCP fundamentals', 'Docker & Kubernetes', 'Infrastructure as Code (Terraform/Ansible)', 'Linux systems', 'Network security'],
    projectIdeas: ['Deploy a highly available, fault-tolerant web application on AWS using Auto Scaling and ELB', 'Create an automated CI/CD deployment pipeline using GitHub Actions and Docker', 'Migrate a legacy monolithic application layout into a modern microservices cloud architecture'],
    internships: ['Cloud Infrastructure Intern', 'DevOps Intern', 'Cloud Security Intern'],
    salaryRange: '₹8L – ₹22L per annum',
  },
  'cyber security': {
    roles: ['Information Security Manager', 'Ethical Hacker / Pen Tester', 'Security Architect', 'SOC Analyst', 'Cryptography Engineer'],
    topCompanies: ['Palo Alto Networks', 'CrowdStrike', 'Cisco', 'Symantec', 'TCS', 'Wipro', 'IBM Security'],
    skills: ['Penetration testing (Kali Linux, BurpSuite)', 'Network security architecture', 'Incident response (SIEM)', 'Cryptography protocols', 'Vulnerability assessment'],
    projectIdeas: ['Perform a comprehensive vulnerability assessment and penetration test on a deliberately vulnerable application (like OWASP Juice Shop)', 'Design and configure a secure network architecture including firewalls, subnets, and an IDS/IPS', 'Analyze and document a malware sample in a secure sandbox environment'],
    internships: ['SOC Analyst Intern', 'Ethical Hacking Intern', 'Information Security Intern'],
    salaryRange: '₹7L – ₹21L per annum',
  },
  'digital marketing': {
    roles: ['Digital Marketing Manager', 'SEO Strategist', 'Performance Marketing Lead', 'Social Media Head', 'Content Strategy Director'],
    topCompanies: ['Ogilvy', 'GroupM', 'Dentsu', 'Amazon', 'Google', 'Schbang', 'Kinnect', 'Performics'],
    skills: ['SEO & SEM optimization', 'Performance marketing (Meta Ads, Google Ads)', 'Content strategy & copywriting', 'Google Analytics (GA4)', 'Campaign ROI modeling'],
    projectIdeas: ['Plan, execute, and analyze a simulated ₹50k Google Search Ads campaign for a local business', 'Perform a comprehensive SEO audit and keyword strategy map for an underperforming website', 'Develop a viral 30-day cross-platform content calendar for a sustainable fashion brand'],
    internships: ['SEO & Content Intern', 'Performance Marketing Intern', 'Social Media Intern'],
    salaryRange: '₹5L – ₹16L per annum',
  }
};
