// lib/redirects-old-slugs.ts
// Maps old/truncated university slugs (indexed by Google) to current slugs.
// Each entry verified against lib/data.ts UNIVERSITIES array.
// Generated: 2026-04-17

export const OLD_SLUG_REDIRECTS: Record<string, string> = {
  'alagappa-universi': 'alagappa-university-online',
  'amrita-vishwa-vidyapee': 'amrita-vishwa-vidyapeetham-online',
  'andhra-universi': 'andhra-university-online',
  'arka-jain-universi': 'arka-jain-university-online',
  'bangalor-universi': 'bangalore-university-online',
  'bharath-institut-of-higher': 'bharath-university-online',
  'bharathi-universi': 'bharathidasan-university-online',
  'chitkara-universi': 'chitkara-university-online',
  'dayanand-sagar-universi': 'dayananda-sagar-university-online',
  'deen-dayal-upadhyay-gorakhpu': 'deen-dayal-upadhyay-gorakhpur-university-online',
  'desh-bhagat-universi': 'desh-bhagat-university-online',
  'devi-ahilya-vishwavi': 'devi-ahilya-vishwavidyalaya-online',
  'gla-universi': 'gla-university-online',
  'gls-universi': 'gls-university-online',
  'guru-ghasidas-vishwavi': 'guru-ghasidas-vishwavidyalaya-online',
  'guru-gobind-singh-indrapra': 'guru-gobind-singh-indraprastha-university-online',
  'guru-kashi-universi': 'guru-kashi-university-online',
  'hindusta-institut-of-technolo': 'hindustan-institute-technology-online',
  'icfai-foundati-for-higher': 'icfai-university-online',
  'jaipur-national-universi': 'jaipur-national-university-online',
  'jaypee-universi': 'jaypee-university-online',
  'kalasali-academy-of-research': 'kalasalingam-university-online',
  'kalinga-institut-of-industri': 'kalinga-institute-industrial-technology-online',
  'karnatak-state-open-universi': 'karnataka-state-open-university-online',
  'mahatma-jyotiba-phule-rohilkha': 'mahatma-jyotiba-phule-rohilkhand-university-online',
  'mangalay-universi': 'mangalayatan-university-online',
  'manonman-sundaran-universi': 'manonmaniam-sundaranar-university-online',
  'marwadi-universi': 'marwadi-university-online',
  'meenaksh-academy-of-higher': 'meenakshi-academy-higher-education-online',
  'pp-savani-universi': 'pp-savani-university-online',
  'shanmugh-arts-science-technolo': 'shanmugha-arts-science-technology-research-online',
  'shri-ramasamy-memorial-univers': 'shri-ramasamy-memorial-university-online',
  'sri-ramachandra-universi': 'sri-ramachandra-university-online',
  'teerthanker-universi': 'teerthanker-mahaveer-university-online',
  'universi-of-mysore': 'university-of-mysore-online',
  'vellore-institut-of-technolo': 'vit-vellore-online',
  'yenepoya-universi': 'yenepoya-university-online',
  'symbiosis': 'symbiosis-university-online',
  'nmims': 'nmims-online',
  'mahe-manipal': 'manipal-academy-higher-education-online',
  'jain': 'jain-university-online',
  'lpu': 'lovely-professional-university-online',
  'sikkim-manipal': 'sikkim-manipal-university-online',
};
