export const UNIVERSITY_REVIEWS: Record<string, Array<{
  name: string
  city: string
  program: string
  rating: number
  date: string
  review: string
}>> = {
  'chandigarh': [
    { name: 'Rahul Sharma', city: 'Delhi', program: 'MBA Finance', rating: 4, date: 'March 2026', review: 'Took admission in CU Online MBA Finance last year. LMS is decent, study material is good. Faculty is responsive on discussion forum. Was confused between CU and Amity but Edify counsellor explained the difference clearly based on my profile. Happy with decision overall. Placement support is average but degree is well recognised everywhere.' },
    { name: 'Priya Mehta', city: 'Chandigarh', program: 'MBA HR', rating: 5, date: 'February 2026', review: 'Really satisfied with CU Online MBA HR. Specialisation content is relevant and case studies are practical. Got salary hike of around 25% after completing first year itself. Edify team was very helpful during admission, answered all queries about validity and recognition very patiently.' },
    { name: 'Vikram Patel', city: 'Ahmedabad', program: 'MBA Marketing', rating: 4, date: 'January 2026', review: 'Good program, flexible schedule works well alongside job. Weekend live classes are mostly on time. Occasional technical issues on exam portal but gets resolved. NIRF ranking gives confidence. Edify helped me compare fees across universities before deciding.' },
  ],
  'amity': [
    { name: 'Sneha Gupta', city: 'Noida', program: 'MBA Marketing', rating: 5, date: 'March 2026', review: 'Amity brand name really helps in interviews. Interviewers recognise it immediately. Content quality is very good, Harvard case studies are a real bonus. Fees are higher side but worth it for brand value. Edify counsellor gave honest comparison without pushing any particular university which I appreciated.' },
    { name: 'Ajay Verma', city: 'Lucknow', program: 'MBA Finance', rating: 4, date: 'February 2026', review: 'Decent experience overall. Study material is comprehensive and updated. Exams are online proctored which is very convenient. Office accepted the degree without any questions. QS ranking of Amity adds credibility. Edify helped me understand difference between Amity and LPU based on my budget and career goals.' },
    { name: 'Deepika Nair', city: 'Kochi', program: 'MBA HR', rating: 4, date: 'January 2026', review: 'Good program for working professionals. Live sessions on weekends work well with office schedule. Faculty is experienced and helpful. Got promotion after completing the degree. Student support response time is sometimes slow but overall positive experience. Edify was upfront about pros and cons which built trust.' },
  ],
  'lpu': [
    { name: 'Manish Kumar', city: 'Jalandhar', program: 'MBA', rating: 4, date: 'March 2026', review: 'LPU Online is excellent value for money. NIRF rank is very impressive for the fees they charge. Study material is solid and exams are fair. LMS portal is easy to navigate. Was confused about so many universities but Edify comparison tool helped me filter based on NIRF rank and budget which made decision much easier.' },
    { name: 'Pooja Singh', city: 'Jaipur', program: 'MBA Finance', rating: 3, date: 'February 2026', review: 'Overall okay experience. Content is good but placement support could definitely be better. Degree is valid everywhere which is the most important thing for me. Fee is very affordable compared to universities with similar ranking. Edify team explained PSU eligibility criteria clearly which was my main concern before enrolling.' },
    { name: 'Arjun Tiwari', city: 'Bhopal', program: 'MBA Marketing', rating: 4, date: 'January 2026', review: 'Happy with the choice overall. NAAC A++ university at this fee range is very hard to find. Live classes are interactive and engaging. Assignments are practical and relevant to industry. Would have liked more company interaction but solid program. edifyedu.in was very helpful for comparing syllabus across universities.' },
  ],
  'mahe-manipal': [
    { name: 'Karthik Reddy', city: 'Hyderabad', program: 'MBA', rating: 5, date: 'March 2026', review: 'Manipal Online is genuinely premium quality. NIRF 14 and the brand recognition is excellent. Coursera integration gives real global credibility. Fees are higher but degree opens international doors too since WES recognised. Edify counsellor spent quality time explaining difference between Manipal MUJ and MAHE which helped a lot.' },
    { name: 'Ritu Sharma', city: 'Pune', program: 'MBA Finance', rating: 5, date: 'February 2026', review: 'Excellent program without doubt. Coursera certifications bundled with MBA add real value to the resume. Faculty quality is top notch. Employer was very impressed with Manipal brand. Slightly expensive but totally worth the investment for long term career growth. Edify has the most accurate fee comparison I found online.' },
    { name: 'Sameer Khan', city: 'Mumbai', program: 'MBA Marketing', rating: 4, date: 'January 2026', review: 'Good experience overall. Live sessions are well structured. LMS is smooth with no major technical issues. International faculty exposure is a definite plus over other options. Got a better job offer after completing the program. More placement drives would be helpful. Used Edify to shortlist top 3 universities before final decision.' },
  ],
  'nmims': [
    { name: 'Anita Desai', city: 'Mumbai', program: 'MBA', rating: 5, date: 'March 2026', review: 'NMIMS brand is truly unmatched in BFSI sector. Got interview calls from 3 banks just because of NMIMS name on resume. Online program quality is excellent throughout. Faculty are practising industry professionals not just academics. Edify gave honest comparison between NMIMS and Symbiosis without pushing either one.' },
    { name: 'Rohan Joshi', city: 'Bangalore', program: 'MBA Finance', rating: 4, date: 'February 2026', review: 'NMIMS Online MBA Finance is very focused and career oriented. Content is regularly updated and relevant to current industry. Exams are strict which maintains the quality. NAAC A++ accreditation is well deserved. Happy with overall experience. Edify website helped verify NMIMS UGC DEB approval status before I took admission.' },
    { name: 'Kavya Menon', city: 'Chennai', program: 'MBA Marketing', rating: 4, date: 'January 2026', review: 'Good program overall. Faculty interaction is noticeably more than other online programs I explored. Assignments are genuinely challenging which is good for learning. Degree is widely accepted by employers. Found Edify very neutral and informative compared to other counselling platforms which push specific universities.' },
  ],
  'symbiosis': [
    { name: 'Nikhil Deshmukh', city: 'Pune', program: 'MBA', rating: 5, date: 'March 2026', review: 'Symbiosis brand carries a lot of weight especially in Pune and Maharashtra. Zero exams policy is a huge relief for working professionals. Assignment based evaluation keeps you learning continuously. NAAC A++ and NIRF 19 speaks for itself. Edify helped me understand that Symbiosis is assignment based while others are exam based which was a key deciding factor.' },
    { name: 'Swati Joshi', city: 'Mumbai', program: 'MBA Finance', rating: 4, date: 'February 2026', review: 'Very happy with Symbiosis Online MBA Finance. No examination stress is a big plus. Content is industry relevant and faculty are approachable. Degree is well recognised in financial services sector. Edify comparison was very detailed and helped me understand the real difference between various online MBA options.' },
    { name: 'Rajan Kulkarni', city: 'Nagpur', program: 'MBA HR', rating: 4, date: 'January 2026', review: 'Symbiosis for HR is a great choice. The brand is well respected in HR circles. Assignment based learning is more practical than exam based. Got a good lateral move after completing the program. Edify counselling service was helpful and they gave honest opinion based on my work experience and goals.' },
  ],
  'jain': [
    { name: 'Sowmya Rao', city: 'Bangalore', program: 'MBA', rating: 4, date: 'March 2026', review: 'JAIN Online is a solid choice for Bangalore based students. NAAC A++ and NIRF 62 gives credibility. Program content is updated and industry relevant. LMS is user friendly. Edify helped me shortlist JAIN vs Amity and explained the practical differences clearly. Made the right choice based on their guidance.' },
    { name: 'Prashanth Kumar', city: 'Mysore', program: 'MBA Finance', rating: 4, date: 'February 2026', review: 'Good program overall. Content quality is good and faculty are helpful. Exams are online which is convenient. Degree is accepted by employers without any issues. Fees are reasonable for a NAAC A++ institution. Found edifyedu.in very useful for verifying UGC DEB approval and comparing with other options.' },
    { name: 'Divya Krishnamurthy', city: 'Chennai', program: 'MBA Marketing', rating: 3, date: 'January 2026', review: 'Average to good experience. Study material could be more detailed in some subjects. Live sessions are helpful. Degree validity is not an issue at all since UGC approved. Placement support is basic. Edify site has accurate information which matched what I verified from the official university website.' },
  ],
}

export const GENERIC_REVIEWS = [
  { name: 'Suresh Yadav', city: 'Delhi', program: 'MBA', rating: 4, date: 'March 2026', review: 'Good online MBA program. Flexibility to study while working is the biggest advantage of online mode. UGC DEB approval gives full confidence about degree validity. Edify counselling team helped me identify which university suits my profile and budget correctly. Very happy with overall admission process and support received.' },
  { name: 'Meera Krishnan', city: 'Bangalore', program: 'MBA Finance', rating: 4, date: 'February 2026', review: 'Decent program with good and updated study material. Live sessions on weekends are very convenient for working professionals. NAAC accreditation confirms the quality of education. Got a salary hike after completing the degree. Edify site has very accurate information about fees and eligibility which I cross verified from university website.' },
  { name: 'Amit Saxena', city: 'Lucknow', program: 'MBA Marketing', rating: 3, date: 'January 2026', review: 'Overall satisfactory experience with the program. Content quality is good. Exams are fair and manageable. Degree is fully recognised by my employer without any issues. Recommend checking the university NIRF rank carefully before taking admission. Edify comparison feature was very useful for my shortlisting process.' },
]
