// lib/site-config.ts — auto-generated by CMS sync
// Edit values in the "🌐 Site Config" Google Sheet, then sync

export const SITE_CONFIG = {
  "site_name": "Edify",
  "tagline": "Best Online Degrees India 2026",
  "admissions_batch": "2026-06-30T18:30:00.000Z",
  "admissions_deadline": "October 15–30, 2026",
  "contact_email": "hello@edifyedu.in",
  "whatsapp_number": "917061285806",
  "hero_headline": "Compare 127+ UGC Approved Online Universities",
  "banner_text": "Admissions Open — July 2026 batch closing October 15–30"
} as const

export type SiteConfigKey = keyof typeof SITE_CONFIG
export function getSiteConfig(key: SiteConfigKey): string {
  return SITE_CONFIG[key] ?? ''
}
