// UNIVERSITY_LOGOS — auto-generated by CMS sync on 2026-03-25
export const UNIVERSITY_LOGOS: Record<string, string> = {}

export function getUniversityLogo(uniId: string): string | null {
  return UNIVERSITY_LOGOS[uniId] || null
}
