// Phase 7.3: Patch NMIMS 5 spec JSONs — rewrite §5 whoHires, §6 skills, §7 comparisons
const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, '../lib/data/page-content');

const patches = {
  'business-management': {
    whoHires: "Business Management MBA graduates from NMIMS Online are hired across these industries and roles:\n\n**Industries:** Technology consulting, BFSI digital functions, E-commerce operations, IT services, Corporate strategy\n\n**Entry-level roles:** Business Analyst, Digital Transformation Analyst, IT Business Partner, Associate Product Manager\n\n**Mid-level roles (3-5 years experience):** Business Manager, Product Manager, Digital Transformation Manager, IT Strategy Manager\n\n**Senior roles (7+ years):** VP Business Strategy, Head of Digital, Chief Digital Officer, Managing Director (consulting practice)\n\n**Top hiring organisations:** TCS, Infosys, Accenture, Deloitte Digital, HDFC Bank Digital, Razorpay, Zepto, Mahindra Group Innovation, Wipro Digital",

    skills: "The NMIMS Business Management specialisation builds skills that technology-forward employers test at business manager and head of digital levels:\n\n**Technical skills:**\n- Organisational Design: structure-strategy alignment, reporting layer design, and matrix organisation management for complex enterprises\n- Cybersecurity and Data Governance: security risk assessment, data privacy compliance, and technology governance for business-owned digital operations\n- Digital Product Management: MVP scoping, product roadmap management, and agile sprint oversight for technology product companies\n- AI Concepts: evaluating AI vendor proposals, writing AI product requirements, and managing AI implementation risk for non-technical managers\n\n**Applied skills:**\n- Business Process Transformation: process mapping, RPA decision frameworks, and change management for operational digitalisation programmes\n- Supply Chain Management: supply chain resilience, vendor management, and distribution strategy across business domains\n\n**Soft skills:** Building business cases for technology investment, managing cross-functional digital transformation projects, and presenting digital strategy to non-technical boards and investors.",

    comparisons: "Comparing NMIMS Online MBA Business Management against peers:\n\n**vs Amity Online MBA General Management:** Amity is NAAC A+ and NIRF #22 at Rs 2,25,000. Amity General Management covers strategy, finance, brand management, and operations breadth. NMIMS Business Management includes technology subjects: cybersecurity, digital product design, AI concepts, and agile. For professionals at technology companies or in digital transformation roles, NMIMS is more differentiated. For traditional management roles across manufacturing and finance, Amity General Management is more targeted.\n\n**vs Symbiosis Online MBA Operations Management:** Symbiosis is NAAC A+ at competitive fees with strong recognition for traditional business management roles. NMIMS Business Management has a technology-forward positioning that makes it more relevant for digital business and IT-adjacent management careers. Choose based on whether your target role is in digital-era business or traditional operations management.\n\n**vs IGNOU MBA:** IGNOU is UGC-DEB approved at significantly lower fees with open enrollment. IGNOU covers general management broadly without dedicated technology management subjects. NMIMS Business Management at Rs 1.96L carries stronger employer recognition at private sector technology and BFSI companies. IGNOU MBA is better suited for government sector and PSU employment tracks."
  },

  'financial-management': {
    whoHires: "Financial Management MBA graduates from NMIMS Online are hired across these industries and roles:\n\n**Industries:** Investment banking, Corporate finance, Asset management, BFSI, Big Four financial advisory\n\n**Entry-level roles:** Corporate Finance Analyst, Treasury Analyst, Investment Banking Analyst, FP&A Analyst\n\n**Mid-level roles (3-5 years experience):** Corporate Finance Manager, VP Treasury, Portfolio Manager, Head of FP&A\n\n**Senior roles (7+ years):** CFO, MD (investment banking), Fund Manager, Head of Corporate Finance\n\n**Top hiring organisations:** Kotak Mahindra Bank, HDFC Bank Corporate Banking, ICICI Bank Investment Banking, Axis Capital, JM Financial, Deloitte Financial Advisory, EY Transaction Advisory, KPMG Deal Advisory, Motilal Oswal, Reliance Industries Finance",

    skills: "The NMIMS Financial Management specialisation builds skills that corporate finance and capital markets employers test at MBA-level interviews:\n\n**Technical skills:**\n- Business Valuation: DCF modelling, comparable company analysis, EV/EBITDA multiples, and M&A acquisition price justification for investment banking and PE fund interviews\n- Financial Derivatives: options pricing concepts, futures and forwards hedging strategy, and swap application in corporate treasury for risk management desk roles\n- Capital Market Analysis: equity and bond market mechanics, portfolio construction, SEBI regulations, and risk-adjusted return presentation for wealth and asset management\n- Corporate Tax Planning: income tax structuring for companies, GST implications, and transfer pricing documentation for financial controller and CFO-track interviews\n\n**Applied skills:**\n- Investment Banking Process: ECM and DCM transaction process knowledge, pitch book structure, and M&A deal mechanics for IB analyst and associate roles\n- International Finance: FX risk hedging, cross-border treasury operations, and cross-currency capital structuring for MNC treasury and international banking teams\n\n**Soft skills:** Presenting financial models to investment committees, structuring credit memos for lending decisions, and defending valuation assumptions in M&A negotiations with counterparties.",

    comparisons: "Comparing NMIMS Online MBA Financial Management against peers:\n\n**vs Amity Online MBA Finance and Accounting Management:** Amity is NAAC A+ and NIRF #22 at Rs 2,25,000. Amity Finance covers accounting depth and taxation alongside financial management. NMIMS Finance focuses on capital markets: business valuation, financial derivatives, and investment banking process. For investment banking and capital markets careers in Mumbai, NMIMS Financial Management is more targeted. For CFO-track and accounting-heavy roles, Amity Finance and Accounting Management is competitive.\n\n**vs Symbiosis Online MBA Finance:** Symbiosis is NAAC A+ at competitive fees with strong recognition for finance roles at Pune-headquartered corporates and PSU banking. NMIMS Financial Management carries stronger employer recognition specifically in Mumbai financial services and investment banking hiring. For BFSI sector careers in western India, choose based on target employer geography.\n\n**vs JAIN Online MBA Finance:** JAIN is NAAC A++ at competitive fees with growing Bangalore recognition for technology and startup finance roles. JAIN Finance covers corporate finance and banking broadly. NMIMS carries stronger brand equity at Tier 1 investment banks, asset managers, and Mumbai-based BFSI firms. For careers specifically in Mumbai BFSI and capital markets, NMIMS Financial Management provides meaningfully stronger employer recognition."
  },

  'marketing-management': {
    whoHires: "Marketing Management MBA graduates from NMIMS Online are hired across these industries and roles:\n\n**Industries:** FMCG, Consumer technology, Digital marketing agencies, Media companies, D2C brands\n\n**Entry-level roles:** Brand Executive (management track), Marketing Manager, Digital Marketing Manager, Category Analyst\n\n**Mid-level roles (3-5 years experience):** Brand Manager, Senior Brand Manager, Head of Digital Marketing, Trade Marketing Manager\n\n**Senior roles (7+ years):** Marketing Director, VP Marketing, CMO, Group Brand Manager\n\n**Top hiring organisations:** HUL, P&G India, Nestle India, Mondelez, Reckitt, Dabur, Marico, Godrej Consumer Products, ITC FMCG, GroupM, Publicis India, Swiggy, Zomato",

    skills: "The NMIMS Marketing Management specialisation builds skills that FMCG and consumer brand employers test at brand manager and marketing head levels:\n\n**Technical skills:**\n- Brand Management: brand equity measurement using brand funnel and NPS, positioning statement development, brand architecture decisions, and brand extension risk assessment for FMCG interviews\n- Consumer Behaviour: buyer persona development, purchase decision tree analysis, category driver identification, and consumer insight translation into creative brief\n- Integrated Marketing Communications: ATL and BTL channel planning, media mix optimisation, campaign brief writing, and unified communication measurement for brand campaigns\n- Sales Management: field sales team structure, distributor management, secondary sales tracking, and sales incentive design for FMCG national sales roles\n\n**Applied skills:**\n- International Marketing: global brand adaptation strategy, distribution in export markets, and cultural insight for cross-border FMCG and consumer campaigns\n- Digital Marketing: digital channel integration, SEO fundamentals, social media strategy, and performance marketing basics for brand campaign management\n\n**Soft skills:** Writing creative briefs for external agencies, presenting brand health data to senior management, and defending marketing investment against finance teams in P&L reviews.",

    comparisons: "Comparing NMIMS Online MBA Marketing Management against peers:\n\n**vs Amity Online MBA Marketing and Sales Management:** Amity is NAAC A+ and NIRF #22 at Rs 2,25,000. Amity Marketing and Sales covers sales management and communications broadly. NMIMS Marketing Management adds dedicated International Marketing, Services Marketing, and Brand Management depth. For FMCG brand management careers in Mumbai, NMIMS brand recognition is stronger. For pan-India marketing and sales management roles at mid-size companies, Amity NIRF #22 is competitive.\n\n**vs Symbiosis Online MBA Marketing:** Symbiosis is NAAC A+ at competitive fees with strong recognition in the Pune-Maharashtra corporate ecosystem, particularly for Bajaj, Kirloskar, and Pune-based FMCG companies. NMIMS carries stronger recognition at Mumbai-headquartered FMCG and consumer technology employers. Choose based on target employer geography and sector.\n\n**vs Chandigarh University Online MBA Marketing Management:** Chandigarh University is NAAC A++ with active placement infrastructure in north India. For marketing management roles at north India-based consumer companies and retail, Chandigarh University has a strong campus placement network. NMIMS carries significantly stronger brand recognition at pan-India FMCG companies and the Mumbai marketing ecosystem."
  },

  'operations-and-data-sciences-management': {
    whoHires: "Operations and Data Sciences Management MBA graduates from NMIMS Online are hired across these industries and roles:\n\n**Industries:** E-commerce and quick-commerce operations, FMCG supply chain, Manufacturing analytics, IT-enabled operations, Management consulting\n\n**Entry-level roles:** Supply Chain Analyst, Operations Analytics Analyst, Procurement Manager, Project Manager\n\n**Mid-level roles (3-5 years experience):** Supply Chain Manager, Operations Analytics Manager, Procurement Head, Head of Logistics\n\n**Senior roles (7+ years):** VP Supply Chain, COO, Head of Procurement, Supply Chain Transformation Director\n\n**Top hiring organisations:** Amazon India Operations, Flipkart Fulfilment, Reliance Retail Supply Chain, Zomato Operations Analytics, Infosys Supply Chain Consulting, Accenture Operations, HUL Supply Chain, Nestle Manufacturing, Tata Motors, McKinsey Operations Practice",

    skills: "The NMIMS Operations and Data Sciences Management specialisation builds a dual skill set that operations analytics employers specifically seek:\n\n**Technical skills:**\n- Supply Chain Management: demand forecasting, inventory optimisation, supply chain network design, and supply chain risk management for manufacturing and e-commerce operations\n- IoT and Big Data in Operations: connected factory sensor data interpretation, predictive maintenance analytics, and IoT-enabled supply chain visibility for smart manufacturing roles\n- Operations Analytics: demand forecasting models, route optimisation algorithms, and production scheduling analytics in Power BI for data-driven operations leadership\n- Total Quality Management: Six Sigma DMAIC problem-solving, SPC chart interpretation, ISO 9001 management system design, and quality audit management\n\n**Applied skills:**\n- Strategic Sourcing: vendor evaluation, e-procurement platform management, TCO analysis, and category strategy for procurement manager and CPO-track roles\n- EDA and Data Visualisation: exploratory data analysis on operations datasets, operational dashboard design, and communicating supply chain insights to non-technical management\n\n**Soft skills:** Presenting supply chain analytics to the COO, building business cases for operations technology investment, and managing cross-functional supply chain transformation projects.",

    comparisons: "Comparing NMIMS Online MBA Operations and Data Sciences Management against peers:\n\n**vs Amity Online MBA Business Analytics:** Amity is NAAC A+ and NIRF #22 at Rs 2,25,000. Amity Business Analytics focuses on Power BI, supervised ML, and forecasting across domains. NMIMS Operations and Data Sciences combines supply chain management depth with analytics for an industry-specific operations credential. For analytics-first careers across multiple domains, Amity Business Analytics is more flexible. For data-driven operations and supply chain leadership, NMIMS is more directly positioned.\n\n**vs MUJ Online MBA Analytics and Data Science:** MUJ is NAAC A+ and NIRF #58 at Rs 1,53,000-1,80,000. MUJ Analytics covers Python/R, advanced ML, and unstructured data for a more technically deep analytics credential. NMIMS Operations and Data Sciences pairs supply chain management with analytics for a business operations profile. For pure data science roles, MUJ Analytics is more technical. For operations management with analytics capability, NMIMS is more targeted.\n\n**vs Amity Online MBA Production and Operations Management:** Amity Production and Operations covers lean manufacturing, TQM, and supply chain without the data sciences layer. NMIMS adds IoT strategy, EDA, and operations analytics that make it more applicable to e-commerce operations, logistics analytics, and tech-enabled supply chain. For traditional manufacturing plant management, Amity Production and Operations is more targeted."
  },

  'human-resource-management': {
    whoHires: "Human Resource Management MBA graduates from NMIMS Online are hired across these industries and roles:\n\n**Industries:** BFSI, IT services, Manufacturing, FMCG, HR consulting and staffing\n\n**Entry-level roles:** HR Generalist (management track), Recruitment Manager, HR Operations Manager, Compensation Analyst\n\n**Mid-level roles (3-5 years experience):** HRBP, HR Manager, Talent Acquisition Manager, Compensation and Benefits Manager, L&D Manager\n\n**Senior roles (7+ years):** HR Head, CHRO, VP Human Resources, Head of Talent Management\n\n**Top hiring organisations:** HDFC Bank, ICICI Bank, Kotak Mahindra Bank, TCS, Infosys, Wipro, HUL, Aditya Birla Group, Mahindra Group, Larsen and Toubro, Aon Hewitt, Mercer India, Korn Ferry India",

    skills: "The NMIMS Human Resource Management specialisation builds skills that large corporate and BFSI employers test at HRBP and HR head level:\n\n**Technical skills:**\n- Compensation Design: salary grading, variable pay programme design, and benefits benchmarking against market data for Total Rewards Head and compensation manager roles\n- Industrial Relations: union management, standing order compliance, disciplinary inquiry procedures, and collective bargaining for manufacturing and large-scale service HR roles\n- Performance Management: KRA-KPI cascading, rating calibration process, and linking performance outputs to compensation and promotion decisions across large organisations\n- Manpower Planning: workforce demand forecasting, succession pipeline management, and skill gap closure strategy for HR Business Partners at growing organisations\n\n**Applied skills:**\n- Organisational Development: change management methodology (Kotter, ADKAR), culture assessment tools, and OD intervention design for CHRO and HR transformation roles\n- Learning and Development: training needs analysis, learning programme design, and measuring L&D ROI for corporate university and L&D Head roles\n\n**Soft skills:** Managing the CHRO-CEO relationship, presenting HR metrics and talent dashboards to the board, and navigating industrial disputes without production disruption.",

    comparisons: "Comparing NMIMS Online MBA Human Resource Management against peers:\n\n**vs Amity Online MBA Human Resource Management:** Amity is NAAC A+ and NIRF #22 at Rs 2,25,000. Amity HRM covers core HR management comprehensively. NMIMS HRM adds Industrial Relations and Labour Laws, Emotional Intelligence, and Corporate Sustainability as dedicated subjects. For BFSI and large corporate HR roles in Mumbai, NMIMS brand carries stronger alumni recognition. For pan-India HR management roles at mid-size companies, Amity NIRF #22 is competitive.\n\n**vs Amity Online MBA HR Analytics:** Amity HR Analytics is the data-oriented HR credential, covering people analytics platforms, HRIS, and workforce intelligence. NMIMS HRM is stronger on classical HR management disciplines: compensation design, industrial relations, OD, and performance management. For analytics-focused HR careers, Amity HR Analytics is more differentiated. For generalist HR leadership roles at large corporates, NMIMS HRM provides broader coverage.\n\n**vs Symbiosis Online MBA Human Resource Management:** Symbiosis is NAAC A+ at competitive fees with strong recognition in the Pune-Maharashtra corporate ecosystem. For manufacturing sector HR roles in Maharashtra (automotive, pharma), both Symbiosis and NMIMS are strong options. NMIMS brand has an edge in BFSI and Mumbai-headquartered large corporates. Choose based on target sector and employer geography."
  }
};

Object.entries(patches).forEach(([spec, patch]) => {
  const filePath = path.join(BASE, 'nmims-online-mba-' + spec + '.json');
  const j = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  j.sections.whoHires.body = patch.whoHires;
  j.sections.skills.body = patch.skills;
  j.sections.comparisons.body = patch.comparisons;
  j.metadata.phase73Updated = '2026-04-21';
  fs.writeFileSync(filePath, JSON.stringify(j, null, 2) + '\n', 'utf8');
  console.log('Updated: nmims-online-mba-' + spec + '.json');
});
